### ISSUE TITLE
Mac: add ability use OS X system-level user-added keyboard shortcuts

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#1]
A user has requested that the WordPress.com Desktop app for Mac be able to use the Keyboard shortcuts built into Mac under System Preferences > Keyboard > Text.

These shortcuts work with WordPress.com from within the browser, but no within the app.

**Comment by briankc** [comment]
This is probably a Chromium issue. A quick test at WordPress.com using Google Chrome reveals that the keyboard shortcuts don't work there either, but they do work in Safari.

**Comment by mkaz** [comment]
Agreed @briankc - looks related to this set of issues https://github.com/electron/electron/issues/1334 which requires a fix within Chromium. If/when fixed there WordPress Desktop app will inherit the fix with Electron update
