### ISSUE TITLE
Support Basic Spellcheck

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#10]
Enable support of browser spell check, to underline the misspelled words.

**Comment by beaucollins** [comment]
Windows and Mac supports spellchecking now. Linux builds still not supported.

**Comment by krainboltgreene** [comment]
So I'm using v1.2.1 and while the release notes say this is fixed it's not. There's not even a right click ability on text. What exactly got "fixed"?

**Comment by beaucollins** [comment]
@krainboltgreene the current support for spellcheck is to only show misspelled words with a red line under incorrect words.

Which OS are you running on? Are you not seeing the red underlines?

**Comment by lancewillett** [comment]
I'm not seeing the spellchecking in the post editor on OS X 10.11.1 El Capitan and Mac app version 1.2.1.

<img width="875" alt="screen shot 2015-12-30 at 10 35 04" src="https://cloud.githubusercontent.com/assets/66797/12054459/17f684d2-aee1-11e5-8db3-5ad39a37f24a.png">

**Comment by mkaz** [comment]
Closing in favor of other bugs, basic spellcheck already implemented.
In 1.3.1 it will be working fine for English onr Mac and Linux

#101 - addresses spellcheck in other languages
#129 - spellchecker does not work on Windows

#130 & #138 - default disables spellcheck, can enable in preferences due to performance issues with long posts
