### ISSUE TITLE
Map Alt + ← (Windows) and ⌘ + ← (Mac) to history.back();

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-desktop#100]
There seems to be enough of a desire to bring more "back" button keyboard shortcuts to the app. Even if we don't store a full history of page navigation, shortcut keys can be helpful.

The shortcut key for "back" is Al ← on Windows, and ⌘ ← on Mac.

**Comment by rachelmcr** [comment]
A back shortcut would be especially helpful after you use the shortcut Cmd+N (Mac app) to start a new post. If you have multiple blogs, this opens a site picker and there's no way to go back from there. Full details in this post: https://test.wordpress.com/2016/10/14/session-notes-editor-domain-claim-vscroll-workflow-automation-desktop-app-testflight/
