### ISSUE TITLE
Editor, Preview, Mac: Preview out of sync with editor

### ISSUE THREAD

**Issue by ryanboren** [Automattic/wp-desktop#107]
Preview is often out of sync with post content. Here's a post with a featured image and gallery.
![screen shot 2016-02-29 at 3 00 52 pm](https://cloud.githubusercontent.com/assets/2047747/13409122/0e3bdd3e-def7-11e5-94f8-5ffdb7a70487.png)

The featured image and gallery do not show in preview. Notice also that the title and conten are out-of-date. The title was changed from Aluminum to Poured Aluminum, but the change does not reflect in preview.

![screen shot 2016-02-29 at 3 00 56 pm](https://cloud.githubusercontent.com/assets/2047747/13409123/0e4a5062-def7-11e5-9e1e-1d5a5d985bb9.png)

I've been seeing this for awhile. Here's an example from December.

![screen_shot_2015-12-14_at_7 07 50_pm](https://cloud.githubusercontent.com/assets/2047747/13409225/9c80e8aa-def7-11e5-9ce0-429d097890a7.png)
![screen_shot_2015-12-14_at_7 07 54_pm](https://cloud.githubusercontent.com/assets/2047747/13409224/9c810650-def7-11e5-9c0d-ea7931272d99.png)

Leaving the editor via the <-Posts back navigation and then returning to the editor does not fix the problem. Quitting and restarting the app and returning to the editor does fix the problem.

**Comment by lancewillett** [comment]
@mkaz Actionable? Thoughts?

**Comment by mkaz** [comment]
@lancewillett yeh, we hopefully can fix. Sounds like a possible cache issue

**Comment by lancewillett** [comment]
This came up again today in internal discussion about why more people don't use (or test new releases of) the desktop app. This kind of thing is a blocker to flow.

**Comment by mjangda** [comment]
So far, I haven't been able to reproduce on 1.3.0 with my WP.com blog (changes to title, content, featured image, category/tags are all reflected on Preview). More details on reproducing would be helpful.

**Comment by rachelmcr** [comment]
I reproduced this on 1.3.0 just now while writing a post a private WP.com blog.

I finished writing the post and the sidebar said "Draft saved a few seconds ago." However, only the first two words of the title are appearing in the preview ("To Test:"). The rest of the title and post content aren't showing in the app's preview, although when I open the preview in a web browser the full post is showing there.

I'll do more testing around this to see if I can come up with reliable steps to reproduce.

**Comment by rachelmcr** [comment]
@mjangda - I am consistently reproducing this issue in 1.3.1-alpha. Only the content that was in the editor before the first auto-save is visible in the preview. Any content I add to the post after that first auto-save is never visible in the preview (no matter whether that content is auto-saved or if I manually click the "Save" link in the editor after that).

If I click out of the editor to My Sites > Blog Posts > Drafts > select the draft to open it in the editor again, the full draft appears when I preview it.

This isn't an issue for me in Calypso web — the full post preview always appears in the editor there.

**Comment by ryanboren** [comment]
Preview is still broken for me as well. I don't use the app often because of this bug. When post flow is buggy, I go elsewhere.

**Comment by ryanboren** [comment]
I can't find a consistent pattern that reproduces this, but do a handful of posts and you will see it.

Patterns I've tried:

* Restarting the app and seeing if the first post succeeds and subsequent ones do not. This held for two iterations but not on a third.
* Previewing after setting the title but before adding content to avoid to bug. This worked for two iterations but not on a third.

**Comment by frosty** [comment]
I'm having the same issue right now in the app with 1.3.1 – I've written a whole post (40 revisions), but when I preview I see no content, only the title. It's fine on the web.

@rachelmcr's fix of going My Sites > Blog Posts > Drafts doesn't seem to help me at all. The preview's still empty when I come back to it.

**Comment by mjangda** [comment]
Okay, was able to get some helpful debug info from @frosty and finally able to reproduce it myself as well.

The key is this part of the preview iframe request: `Status Code:200 OK (from cache)`

Basically, Electron (or maybe the Chromium layer?) is caching the preview and showing an older version. Best option here is to force it to not pull from cache.

**Comment by mjangda** [comment]
Could try using the `disable-http-cache` switch (https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md#--disable-http-cache) or append a cache buster to the preview URL.

**Comment by nerdysandy** [comment]
Also, reported on `1367155-zd-woothemes`

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
