### ISSUE TITLE
Add Signup / Create Account / Lost Password Flow

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#11]
From @johngodley 

Currently on the login page there is a link to create a new account and recover a forgotten password. Both of these open in the browser.

Calypso has some new user code already so at some point it will probably make sense to enable this and bring it into the app.

The buttons are relatively easy, but a problem is that Calypso is designed for `wpcom-proxy-request` and we use `wpcom-xhr-request` so any errors in the site creation flow and reported incorrectly.

The signup link is more difficult as the login page is using the LoggedOutOauth layout, which doesn't have all the stuff setup that the signup flow needs. We'd need to be able to switch layout.

**Comment by mjangda** [comment]
Signup flow at https://github.com/Automattic/wp-calypso/pull/3221

**Comment by mkaz** [comment]
Deployed in v1.3.0
