### ISSUE TITLE
Add back/forward navigation and other enhancements to right-click context menu

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-desktop#117]
In an upcoming release, a right-click menu will be added inside textfields, and when text is selected.

In a future release after that it would be nice to explore more right-click options. For example, when no text is selected, and not right-clicking a textfield, back/forward history navigation would be nice:

![screen shot 2016-03-10 at 19 07 13](https://cloud.githubusercontent.com/assets/1204802/13679424/f82ca01e-e6f3-11e5-8be4-a220af3af8c5.png)

When right-clicking a hyperlink:

![screen shot 2016-03-10 at 19 11 32](https://cloud.githubusercontent.com/assets/1204802/13679432/fde7894c-e6f3-11e5-842c-35a46e85b99a.png)

When right-clicking an image:

![screen shot 2016-03-10 at 19 11 43](https://cloud.githubusercontent.com/assets/1204802/13679439/03680f72-e6f4-11e5-8fd7-118203a18192.png)

Those are some ideas worth exploring.

**Comment by rachelmcr** [comment]
A back option would be especially helpful after you hit Cmd+N (Mac app) to start a new post. If you have multiple blogs, this opens a site picker and there's no way to go back from there. Full details in this post: https://test.wordpress.com/2016/10/14/session-notes-editor-domain-claim-vscroll-workflow-automation-desktop-app-testflight/
