### ISSUE TITLE
Signup: Email verification prompt doesn't go away after verification

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-desktop#123]
I signed up inside the app (MacOS beta channel) & I saw the prompt at the top of the screen:
<img width="804" alt="screen shot 2016-03-18 at 2 42 01 pm" src="https://cloud.githubusercontent.com/assets/1587282/13888542/4e208164-ed18-11e5-8421-fcc7be25fff2.png">

...so, I opened my email client, & clicked the "Confirm Now" call-to-action button which opened in my default browser. That session worked as expected.

The issue here is: when I returned to the desktop app, the prompt was still present and the only way I can figure out to get it to go away is to quit the app and relaunch.

It would be great if the prompt went away on its own after verifying (via polling, etc.), but at very least, it should go away when I click around after that.

**Comment by jblz** [comment]
Related #47

**Comment by michaeldcain** [comment]
Related: Automattic/wp-calypso#4651
