### ISSUE TITLE
Plugins: Data not loading for Jetpack sites

### ISSUE THREAD

**Issue by jbcul** [Automattic/wp-desktop#126]
On the 5 sites I have linked, I can see pages, posts etc. but since upgrading to 1.3.0 on my MAC 10.10.5, I cannot see the plugins installed on my sites. Wordpress.com desktop says there are none. I can find no way to refresh this.
I'm not sure if it's a bug or if there is a file from an older version that is hanging up the works.  On the older release I was getting constant install helper toolbar message that never went away, even when I said to install and restart.  The app says to visit Github for support so here I am.

**Comment by jasmussen** [comment]
> since upgrading to 1.3.0 on my MAC 10.10.5, I cannot see the plugins installed on my sites. Wordpress.com desktop says there are none. I can find no way to refresh this.

Thanks for the report, I'm able to reproduce. That's annoying. We'll see about fixing this.

**Comment by aheckler** [comment]
2588644-t

**Comment by beaulebens** [comment]
As I mentioned in #142, I can confirm this, and possibly related, I'm also redirected away from Settings for Jetpack sites.

**Comment by mkaz** [comment]
@beaulebens Settings bug reported in #134 and will be fixed in v1.3.1

**Comment by rachelmcr** [comment]
I checked in v1.3.3 and I am able to view the plugins on my self-hosted sites under My Sites > Plugins. @jbcul is this still a problem for you or is it working now?

**Comment by beaulebens** [comment]
I've been able to see my plugins on all sites for a while now. I believe this was indeed fixed a few versions ago. Going to close, but feel free to re-open if it's still a problem.
