### ISSUE TITLE
Copy-Paste Slow in Longer Posts

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#130]
As a post gets longer the copy and pasting of text becomes slower.

This does not occur on normal Calypso in browser.

**Comment by mkaz** [comment]
After testing, it appears the spellchecker is what slows down the copy-paste, particularly with large amount of text. Disabling spellchecker and it works fine.

**Comment by rachelmcr** [comment]
I just ran into this while creating a new post. It didn't take long for the pasting to become noticeably slower — after about 500 words, I noticed that pasting was taking longer than I expected.

Found on Mac OS X 10.11.4, app v. 1.3.0.
