### ISSUE TITLE
Enable offline mode

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/wp-desktop#132]
A user reports that when their internet connection drops out the app loads a blue screen and they lose whatever changes had been made immediately prior. I can reproduce this on my Mac.

Steps:
1. Create a new post and add a few lines.
2. Turn off the wifi.
3. The app loads a blue screen with an error message.
4. Turn the wifi back on and the most recent changes are gone.

**Comment by Nikitaw99** [comment]
This could also be useful to compose posts while offline.

Like, you could write some posts and maybe pages, but then click a `Sync` button when you are back online to sync between local and website.

Also useful when you have composed multiple posts on multiple devices, but then didn't `sync` the posts on a device with the website. Maybe it will even re-order posts depending on what date were they written.

**Comment by alexjgustafson** [comment]
171248-chat

**Comment by Nikitaw99** [comment]
@alexjgustafson Um, stop spamming?

**Comment by alexjgustafson** [comment]
@Nikitaw99 the previous comment is a cross-reference to another support request within Automattic.

**Comment by Nikitaw99** [comment]
@alexjgustafson Oh, ok. Mind telling me what those are?

**Comment by KokkieH** [comment]
Another request in 870026-f

**Comment by kristarella** [comment]
Another request 801835-zen

**Comment by billisalive** [comment]
Does this mean that if the app crashes while I'm editing a post, and I either have the Internet off or my WordPress server has been glitching and not letting the post save remotely (see #420 ), then I lose all my work? Because there's no local "restore" copy? That would be ... frustrating. :(

**Comment by rachelmcr** [comment]
Reopening this as offline support would still be a valuable enhancement to the app.

**Comment by song4Him** [comment]
I would love to have offline support for the desktop app! Having done a lot of traveling, it would be super helpful to be able to write and format my blog posts, save them offline/locally, then hit publish when I can get online again. Having an automatic local backup like this even when I am online would be appreciated, too.

**Comment by jdhitsolutions** [comment]
I would very much like to have an offline mode. I have been using Open Live Writer on Windows because it is often easier and faster to work locally and then publish when ready. An offline mode would also let me compose posts while traveling. I've recently begun using this on Fedora 31 and it inevitably locks up the system. I'm presuming because there was some issue in maintaining connectivity. Being able to work offline would be a big help. This seems like such an obvious feature to me I can't understand why it isn't being pursued.

**Comment by skierliu** [comment]
I think offline mode is **necessary** for a blog client. After all, what we need is not a browser-like client, but an email-like client. I noticed that when I was writing on the client, it auto-saves a draft online once a few seconds, which created a lot of unnecessary copies in my database. It would be better if we can finish writing locally and publish through the client as we wish.

**Comment by song4Him** [comment]
@skierliu, I agree. I've noticed the same problem with multiple unnecessary copies. Please, Wordpress, find a way to enable offline editing and stop all these different versions! Surely if it works on the web to just have one or two versions, it would work on the app as well?

**Comment by belcherj** [comment]
When WordPress.com supports offline the app will as well.
