### ISSUE TITLE
Settings for any individual site redirects to All My Sites → Stats

### ISSUE THREAD

**Issue by amylaneio** [Automattic/wp-desktop#134]
Steps to Reproduce:

1. Open the WordPress app for Mac.
2. Go to My Sites → [Site Name] → Settings.

Instead of seeing my site's settings, I see My Sites → All My Sites → Stats. Tested same steps on WordPress.com in Safari, and was unable to reproduce the problem.

**Comment by jessefriedman** [comment]
I can replicate the problem as well. I also tested it on self-hosted multi-site and single sites, as well as .com sites and the problem exists for all sites I have.

**Comment by amylaneio** [comment]
Looks like it might have actually been a bug in the version of Calypso that was pulled for the last version of the app. @mkaz wasn't able to reproduce on a dev version of the app with a newer version of Calypso.

**Comment by mkaz** [comment]
Yeh, this will be fixed with the v1.3.1 release which we aim to get out this week

**Comment by rachelmcr** [comment]
Closing as this is now resolved. (Tested and confirmed in 1.3.2-alpha for Mac OSX.)
