### ISSUE TITLE
Linux: Change tar.gz download icon

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-desktop#140]
Currently we show the Fedora icon for the .tar.gz download file on Desktop.wordpress.com:
![screenshot_28-03-2016-10 56 03](https://cloud.githubusercontent.com/assets/150348/14085264/ade358f2-f4d3-11e5-95a3-7c95a651bc64.png)
As the tar.gz file works with all distributions of linux (Debian Based, Red Hat based, Arch, Gentoo) we should switch this icon to the Tux (penguin), general archive (folder), or the text Linux. 

Using the Fedora symbol here is a bit misleading. We should use the Fedora symbol if we release a .rpm version on the future.

**Comment by jasmussen** [comment]
Great call. Thanks for the suggestion. Fixed:

![screen shot 2016-04-18 at 13 28 36](https://cloud.githubusercontent.com/assets/1204802/14602731/cd71068c-0569-11e6-860f-a41f562f104b.png)
