### ISSUE TITLE
Plugins: Data not loading for Jetpack sites.

### ISSUE THREAD

**Issue by Back2Front** [Automattic/wp-desktop#142]
Hi there, I've got 32 sites connected via Jetpack with Manage Module on.
Previously was able to view and update plugins via this app.
Now it shows no plugins are active/inactive on any sites.
![screen shot 2016-03-29 at 12 01 18 pm](https://cloud.githubusercontent.com/assets/18129899/14094867/fbc2a276-f5a5-11e5-93cd-8d9b4e7e9c46.png)
I can view/change themes via the app.

Version 1.3.0

Any ideas? Recently migrated a bunch of these sites, but since there are sites on many different servers I'm guessing its an issue with the app?

**Comment by beaulebens** [comment]
I can confirm this as well, with nothing changing on the individual sites. Seems to be app-specific, as I can see them via wordpress.com.com/plugins/{site}.

Perhaps related, I also noticed that if I try to visit the Settings menu item for a Jetpack site, I am immediately redirected to All My Sites > Stats.

**Comment by beaulebens** [comment]
Closing this as a duplicate of #142.
