### ISSUE TITLE
Mac: White icon vanishes when on smaller screen

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-desktop#143]
I have developed a habit of having split screen on my 13" macbook. As a result the app is thinner and it works really well using this. Unfortunately, it's showing an issue with the 'active' state where there is a white icon:

<img width="608" alt="2016-03-29 at 13 23" src="https://cloud.githubusercontent.com/assets/253067/14107706/a360f072-f5b1-11e5-91db-89c535359a1c.png">

**Comment by lancewillett** [comment]
I use WP.com desktop app in a small window, too. :) Love it for Reader, especially.

I can't repeat this with a non-Automattic account. @karmatosed is the only icon going white the Automattic one?

**Comment by lancewillett** [comment]
Here's my Reader view (I use a non-Automattic user account for my personal blog reading, though.)

![screen shot 2016-03-30 at 10 21 24](https://cloud.githubusercontent.com/assets/66797/14151107/36b20550-f661-11e5-8f45-d088b954a58c.png)

**Comment by lancewillett** [comment]
Also: worth checking in a normal browser with wpcalypso — to see if it's specific to the Desktop app or not.

**Comment by lancewillett** [comment]
I'm able to repeat in wpcalypso — so it's probably not Desktop app specific.

<img width="680" alt="screen shot 2016-03-30 at 10 25 40" src="https://cloud.githubusercontent.com/assets/66797/14151237/ceeaa8d6-f661-11e5-8e2d-b35ad2966614.png">

**Comment by lancewillett** [comment]
Moved to https://github.com/Automattic/wp-calypso/issues/4427
