### ISSUE TITLE
Mac: giant emojis when using a smaller screen

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-desktop#145]
If I have a narrower screen I end up with giantmojis to rival Slack's:

<img width="593" alt="2016-03-29 at 21 42" src="https://cloud.githubusercontent.com/assets/253067/14137235/d5a4fbd4-f65e-11e5-8ec2-17a7e2bdc277.png">

**Comment by jasmussen** [comment]
Fixing that here: https://github.com/Automattic/wp-calypso/pull/4414

Thanks, and sorry :)

**Comment by karmatosed** [comment]
No worries, I sort of enjoyed Giantmojis :)

**Comment by jasmussen** [comment]
❤
