### ISSUE TITLE
Mac OS: Images uploaded don't display with proper rotation

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/wp-desktop#147]
Site I'm testing on is ryanmarkel.com (it's hosted on VIP Go as a test site). App version is 1.3.

When uploading images that were taken with my iPhone 6+, the rotation data is not respected when viewing the post within the app:

https://cldup.com/zYSTpCe-aq-3000x3000.png

The Media Library view displays the image with proper rotation:

https://cldup.com/R9QqnXtFTT.png

**Comment by lancewillett** [comment]
Hi @ryanmarkel — could you please confirm this in wpcalypso (normal Mac-n-Chrome, desktop browser)? Chances are it's not specific to desktop app.

**Comment by ryanmarkel** [comment]
Yup - confirmed broken there as well:

https://cloudup.com/cUkxgTm9qax

**Comment by lancewillett** [comment]
Added notes to main issue over in Calypso repo: https://github.com/Automattic/wp-calypso/issues/313
