### ISSUE TITLE
E-mail followers flashing

### ISSUE THREAD

**Issue by andersbateva** [Automattic/wp-desktop#149]
Hello. On 1.3.1 for Windows, when I go People->E-mail followers, the third follower is flashing, and never is shown. Appears that there is a sort of "ghost" follower in here. _As the Ghostbusters will be avaiable only in July, I'm gonna call Auttomatic for now..._

**Comment by jasmussen** [comment]
Hi, thanks for the report.

Does this issue appear only in the desktop app, or can you reproduce it in the web-app on https://wordpress.com also?

**Comment by rachelmcr** [comment]
I'm closing this for now as we have insufficient information to resolve the issue.
