### ISSUE TITLE
lowercase and UPPERCASE dealing wrong with accents

### ISSUE THREAD

**Issue by andersbateva** [Automattic/wp-desktop#151]
Hello. I searched my image library for "ônibus" (bus), and found nothing. But, when serching for "Ônibus", I found my 4 images - one of them I reuploaded after thinking there were no busses images! After I remembered that I had them there (looked my local folder), I retried the search, and replaced the image I uploaded for the better one that was already there.

I believe it's a problem only with accents (^), but I have not tested.

**Comment by lancewillett** [comment]
Hi @andersbateva — could you report this in https://github.com/Automattic/wp-calypso instead? The desktop app is simply a wrapper for our Calypso client for WordPress.com. Thanks!
