### ISSUE TITLE
SSL rejects network requests in some proxy configurations

### ISSUE THREAD

**Issue by beaucollins** [Automattic/wp-desktop#152]
In proxy situations users are unable to use the app due to what is essentially a MITM attack by their network.

`UNABLE_TO_VERIFY_LEAF_SIGNATURE`:

<img width="266" alt="UNABLE_TO_VERIFY_LEAF_SIGNATURE" src="https://cloud.githubusercontent.com/assets/19795/14365806/794b56fa-fcc4-11e5-82b4-7cee178ec28c.png">

**Comment by beaucollins** [comment]
One potential solution is to allow the user to disable SSL failures via a [configuration option][request] for `https.request`.

[request]: https://nodejs.org/dist/latest-v5.x/docs/api/https.html#https_https_request_options_callback

**Comment by lovestulip** [comment]
This issue seems to be coming up over here: 1306205-zen.

**Comment by designsimply** [comment]
Still appears valid. Removing the `[Status] Stale` label and noting this project is currently not under active development and the suggestion is appreciated but may take some time to get to!

**Comment by belcherj** [comment]
I don't think this is an issue any longer.
