### ISSUE TITLE
Auto-updater on Ubuntu Linux?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#156]
Dear all,

Does WP Desktop provide an auto-updater when installed from the `deb` package on Ubuntu Linux?

Thankfully,

~Robert

**Comment by mkaz** [comment]
Hi @orschiro 

No there is not an auto-updater or debian repo that it can update the package from. However, the app will automatically check for the latest version and when a new version is out prompt you to download and install the new version.

**Comment by orschiro** [comment]
Dear Marcus,

  

Thank you for your reply!

  

Prompting to manually download the latest version is completely sufficient.

  

Good to know,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 15 2016, at 12:20 am, Marcus Kazmierczak
&lt;notifications@github.com&gt; wrote:  

> Hi [@orschiro](https://github.com/orschiro)

>

> No there is not an auto-updater or debian repo that it can update the
package from. However, the app will automatically check for the latest version
and when a new version is out prompt you to download and install the new
version.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on
GitHub](https://github.com/Automattic/wp-desktop/issues/156#issuecomment-21017
9453)![](https://github.com/notifications/beacon/AAKbw57o8bWDSOV_noNOL1lJxKIX2
DKAks5p3r2tgaJpZM4IHvtr.gif)
