### ISSUE TITLE
Bug: Quitting the app with editor open confuses the Back button

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-desktop#159]
Steps to Reproduce:

1) Open up a post or page in the editor
2) Quit the application
3) Re-open the application - it should start up on the post/page you were editing.  So far so good.
4) Click Back to return to the post/pages list
5) Open a different post/page
6) Click Back

It should return you to the post/pages list, but instead takes you back to the post you were editing when the application started.

This was tested on v1.3.1 on OSX, Windows, and Linux

![wp-desktop-editor-open-on-quit](https://cloud.githubusercontent.com/assets/7233112/14651402/cb927e5c-063d-11e6-89fa-2742ce31308e.gif)

**Comment by orschiro** [comment]
I can confirm this exact same bug on Ubuntu Linux 15.10.
