### ISSUE TITLE
Keyboard shortcut to insert link?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#161]
Dear all, 

According to the [documentation](https://codex.wordpress.org/Keyboard_Shortcuts), the default shortcut to insert a link is `Ctrl+k`. 

Using this combination, however, does not work for me in Wordpress Desktop on Ubuntu 15.10.

Any advice?

Thankfully,

~Robert

**Comment by lancewillett** [comment]
Thanks for the report.

I think this might be broken in the main WordPress.com website — not just desktop app(s).

Can you confirm by logging into WordPress.com with a web browser and trying it there?

**Comment by lancewillett** [comment]
When in the Calypso (code name for WordPress.com web app) editor — you can see all the shortcuts that it **should** support by going into the toolbar, expanding the second row — and clicking the `?` icon.

<img width="795" alt="screen shot 2016-04-25 at 1 12 54 pm" src="https://cloud.githubusercontent.com/assets/66797/14797390/7826b3f6-0ae7-11e6-8219-b54f0d8e7d2c.png">

**Comment by lancewillett** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/4336

**Comment by orschiro** [comment]
Dear @lancewillett,

You're right, the wordpress.com version is affected as well although the `?` clearly says that `Ctrl+k` should work. 

You already reported it at the correct place?

Thankfully,

~Robert

**Comment by lancewillett** [comment]
Yes, will follow up there. Thanks Robert!
