### ISSUE TITLE
Electron Icon shows up for alert view instead of WordPress icon

### ISSUE THREAD

**Issue by sendhil** [Automattic/wp-desktop#162]
<img width="1364" alt="screen shot 2016-04-25 at 3 35 28 pm" src="https://cloud.githubusercontent.com/assets/437043/14801077/817fe4ea-0afb-11e6-8f5f-0050685f8f69.png">

**Steps to reproduce**

1. Create a new post.
2. Enter some text
3. Hit the back button

**Comment by sendhil** [comment]
I can't really reproduce this. I think it might have been a hiccup with my dev build going to close for now.

**Comment by mkaz** [comment]
Correct, dev builds will show Electron icon. Production builds show WP.

**Comment by sendhil** [comment]
Good to know ;)
