### ISSUE TITLE
Offline Compose & Schedule?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#164]
Dear all, 

One really cool feature would be if it was possible to compose and schedule a post while being offline. 

Is this something that WP Desktop can technically support?

Thankfully,

~Robert

**Comment by mkaz** [comment]
We hope to include more offline support as the app develops - it is an eventual goal.

The main issue can be tracked here: https://github.com/Automattic/wp-desktop/issues/132

**Comment by orschiro** [comment]
I will subscribe to the other conversation. Thanks for providing the reference, @mkaz!
