### ISSUE TITLE
How to compose in Markdown?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#165]
Dear all, 

I enabled the option to compose in Markdown: 

![image](https://cloud.githubusercontent.com/assets/170947/14845414/4f8ac6e4-0c5e-11e6-9dd2-f12cc9f810f2.png)

However, the composing window does not render Markdown code:

![image](https://cloud.githubusercontent.com/assets/170947/14845430/74506704-0c5e-11e6-8454-3a5931df8729.png)

Do you have any advice how I can use Markdown in the composing window properly?

Thankfully,

~Robert

**Comment by mkaz** [comment]
@orschiro to use Markdown, you should edit while in HTML mode and not Visual.

**Comment by orschiro** [comment]
@mkaz, thanks!

Maybe the editor tab could say `HTML/Markdown` if Markdown was enabled in the WP-Admin?

Or maybe even an extra tab next to `Visual`, `HTML` that says `Markdown`?

![image](https://cloud.githubusercontent.com/assets/170947/14876413/0b74ad5a-0d15-11e6-9b01-9ee844f15b94.png)

**Comment by nsakaimbo** [comment]
Thanks for this feature request. Closing as this issue is stale. If there is still interest in this enhancement, please file it to the Calypso repository at https://www.github.com/Automattic/wp-calypso as it is not specific to the Desktop app.
