### ISSUE TITLE
Make Visual and HTML tabs fixed scroll?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#166]
Dear all, 

Would it be possible to make the visual and HTML tabs fixed scroll when scrolling down so that they remain visible? :)

Screencast below:

https://cloudup.com/cgh-6xZBSaE

**Comment by lancewillett** [comment]
Hi orschiro, thanks for this suggestion. I'm going to note it on an existing request over on the open-source WordPress.com app: https://github.com/Automattic/wp-calypso/issues/1001 (it's not specific to desktop apps).

**Comment by orschiro** [comment]
That's great, thank you for forwarding @lancewillett!

~Robert
