### ISSUE TITLE
Preformatted texts do not close </pre> tag

### ISSUE THREAD

**Issue by prrandrade** [Automattic/wp-desktop#169]
Hello everyone! I am using the wp-desktop Windows version, and I realized that when I select a text and change the the font format to preformatted, the close tag (</pre>) is not added. I have to manually edit the HTML version of the text I am posting and type the </pre> tag.

Thanks for the attention and sorry if this is a duplicated post.

**Comment by nsakaimbo** [comment]
Closing as testing on Windows seems to indicate that the `preformatted` tag is working as expected in the Classic/HTML editor. Please feel free to re-open if you encounter this issue again.
