### ISSUE TITLE
Downloading the app in Chrome shows possibly unnecessary warning

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/wp-desktop#171]
When you download the Desktop app on Chrome (latest) on a Mac you're presented with the following warning. 

![screen shot 2016-05-10 at 10 04 17 am](https://cloud.githubusercontent.com/assets/1749986/15155762/f271d354-16b1-11e6-9be6-ab655d2659b9.png)

This kind of warning can be quite frightening to many users and may result in loss of adoption. I'm curious if there is a way to avoid the error and create a better and seemingly safer experience for the user?

**Comment by mkaz** [comment]
According to <a href="http://stackoverflow.com/questions/5553553/why-does-google-chrome-sometimes-warn-that-a-downloaded-pdf-can-harm-your-comput">these comments on Stackoverflow</a> it might be due to a redirect or the way we are doing content-disposition to trigger a download.
