### ISSUE TITLE
Mac: "Origin is not allowed" in login screen

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-desktop#172]
Previous steps that led to this:
- Opened the app as usual, into my regular user
- Logged out via the `/me` screen
- Having been taken to the login screen, followed "Create account" link to try that flow
- Closed the app mid-flow (Themes step)
- Reopened the app, now seeing the login screen. The error notice appears:

<img width="999" alt="desktop-app-origin-not-allowed" src="https://cloud.githubusercontent.com/assets/150562/15177370/840fbc6c-1767-11e6-8640-15bf8992aa63.png">

(1.3.2 release)

**Comment by naquiuddin** [comment]
<img width="1279" alt="wordpress_issue" src="https://cloud.githubusercontent.com/assets/1978381/20037408/ae1cb9fa-a444-11e6-9156-ff01198022ab.png">
I did a fresh clone. After trying to login I got `405` and then I see this error.
````
XMLHttpRequest cannot load https://public-api.wordpress.com/rest/v1.1/me?meta=flags. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:41050' is therefore not allowed access. The response had HTTP status code 405.
````

**Comment by naquiuddin** [comment]
I removed Javascript origins in Developer account's app settings and tried it has changed a little bit . This time looks similar to this issue.

<img width="430" alt="wordpress_com" src="https://cloud.githubusercontent.com/assets/1978381/20037494/088adede-a446-11e6-8222-65cf92cf5884.png">

**Comment by naquiuddin** [comment]
Oops sorry, Please ignore my comments. I missed adding `http://127.0.0.1:41050` in JavaScript Origins. I should RTFM properly.. Lol!

**Comment by naquiuddin** [comment]
Adding these two origins `http://127.0.0.1:41050, https://widgets.wp.com` prevented many other errors. Not sure whether I should create a separate issue for this.
