### ISSUE TITLE
User gravatar still showing after logout, in signup flow

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-desktop#173]
Steps:
- Open app, logged in as usual
- Log out via `/me` screen
- Having been taken to login screen, follow "Create Account" link to proceed to signup flow

<img width="997" alt="desktop-flow-logged-out-avatar" src="https://cloud.githubusercontent.com/assets/150562/15177468/1fc3eafc-1768-11e6-8cca-b5c6396593fa.png">

(1.3.2 release)

**Comment by rachelmcr** [comment]
I just encountered this again while testing 3.6.0-beta1 on OSX; it's still an issue. It also persists after uninstalling and reinstalling the apps.

I tested each of the links in the masterbar (which appears as if you are logged in):
* My Sites, Reader, and the Gravatar all return me to the login screen.
* The editor button opens a list of my sites, and selecting a site returns me to the login screen.
* The notifications panel opens but nothing loads, and the API returns a 403 error.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue, as of version 4.3.0. The signup flow no longer shows the masterbar, and I was able to complete the signup flow without any errors (and confirmed I was logged in to my new account, not the account I had been logged in to previously).
