### ISSUE TITLE
Design for Uninstall

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#174]
I'm creating an uninstall script (on OSX initially) which will remove all transient files. It will be included as a secondary app within the DMG, this will need an icon an anti-W seems not on brand, so maybe just the anti-circle without the W logo.

When double clicking it will show a dialog, current wording is: 
"Confirm uninstalling WordPress.com desktop app" (Yes/No)

If yes, then "Uninstall Complete" (Ok)

If no, then "Nothing done" (Ok)

Also the DMG folder will need an update on where to include the uninstall app.

**Comment by mkaz** [comment]
@jasmussen here's a screenshot just to show a sample from Little Snitch which includes both install / uninstall apps in their dmg. 

<img width="494" alt="screen shot 2016-05-12 at 11 05 33 pm" src="https://cloud.githubusercontent.com/assets/45363/15268868/2273f54e-19a2-11e6-8af2-09fe001111b8.png">

**Comment by folletto** [comment]
> I'm creating an uninstall script (on OSX initially) which will remove all transient files.

What are these files? 

I'm asking because I don't feel our should be the kind of app that requires an uninstall script. Little Snitch requires it since it installs `kext` (kernel extensions) which is an entirely different ballpark. That's also why it's an installer and not just a drag'n'drop app.

**Comment by jasmussen** [comment]
A nice bit of graphic for the uninstall button should be easy to create. 

However, and as Davide alludes to, it hit me that for OS X users, the DMG window is the first the user sees when they mean to install the app. I'm wondering if the presence of an uninstaller app sends mixed signals. When I see one myself, my first thought is "What files are being blasted onto my computer?"

To be clear, I'm not opposed to having an uninstaller, it's just most apps don't, and I'm wondering if we can do without it. Perhaps we can provide the script as a separate download on the support page.

**Comment by drw158** [comment]
I agree with @folletto and @jasmussen. I don't think that an uninstall script in the DMG is a right fit for WordPress.

I've seen a handful of apps include an uninstall script on their website for those that want it. I think putting on up on GitHub would be a very good compromise.

**Comment by mkaz** [comment]
I'm fine for not having an uninstaller, however if a user simply drags and drops the application to the Trash the settings and stored state does not get cleared since it is saved in `~/Library`  If they install again, they will still be logged in, assuming they didn't log out.

This is relatively common for Mac apps, since it doesn't come with a program manager like Windows. For the Windows install we remove the AppData, so an uninstall and reinstall and the user starts with a clean state.

@jasmussen @folletto @drw158

**Comment by folletto** [comment]
> This is relatively common for Mac apps

Yep. That's the assumed default behaviour. 

And in most instances I feel it's also the preferred user behaviour (where the reinstalled app opens again where it was left). ;)

**Comment by jasmussen** [comment]
I tend to agree, and for that reason I think we shouldn't put this in the dmg. However we should write a likely snippet on the apps.wordpress.com support page, on how to uninstall the app, and we can provide the script as a download there.

**Comment by jasmussen** [comment]
I can add some text to the app site, but I'll probably need some good place to store the applescript that I'll be linking — just use cloudup?
