### ISSUE TITLE
"You need to download and install the new version manually"

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#179]
Dear all,

Wordpress keeps prompting me to install the latest version altough it's already being installed.

Can someone confirm this issue?

Thankfully,

~Robert

```
orschiro@x230:~$ dpkg -l | grep wordpress # grep deb package
ii  wordpress.com                                        1.3.3-alpha                                                 amd64        WordPress.com Desktop client
```

![image](https://cloud.githubusercontent.com/assets/170947/15272514/9de4911e-1a7b-11e6-867f-358110c06bc3.png)

**Comment by mjangda** [comment]
@orschiro We pushed out a `1.3.3 release` version, which is newer than the `1.3.3-alpha` version that you have installed. Can you download and install the latest version from here https://apps.wordpress.com/d/linux-deb to see if the prompt goes away?

**Comment by orschiro** [comment]
Dear @mjangda,

Your link prompts me to download the following file:

```
be53a27698a03d2038677aee2d03a9f2  wordpress-com-1-3-3.deb
```

**Comment by orschiro** [comment]
Now it worked. 

Seemed to have been a problem with Ubuntu's Software Center. 

Thanks guys!

~Robert
