### ISSUE TITLE
Reconnect gracefully once connection is re-instantiated

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-desktop#181]
Right now the app does not reconnect once internet connection is re-instantiated after going offline, resulting in a `Code 106` error. Could we run a check for internet connection and try to connect gracefully without manual intervention?

![](https://cloudup.com/ceRPcmsOz19+)

**Comment by jessefriedman** [comment]
I have been experiencing this as well. From strictly a user standpoint, every time my computer sleeps I awake to that sad face error. What is weird to me is that the screen needs to change at all (I'm sure there are tech reasons) but at this point couldn't we just leave whatever view I have up and just attempt to reconnect behind the scenes?
