### ISSUE TITLE
Aggressively pre-caching empty results when internet connection is reinstantiated

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-desktop#182]
A couple issues when using [tripmode](https://www.tripmode.ch/) to test internet outage/reconnection on the osx desktop app: https://cloudup.com/iyfQzpueI-M
- we aren't showing a fallback state or connection error for most screens, so if a user loses connection during app usage, we simply show nothing when they try to fetch data
  ![](https://cloudup.com/cKK3g7TMUb3+)
- when the connection is re-instantiated, we appear to be serving the cached empty results instead of fetching the desired information

**Comment by mkaz** [comment]
@meremagee, can you test and compare this with Calypso on web and wonky internet connections?

It is my understanding that the offline support is being developed (planned) for inclusion from within Calypso which should address this for both web and desktop.
