### ISSUE TITLE
Layout does not adjust for RTL languages

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-desktop#19]
The sidebar does not shift to the right side in the desktop app when a user's interface language (wordpress.com/me/account) is set to an RTL language such as Arabic or Persian. This happens in all sections I looked at, including Stats, Reader, and Me. This works properly on WordPress.com in a browser. 

Tested in WordPress.com 1.0.1 desktop app and Chrome 47 on OS X 10.11.

Chrome:

![screen shot 2015-12-17 at 12 11 42 pm](https://cloud.githubusercontent.com/assets/1900444/11876488/fa721f3a-a4b7-11e5-85f1-f0f28fe95423.png)
 
WordPress.com.app:

![screen shot 2015-12-17 at 12 12 06 pm](https://cloud.githubusercontent.com/assets/1900444/11876496/0378e60e-a4b8-11e5-877d-2dbed997a512.png)

**Comment by mbnoimi** [comment]
+1

**Comment by johngodley** [comment]
Going to close this in favour of https://github.com/Automattic/wp-desktop/issues/8
