### ISSUE TITLE
Desktop App: Does not Sync Any Content

### ISSUE THREAD

**Issue by Jawwads** [Automattic/wp-desktop#200]
Hi, I recently upgraded my blog's security to SSL. After doing that, my local desktop wordpress client is not syncing any of my content. It just goes into an endless loading screen as shown below; 
![image](https://cloud.githubusercontent.com/assets/2739634/16524020/4c9a0078-3f74-11e6-9c4b-4a75b369f577.png)

Could someone please help me out on this? More than happy to provide additional information. 

Update: 
- I have tried re-connect jetpack. The issues still persists. 
- I have re-installed the application. The issue still persists.

**Comment by sendhil** [comment]
Hi @Jawwads - sorry about the issue :\.  Could you check something for me?  Would you mind trying to access your site through a browser at WordPress.com and let me know if you hit the same issue?

**Comment by Jawwads** [comment]
Yes, same issue persists through the wordpress.com site. Looking forward to your help, @sendhil!

![image](https://cloud.githubusercontent.com/assets/2739634/16900430/87047e48-4bf2-11e6-9323-53f0970ce227.png)

**Comment by sendhil** [comment]
@Jawwads - can you send me an email with the website you are trying to access and the account you use to login to WordPress.com? My email address is sendhil AT automattic.com

**Comment by Jawwads** [comment]
@sendhil, I have emailed you more than two weeks ago. Please help me get this sorted out.

**Comment by sendhil** [comment]
@Jawwads what's your email address?

**Comment by Jawwads** [comment]
@sendhil you can reach me at hi{a-t}jawwad.me. I have emailed you so you could search your inbox for my name.

**Comment by rachelmcr** [comment]
I'm closing this issue as it isn't specific to the desktop app.
