### ISSUE TITLE
Add option to allow zooming

### ISSUE THREAD

**Issue by jacklenox** [Automattic/wp-desktop#201]
It would be great if the desktop app allowed you to control the zoom level. The pixel densities between my laptop and desktop display are quite different, so I've set most of my applications to use either a higher zoom or larger text size level when I'm not using the display. (I'm on an Ubuntu variation and the OS-level increments are too large, everything is either massive or tiny.)

The WordPress desktop app is one of the only apps I use that doesn't support this, meaning that when I'm on the laptop I tend to not bother opening it and just use a browser instead.

From a brief root around, it looks as though [Electron provides API-level support for user-defined zoom levels](https://github.com/electron/electron/blob/a6e3eeee2ded24c53d55d8a905399b6072a5c3e1/docs/api/web-frame.md).

**Comment by jacklenox** [comment]
I'm just leaving bump a here to stop `stalebot` from closing this. This continues to be an issue for me (and I'm guessing plenty of others). I really don't think this should be closed as it's a basic accessibility feature. The WordPress.com desktop app continues to be pretty much the only app I use that doesn't allow the user control over the text size. While other apps that we own, like Simplenote, do have this feature.

**Comment by ajaykj** [comment]
Today I had a user asking for this feature in 16126691-hc.

**Comment by nsakaimbo** [comment]
The application now includes Zoom controls - please install v7.0.5 or greater. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
