### ISSUE TITLE
Creating Seperate Pages For Each Blog Entry.

### ISSUE THREAD

**Issue by KevinBrucer1957** [Automattic/wp-desktop#205]
I have 7 months worth of blog entries.  These Blog entries have been signed with a STICKY signature.  Now all my 7 months worth of blog entries are READ on one page.  Making loading my Blog Entries time consuming to down load.  How can I find in Wordpress.com that will help me seperate each blog entry into "ONE" page instead of "ONE" page with (7) months worth of Blog Entries.

**Comment by rachelmcr** [comment]
If all of your blog entries are marked as "sticky," they will always appear on one page on your blog. One solution is to remove the "sticky" marking on your posts — that way only your most recent posts will be loaded on the first page of your blog, and the rest will load as you scroll down to view older posts on the blog.

You can change the "sticky" status of your posts in the editor (where you made the posts sticky), as described on our support page about [Post Visibility: Sticky Posts](https://en.support.wordpress.com/post-visibility/#sticky-posts).

If you'd like more help with your blog, please go to the Help menu in the app and select "How can we help?" or go the [Help page](https://wordpress.com/help) in a web browser. Cheers!
