### ISSUE TITLE
Publishing of post failed on Wordpress App for Macbook

### ISSUE THREAD

**Issue by IWEARVR** [Automattic/wp-desktop#207]
Here is what happens: (1) I migrated the site with jetpack installed; (2) After successfully migrating the site, reactivate jetpack, and then I can't post new post any more. The error "publishing of post failed" started to show up. (3) I deleted the jetpack plugin, and reinstall it. But this error "publishing of post failed" persists.   (3) I deleted the wordpress App for Mac, and reinstall it. But this error "publishing of post failed" persists. 

What should I do?

**Comment by IWEARVR** [comment]
Here is the screenshot.
![publishing-of-post-failed](https://cloud.githubusercontent.com/assets/20469855/16863353/45c2befa-4a84-11e6-84a5-01a289cbf24f.jpg)

**Comment by designsimply** [comment]
> (1) I migrated the site with jetpack installed

Can you tell me more about this step? Was the site using a different URL before? Where did you migrate to/from?

**Comment by IWEARVR** [comment]
The URL is www.xiaomiinsider,
it is the same URL.
We migrated it from a WordPress server on GoDaddy to another one on GoDaddy.

**Comment by rachelmcr** [comment]
Hi there! Sorry for the delay updating this issue. Do you still encounter this issue in the WordPress.com app? If you do, could you check to see if the same issue occurs when you use WordPress.com in a web browser?

If the problem occurs in both places, it isn't something we'll be able to resolve in the desktop app. In that case, it's likely an issue with the Jetpack plugin's communication with your site and can be best resolved by contacting Jetpack support: https://jetpack.com/support/
