### ISSUE TITLE
Bug: blank page "randomly"

### ISSUE THREAD

**Issue by andersbateva** [Automattic/wp-desktop#208]
Hello. When I edit a post, publish, then click to go back to post list, or go back to editing, sometimes the blank page that appears while changing from one to another turns to be definitive. Then I need to close the client and open again.

I'm on Ubuntu 16.04 LTS 64-bit. Installed through Debian package. Version 1.3.4.

**Comment by rachelmcr** [comment]
Thanks for reporting this issue. Do you still see this blank page appear sometimes in the latest version of the app (version 1.6.0)?
