### ISSUE TITLE
Support Calypso keyboard shortcuts other than `n` for Notifications

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-desktop#21]
This is for Windows and Mac (Linux not tested yet).

When in a browser, you can pull up Calypso-wide keyboard shortcuts with the `?` key.

<img width="684" alt="screen shot 2015-12-17 at 13 58 55" src="https://cloud.githubusercontent.com/assets/66797/11881806/547ddfec-a4c6-11e5-94da-fad1b29fe1d4.png">

You can't access the shortcut menu from `?` on Mac or Windows, and it also seems like most of those shortcuts don't work — with the exception of `n` for opening Notifications.

**Comment by johngodley** [comment]
The keyboard shortcuts are enabled with the config feature `keyboard-shortcuts`. This is not enabled on production or inside the desktop app as I believe the feature isn't ready yet.

If you are seeing this in development mode only then we can close this ticket until the feature is ready.

**Comment by Jawwads** [comment]
What is the update on this?
