### ISSUE TITLE
Windows desktop client 1.3.5 open with "You need to set `oauth_client_id` in your config file." error

### ISSUE THREAD

**Issue by VaanPan** [Automattic/wp-desktop#210]
I just installed Windows desktop client 1.3.5 on my machine.
Every time I tried to open this application, it shows me below error message.
![untitled](https://cloud.githubusercontent.com/assets/12791293/17199782/25676c36-54b2-11e6-9f4d-dc6dda0649d4.png)

But I didn't meet the same issue in my Surface laptop.

**Comment by rachelmcr** [comment]
Thanks for the report! Do you encounter the same error message in the latest version of the Windows app?
