### ISSUE TITLE
Desktop app - OS X -  Stats page gets stuck on Insights, can't switch to Days, Weeks, etc

### ISSUE THREAD

**Issue by BehrouzIX** [Automattic/wp-desktop#216]
After updating to version 1.3.6, I can't see my stats on the OS X app.

When I open the app and click on stats, it opens to Insights tab. Then when I click on Days, it goes to Days tab, but comes back to insights in 1 second and then everything in the app - like scrolling -  virtually freezes - actually becomes very very very slow).

**Comment by ashthemighty** [comment]
Another user has written in to WordPress.com with some additional information regarding from an error screen:

![bildschirmfoto 2016-07-31 um 08 16 20](https://cloud.githubusercontent.com/assets/5559951/17298007/0d49ca3c-57bd-11e6-973d-c7e9cf91a0f0.png)

**Comment by supernovia** [comment]
Note here too:
http://en.forums.wordpress.com/topic/wordpress-mac-app-136-bugs

**Comment by sendhil** [comment]
@BehrouzIX is this still an issue for you in the latest version(1.4.0)? If so would you mind trying the beta channel and letting me know if it persists there?

**Comment by rachelmcr** [comment]
I'm closing this issue as we haven't had any recent reports of it persisting in the latest version. Please comment if this is still an issue for you and we can reopen it.
