### ISSUE TITLE
How to install this application on i386 based linux computer

### ISSUE THREAD

**Issue by s1-ranjan** [Automattic/wp-desktop#217]
I am using an i386 based Ubuntu computer I tried to install this application but I failed to do it so can any body can tell me which package or source code can be used to install on a i386 based computer. I hope to listen on this.

**Comment by sendhil** [comment]
@s1-ranjan that's 32 bit if I'm correct? If that's the case like a lot of other apps(http://www.omgubuntu.co.uk/2016/01/google-chrome-linux-32-bit-discontinued) we don't support 32 bit builds. Sorry :\.
