### ISSUE TITLE
Spell check no longer working

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/wp-desktop#220]
Upon upgrading to version 1.4.0 or 1.5.0-beta1, the experimental spell check feature no longer works.  Screenshots of before and after upgrading are below.

Test in version 1.3.3:
<img width="805" alt="screen shot 2016-08-05 at 3 54 35 pm" src="https://cloud.githubusercontent.com/assets/2282189/17449137/713a83f8-5b0d-11e6-8395-88c3da204923.png">

Test in version 1.4.0
<img width="800" alt="screen shot 2016-08-05 at 3 58 50 pm" src="https://cloud.githubusercontent.com/assets/2282189/17449140/76927a40-5b0d-11e6-8d5d-8600475cb6aa.png">

The _Proofread Writing_ icon still works properly.   

Originally reported in 2760600-t

**Comment by lancewillett** [comment]
Confirmed, testing with 2.3.0-beta3.

In addition, if you try to right-click to select a word (in order to see the spelling options, or copy - paste - etc) the app freezes. See #241

**Comment by lancewillett** [comment]
Closing as per fixes noted in #241.
