### ISSUE TITLE
issues with 1.4.0 on osx

### ISSUE THREAD

**Issue by ptica** [Automattic/wp-desktop#221]
after upgrade I've twice seen the 'missing module ../screen' message
the app was usable though
after 2 days and 2 published blog posts I am suddenly unable to use it anymore
as it gets stuck after few seconds after start
after some time being stuck an already rendered page disappears and all I can see is a blank page

have tried uninstalling and installing app + restarting osx several times
but the symptoms endure
(I wonder, how It is, that I am logged in even after the uninstall/reinstall)

please, could you provide a link to previous .dmg?
thank you very much

**Comment by sendhil** [comment]
Hi @ptica - sorry about that. A fix for this is included with the latest beta, here's a [link](https://public-api.wordpress.com/rest/v1.1/desktop/osx/download?version=1.5.0-beta2) to download it.

**Comment by ptica** [comment]
👍
