### ISSUE TITLE
Typo in tar.gz for wordpress desktop app

### ISSUE THREAD

**Issue by WinstonPoh** [Automattic/wp-desktop#222]
Original name: "**wordpress-com-linux-x64-1-4-0-tar.gz**". The "**-tar.gz**" causes problems extracting. Change to "**wordpress-com-linux-x64-1-4-0.tar.gz**" and it will work fine. My setup is Ubuntu 16.04, x64

**Comment by rachelmcr** [comment]
Thanks for reporting this! I am going to close this issue, as it's a duplicate of this older report: https://github.com/Automattic/wp-desktop/issues/139
