### ISSUE TITLE
macbook app opens to blank stats page

### ISSUE THREAD

**Issue by gmosesx** [Automattic/wp-desktop#223]
Wordpress desktop app 1.5.0 on macbook pro mid-2009 running Capitan 10.11.6 on home wifi. App opens to blank stats window. Window navigation from top dropdown is not responsive; won't open "My Sites," "Reader," etc. Trashed app. Reinstalled. Same thing.

**Comment by rachelmcr** [comment]
Thanks for reporting this issue. If you update to version 1.6.0 do you continue to have the same issue?

Also, do you see a blank stats screen and/or unresponsive window if you log in to https://wordpress.com/ in a web browser and open your stats there? That will help us determine if this is an issue specific to the desktop app or not.

(If it's an issue in the browser as well, there's a possibly related Calypso issue here: https://github.com/Automattic/wp-calypso/issues/7406)

**Comment by gmosesx** [comment]
All is good now, thank you! Using 1.8. Life is smooth. Wordpress rocks.
