### ISSUE TITLE
Bug? WordPress desktop (Windows) v1.5.0 doesnt open

### ISSUE THREAD

**Issue by journeynator** [Automattic/wp-desktop#224]
Tried installing v1.5 yesterday on my home pc (Windows 10) and kept getting errors saying that various .dll files are missing (didn't think to screen shot at the time).
In work I've just upgraded to v1.5 (on Windows 7) and now I'm getting a similar error 
![wperror1](https://cloud.githubusercontent.com/assets/21174082/17854971/e2b5f46e-686d-11e6-9c0d-6727e32a2db5.png)
have rolled back to 1.4.0 for now, hope this is the right place to flag it

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/user/status/767681411310583808)

**Comment by ACWMH** [comment]
I'm having the same issue, downloaded the "update" today.  I'm on Widows 10.  

Yes, I've tried reinstalling several times.

**Comment by mkaz** [comment]
This looks like it is related to his bug in Electron, https://github.com/electron/electron/issues/5528
We are working on upgrading to a newer version which will address the issue.

As a work around you can download and install the VC++ library files directly from Microsoft at: 
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Alternatively, you can uninstall 1.5.0 and downgrade and installing the previous 1.4.0 version from
https://public-api.wordpress.com/rest/v1.1/desktop/windows/download?version=1.4.0

**Comment by supernovia** [comment]
Another twitter user [reported](https://twitter.com/user/status/768184916798570496) this on a 64 bit Windows 7 installation too.

**Comment by hlashbrooke** [comment]
I have this same problem on Mac with v1.5 - I got this error immediately after updating and continue to get it whenever I try to open the app:

![Error](https://cldup.com/RpnoHr4oMO.png)

I'm downgrading to v1.4 in the mean time.

**Comment by hlashbrooke** [comment]
Doing a clean re-install of v1.5 fixed this issue, so the problem must have come up in the update process somewhere.

**Comment by lancewillett** [comment]
Another report from @m saying he couldn't upgrade to 1.6 on OS X.

I upgraded to 1.6.0
it didn’t relaunch, and when I tried to launch it, said it wouldn’t open
downloaded fresh from apps
went through install

<img width="601" alt="xn5pchy2d9" src="https://cloud.githubusercontent.com/assets/66797/18285416/20169618-7423-11e6-9766-b42de17750eb.png">

**Comment by sendhil** [comment]
@lancewillett  - I think that issue is more related to https://github.com/Automattic/wp-desktop/issues/213

**Comment by nsakaimbo** [comment]
The application is now on v4.7.0, and was just upgraded to Electron v4.2.9 (forthcoming in v5.0.0) in #757. Code-signing and installation issues seem to have relatively been stable since this issue was first reported. Closing this issue for now and will continue to monitor.
