### ISSUE TITLE
Error processing argument at index 0

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-desktop#225]
A user submitted this error message via email. They report they're using Windows 10.

![12c76e685d4217891095b8d9dd4c7020](https://cloud.githubusercontent.com/assets/8002138/17867045/abcd1bf4-685d-11e6-8b57-5d6d979a3e8b.png)

**Comment by chrisfromthelc** [comment]
Another submitted via a user ticket.

> I uninstalled and reinstalled the Wordpress desktop app. The current version I downloaded from the site. The error occurs when I minimize the application in the tablet mode. The application then stops responding. Use a Windows 10 tablet.

**Comment by lancewillett** [comment]
I'm not sure how actionable this one is — let's close it, but reference it in the future in case it comes up again.
