### ISSUE TITLE
Notifications: Missing styles?

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-desktop#226]
In 1.6.0-beta1 (OSX), I appear to be missing all styles related to the notifications panel. This is what I see:

<img width="402" alt="screen shot 2016-08-25 at 9 25 28 am" src="https://cloud.githubusercontent.com/assets/108942/17975193/00e35a46-6aa6-11e6-86ef-15258e8951cf.png">

**Comment by rachelmcr** [comment]
There's definitely some weirdness in your screenshot, but I haven't reproduced the issue in 1.6.0-beta1 or after updating to 1.7.0-beta1. I wonder if it's something related to the exact notifications you received.

@beaulebens After updating to 1.7.0-beta1 do you still see the same issue? If so, could you open the console (CTRL+SHIFT+i) to check for errors there?

**Comment by beaulebens** [comment]
On 1.7.0-beta1 I'm still seeing it (even after a couple of restarts). Looking in the console, I see this:

`GET https://widgets.wp.com/notifications/build.css?df08925ae3732afc5f881447e8542a38 net::ERR_CONTENT_DECODING_FAILED`

which seems to be related.

**Comment by sendhil** [comment]
@beaulebens would you mind attaching a video? I'm having difficulty reproducing the issue as well.

**Comment by beaulebens** [comment]
There's not really anything to video, TBH. All I'm doing is opening the app and then clicking the Notifications icon, and that's what I see. I think the above `ERR_CONTENT_DECODING_FAILED` error is what's happening, although I've never seen that before.

If I try to load that URL in a browser, it seems to load fine, although [this page](https://stackoverflow.com/questions/14039804/error-330-neterr-content-decoding-failed) seems to claim that this is because of a gzip misconfiguration/lie.

That URL does report `Content-Encoding: gzip`, but appears to be passed as plain text. I don't know why it would only affect me, and not everyone else though?

**Comment by sendhil** [comment]
Ahhh - I thought it was a specific Notification, like @rachelmcr I can't quite repro it.  By chance do you have another computer you could test this out on?

**Comment by beaulebens** [comment]
I'm afraid I don't. FWIW, this has persisted through multiple upgrades now, and is still happening on 1.8.0

**Comment by mtias** [comment]
cc @dmsnell

**Comment by dmsnell** [comment]
@mtias I'm AFK do you mind assigning me on this so I don't miss it later?

**Comment by mtias** [comment]
Sure thing :)

**Comment by dmsnell** [comment]
@beaulebens what about a `build.min.css` - is the error on the sourcemap? we've had problems with the source map.

as to why the styles aren't loading…no clue. this is odd indeed. works fine for me. could there have been an upgrade-related path that could be badgering a cache? is the `build.min.css` file ever loading?

**Comment by beaulebens** [comment]
@dmsnell I can see `build.min.css` if I open inspector, and look under Sources. It has (full, I think) content. Right next to it, I see `build.css`, and it's empty. That's the file that's triggering the `ERR_CONTENT_DECODING_FAILED` error that I see in the console.

Not sure if it's related, but I'm also seeing these at the moment:

`GET https://public-api.wordpress.com/rest/v1.1/pinghub/wpcom/me/newest-note-data 404 ()`

(404s for a notifications-related request).

I have tried deleting the WP.com app and installing a clean version, and the problem persists for me.

I'm now on 1.9.0-beta1

**Comment by beaulebens** [comment]
This seems to have magically fixed itself in some recent version, so I'm closing it for now.
