### ISSUE TITLE
Button to search through all articles and pages?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#228]
Dear all, 

What do you think of a button to easily search through all existing articles and pages to quickly being able to find and edit an article or page?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18120232/dc67e390-6f5e-11e6-805f-64e2109e7be1.png)

**Comment by rachelmcr** [comment]
Thanks for the suggestion! The desktop app is based on the Calypso project, so the best place for enhancement/feature requests like this are directly in that project:

https://github.com/Automattic/wp-calypso/issues

If a feature like this is implemented in Calypso, it will be automatically released in a future version of the app.

You may also be interested in the editor's existing drafts feature: If your site has unpublished drafts, you'll also see a "Drafts" drawer at the top of the sidebar on the left (next to the "Back" button). That's a quick way to find existing drafts so you can edit and publish them.

**Comment by orschiro** [comment]
Thank you @rachelmcr!

I did not know that issues like these should better be reported in wp-calypso.

Should I file a new request there?

Thankfully,

-Robert

**Comment by rachelmcr** [comment]
If the existing drafts feature I mentioned doesn't meet your needs, please feel free to file a new request in the wp-calypso repo. :)

This repo is best for issues or enhancements that are specific to the desktop app, but a feature like this one could benefit both app and web users, so it's best filed directly in wp-calypso.

**Comment by orschiro** [comment]
Done. :-)

https://github.com/Automattic/wp-calypso/issues/7898

Thank you again for your help!

-Robet
