### ISSUE TITLE
2FA: support verify button in the mobile WP apps

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-desktop#23]
Would be neat if we supported the "verify" button in the mobile WP apps (iOS and Android) as an option for 2FA like we already do on the web.

**Comment by lancewillett** [comment]
+1 to this.

Flow:
1. Enter username and password.
2. Instead of prompting for 2FA, send request via WordPress mobile app.
3. Confirm in the mobile app.
4. Boom! Logged in to desktop app.
