### ISSUE TITLE
Code snippet visible in pop-up options menu

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-desktop#231]
In the Mac version of the app the line `rootClassName=>` is visible in the pop-up options menu if one clicks on the ... icon on the Reader and Pages screens:

<img width="264" alt="following_ _reader_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/18226388/afbe21a4-7208-11e6-910d-c780b471601a.png">

<img width="240" alt="pages_ _if_all_else_fails___use_a_hammer_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/18226390/b41eb0f6-7208-11e6-8741-bafb5f72c9d0.png">

I do not see the same in the Windows version of the app.

Behaviour observed in the 1.6.0-beta1 release on Mac OS X v 10.11.6

**Comment by rachelmcr** [comment]
I confirmed that I saw this issue in the 1.6.0-beta1 release on Mac OS X 10.11.6.

I then updated to version 1.7.0-beta1 and confirmed this issue is resolved there. Closing as resolved; please comment/reopen if you still see this issue.

**Comment by KokkieH** [comment]
Thanks. I'm not seeing 1.7.0-beta1 available yet, but once I have it installed I'll double-check.
