### ISSUE TITLE
Image upload progress indicator

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#232]
Dear all, 

It would be fantastic to have an indicator for the image upload progress. 

How am I supposed to know how long the upload is still taking and how many images still need to be processed?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18254698/b7a70b4e-73a0-11e6-9dad-462f7e2533ae.png)

**Comment by lancewillett** [comment]
Hi @orschiro — this could be an improvement for all of WordPress.com in general (not just the desktop app) right? Possibly related: https://github.com/Automattic/wp-calypso/issues/4189

**Comment by orschiro** [comment]
Hi @lancewillett,

Yes, indeed! Do you want me to respond in the linked thread?

-Robert

**Comment by lancewillett** [comment]
Hi Robert, yes please! Let's close this one, I don't think it's specific to desktop app.
