### ISSUE TITLE
Filtered Custom Post Types not displaying

### ISSUE THREAD

**Issue by defries** [Automattic/wp-desktop#233]
I've implemented @jeherve's useful function to [add a Custom Post Type to the Jetpack REST API](https://jeremy.hu/manage-custom-post-types-wordpresscom/), but although the CPT is added to the WordPress.com interface, it is not been added to the Desktop App. I am using the latest version available.

<img alt="wordpress_com" src="https://cloud.githubusercontent.com/assets/411524/18274223/b0cea808-7441-11e6-9c2a-e0670a6f255d.png">

**Comment by rachelmcr** [comment]
Custom Post Types were enabled in Calypso (web) in https://github.com/Automattic/wp-calypso/pull/7384, but they are not yet [enabled in the Desktop app](https://github.com/Automattic/wp-calypso/blob/d7126c47806d39d1b322cc013fad2bcbca7dd753/config/desktop.json).

@aduth Unless there's a reason to hold off on adding CPT to the desktop app, is that something you could help with?

**Comment by aduth** [comment]
This was marked as closed by Automattic/wp-calypso#7876, but will still require a new release of the desktop app for the changes to take effect.

**Comment by rachelmcr** [comment]
Thanks, @aduth! I've made a note to test this out in the next desktop beta release.
