### ISSUE TITLE
NaN error code if the app opens on the My Sites tab

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#237]
#### Steps to reproduce
1. Open the WordPress.com app
2. Open the My Sites tab
3. Quit the app
4. Reopen the app
#### Expected behavior

I expect the app to reopen on the same screen (My Sites) that I was on before.
#### Actual behavior

The app begins to load and I consistently get this error message:

> WordPress.com ran into an error! (code NaN)

![screen shot 2016-09-09 at 10 24 54 am](https://cloud.githubusercontent.com/assets/8658164/18382152/ade62430-7677-11e6-9c1b-7874febd4ca4.png)

(Note that the error screen has a broken image at the top.)

Using the "Try Again" button loads the app successfully, but I end up on the Reader tab.

**Bonus:** If I quit the app while on that error screen, and then reopen it, I get this error screen:

![screen shot 2016-09-09 at 10 17 58 am](https://cloud.githubusercontent.com/assets/8658164/18382051/471b76f6-7677-11e6-9b04-34df6c559974.png)

**Comment by rachelmcr** [comment]
I also ran into the same error with these steps:

1. Opened the WordPress.com app
2. Opened the My Sites tab
3. Selected a self-hosted (Jetpack-connected) site
4. Noticed that the site has updates available (the yellow update icon appeared next to the site title in the sidebar)
5. Clicked the link to update, which opened a browser window with the site's WP Admin
6. In the app, the blue error screen (code NaN) appeared

Unfortunately, now I'm completely unable to open the My Sites tab in the app. Every time I open My Sites it defaults to that self-hosted site and I immediately get that blue error screen. Quitting and restarting the app doesn't not resolve it.

**Comment by sendhil** [comment]
@rachelmcr - I'm trying to reproduce this - once you clicked on the My Sites tab did you click on any particular item?

**Comment by sendhil** [comment]
Ahhh I got it to reproduce, n/m.

**Comment by carinapilar** [comment]
Got an user today with the same problem, but on a different situation. He said when he tries to click on the Themes menu it shows this error. Ticket 2862317

**Comment by tejas-shanthraj** [comment]
Running with the same error. When i try to customize my theme it gives me that error and when i click on try again takes me back to reader profile. Any idea how to get this working?

**Comment by qwqclover** [comment]
the same error.

**Comment by kevinvanryck** [comment]
The same thing is happening to me.

**Comment by ehti** [comment]
This is still an issue. Another report in #232374-hc

**Comment by rachelmcr** [comment]
Another report in #171519-h.

**Comment by ChriZiegler** [comment]
Same error. The "customize theme" page begins to load but then the error appears.

**Comment by gracie** [comment]
Another report in #3124080-t

**Comment by carladoria** [comment]
Also reported in #269497-chat

**Comment by ehti** [comment]
@rachelmcr  - there's no way to get around this once someone ends up on this NaN error?

i.e. can they switch sites again? Or they're stuck and must use the web app?

Also, is anyone looking into this issue to get it fixed? We're receiving reports on a regular basis now. Maybe @sendhil  ?

**Comment by lancewillett** [comment]
Side note: the image on this screen is broken: https://github.com/Automattic/wp-desktop/issues/249

**Comment by lizkarkoski** [comment]
A report of this error in the forums https://en.forums.wordpress.com/topic/whats-this-3?replies=6

**Comment by lizkarkoski** [comment]
Two more reports in this forum thread: https://mc.a8c.com/happiness/tqr/?topic_id=844060&in_queue=1

**Comment by rachelmcr** [comment]
I can no longer reproduce this error in the scenario described in the original report or any of the other scenarios described in the comments. (Tested in macOS 10.13.3, app version 3.2.0.) Closing as resolved.
