### ISSUE TITLE
Posts are not loading - Publish Posts / Draft Posts

### ISSUE THREAD

**Issue by avirupchatterjee** [Automattic/wp-desktop#238]
Unable to see the published posts or Draft posts from left side **'Blog Posts'** 

STEP 1. Open the **Wordpress.com** app in OS X El Capitan 10.11.6 and login
STEP 2. After the successful login click on the **My Site** TAB on the top left corner
STEP 3. Click on **Blog Posts** menu item and published posts are not showing up

Unexpected behaviour. The end user should be able to see the published posts.  Please refer attached screenshot for more detail.

**wordpress.com** app version 1.7.0

Due to this issue I cant even post in my blog, however the wordpress admin dashboard is working as expected. 
<img width="1203" alt="screen shot 2016-09-11 at 6 49 30 pm" src="https://cloud.githubusercontent.com/assets/8520204/18418469/be374960-7864-11e6-9f4e-2e9621fb7ab9.png">

**Comment by avirupchatterjee** [comment]
It is possible that some port is blocking the connection. Please let me know what are the steps I have to follow in order to identify the issue. Thanks!

**Comment by rachelmcr** [comment]
Do you only have trouble with this in the WordPress.com app? Or is it also an issue if you log in to https://wordpress.com/ in a web browser?

If it's also a problem at https://wordpress.com/ in a web browser, there may be an issue with the Jetpack plugin on your site. You can troubleshoot that issue in the [Jetpack debugger](https://jetpack.com/support/debug/) and [contact Jetpack support](https://jetpack.com/contact-support/) for additional help.

**Comment by avirupchatterjee** [comment]
You are absolutely right.

I ma facing the same issue in wordpress.com site also. I guess Jetpack it is then. We can close this issue '**Not a defect**' with the reason as '**Configuration Issue**'.

Thanks.

**Comment by rachelmcr** [comment]
Thanks for letting us know!
