### ISSUE TITLE
Suggestions: word search function + shortcut for switching between visual and HTML editors

### ISSUE THREAD

**Issue by hd86000** [Automattic/wp-desktop#239]
Hello,

Thanks for the desktop app, which I have found to be useful, but to make it even better, could you please add the possibility to search for a word in the current page by pressing ctrl+f? This is important in any app used for word processing.

I would also appreciate a shortcut that can enable me to easily switch between the visual editor and the HTML editor. Currently I have to scroll to the top of the page each time I have to switch.

**Comment by rebeccakpayne** [comment]
The option to search for a word by pressing ctrl+f was requested in 1226658-zd-woothemes.

**Comment by mmtr** [comment]
I got another user requesting the search functionality using the `ctrl`/`cmd` + `F` shortcut in 1448629-zd-woothemes.

**Comment by albnavper** [comment]
I join the petition too.

**Comment by elliotttate** [comment]
Yes, I was really surprised to find a search function was missing. The lack of one is almost enough to never use the app and just use it through Chrome.

**Comment by nsakaimbo** [comment]
Update:

Tracking the `ctrl/cmd + F` feature request as part of #35, but will leave this issue open to track feature request for HTML/Visual editor shortcut.

**Comment by nsakaimbo** [comment]
Closing this issue as the feature request for `CTRL/CMD + F` is being tracked in #35.

Opened a separate issue to track the feature request for a Visual/HTML editor shortcut toggle (#781).

**Comment by nsakaimbo** [comment]
Closing this issue as we are tracking these items in separate issues above.
