### ISSUE TITLE
Linux: Gnome: Icon not always present

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-desktop#24]
The WordPress.com icon is not consistently showing up for me. Running Ubuntu 15.10 with Gnome 3.16. 

You can see the icon is missing in the top system menu bar:

![screenshot from 2015-12-17 15-13-03](https://cloud.githubusercontent.com/assets/260253/11884749/d6f2a142-a4d0-11e5-987f-9c60faaad488.png)

It's also missing in the dock:

![screenshot from 2015-12-17 15-17-52](https://cloud.githubusercontent.com/assets/260253/11884813/627fa3ae-a4d1-11e5-8a87-b99f1160033a.png)

And in the application switcher (alt+tab) but I can't screenshot it.

It does show up as expected in the Gnome search however:

![screenshot from 2015-12-17 15-13-39](https://cloud.githubusercontent.com/assets/260253/11884750/da0c9c16-a4d0-11e5-8f39-da0006c142c5.png)

Other Electron based apps, like Atom show the icon correctly everywhere so it must just be some missing config.

**Comment by andersbateva** [comment]
Indeed, I noticed and came here to report.

**Comment by mkaz** [comment]
Looks like it might be related to: https://github.com/electron/electron/issues/5241
