### ISSUE TITLE
Using wp-desktop with self-hosted wordpress without going through wordpress.com

### ISSUE THREAD

**Issue by arthurlutz** [Automattic/wp-desktop#240]
This application looks awesome and I'd like to use it for a collection of wordpress sites, some of them internal to a private network.

Is it possible (even in dev mode or by recompiling it) to use wp-desktop against those, so without an account on wordpress.com or installing jetpack (which from what I understand enables wordpress.com to access the self-hosted site).

I would be ready to install https://github.com/Automattic/wp-calypso and any other open source component. 

Is http://public-api.wordpress.com/ open source or proprietary ? http://v2.wp-api.org/ seems open source but does it give enough access for wp-desktop to work with ? 

Sorry if this is not the right place to put this feature request or documentation request. Feel free to redirect me. 

Thanks for your awesome products!

**Comment by sendhil** [comment]
Hi @arthurlutz - unfortunately at this time the desktop app only supports sites that are on WordPress.com or connected via Jetpack. Sorry :\.

**Comment by arthurlutz** [comment]
I'm suprised this issue is being closed. I understand that this is not part of your plan, but does closing it mean that you do not welcome contributions going towards this goal ? 

Would it be possible to have some answers about the APIs I mentioned ? 

If http://public-api.wordpress.com/ is proprietary software, is there a public specification for it ?

**Comment by Saburo40** [comment]
I have a account free and other with web master. I need more information fo best application.

**Comment by Saburo40** [comment]
![2_427251324992618570](https://cloud.githubusercontent.com/assets/17522680/19372403/1df7b056-9192-11e6-97c4-cb521c44f1ae.gif)
