### ISSUE TITLE
Preview on private sites brings up error screen

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#242]
Previewing a post on a private site in the desktop app editor brings up an error screen (code NaN):

![screen shot 2016-10-12 at 10 59 35 am](https://cloud.githubusercontent.com/assets/8658164/19306021/93faaf06-906b-11e6-9ddc-829fbd52b688.png)
### Steps to reproduce:
1. Open the desktop app
2. Start a new post on a private site, or open a draft from a private site in the editor
3. Save and preview the post

Result: As soon as the preview starts loading, the error screen appears.

**Comment by ryanboren** [comment]
I can reproduce this with site preview but not post preview.

**Comment by rachelmcr** [comment]
Noting that this is still an issue in version 2.6.0-beta1.

**Comment by rachelmcr** [comment]
I retested on macOS 10.13.3, app version 3.2.0 and I can no longer reproduce this issue with either post preview or site preview.
