### ISSUE TITLE
Windows: Failed to start app

### ISSUE THREAD

**Issue by hadi77ir** [Automattic/wp-desktop#246]
I have installed the app on Windows 8.1 x64 but every time I try to start it, it says there is an instance of app running! (While there is no Electron app running. Even Chrome is not running.)

I have used many Electron-built app together and none of them have thrown this error.
FYI, I have node.js with electron-prebuilt package installed.

I also tried building it on my system but I was unable to get the API keys from developer.wordpress.com web site.

**Comment by sendhil** [comment]
@hadi77ir - could you try rebooting and seeing if it works? If that doesn't work attempt and uninstall/re-install?

**Comment by hadi77ir** [comment]
I have tried rebooting, uninstalling, reinstalling, installing to a path
without spaces, etc. But it didn't work.

Do I have to uninstall my Node.js environment???

2016-11-01 23:59 GMT+03:30 Sendhil Panchadsaram <notifications@github.com>:

**Comment by nsakaimbo** [comment]
Update: Have been testing/using the application on Windows 10 and have not encountered this issue. Closing as this issue doesn't seem to have been reported since it was initially encountered in 3 years ago.
