### ISSUE TITLE
Plans: Desktop apps missing the Personal plan

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-desktop#247]
Navigate to My Sites -> Plans (or create a new site) on the desktop app on any OS and you'll see options to purchase the Premium and Business plans, but not Personal.

<img width="1438" alt="screen shot 2016-11-03 at 12 41 16 pm" src="https://cloud.githubusercontent.com/assets/7233112/19975570/d75d9a52-a1c2-11e6-8bb9-3a8b190a5835.png">

Seen in latest beta (2.0.0-beta1) as well as older versions

**Comment by rachelmcr** [comment]
Confirmed that the Personal plan is still missing in latest beta (2.1.0-beta3).

@rodrigoi You mentioned testing and submitting a PR to enable it. Any updates on that?

**Comment by rodrigoi** [comment]
@rachelmcr I just opened a PR on Calypso 😉
