### ISSUE TITLE
Random crash when setting tray icon (Windows)

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-desktop#248]
I can't get it to reproduce reliably, but I've seen this error several times when launching the Windows app.  The problem is referenced in several Electron issues ([here](https://github.com/electron/electron/issues/7657), [here](https://github.com/electron/electron/issues/1299)), and the answer seems to be that it's a problem if the icon file is inaccessible.  Sure enough, if I remove/rename the file the error occurs...but I have no idea why the file is inaccessible during normal usage.

Those issues do say that you need to specify the full path, but I believe we're already doing that.  And there is another possible workaround given [here](https://github.com/electron/electron/issues/7657#issuecomment-255673246) that supposedly prevents the error from crashing the app at least, but I assume that will leave you without a tray icon.

Seen on a Windows 10 machine running at least 1.9.0 and 2.0.0-beta1, although I think I'd seen it even earlier.

![image](https://cloud.githubusercontent.com/assets/7233112/20017579/a41339f8-a29a-11e6-9311-aa9653e88438.png)

```
TypeError: Error processing argument at index 0, conversion failure from C:\Program Files (x86)\WordPress.com\resources\app\public_desktop\win10-tray-icon.ico
```

**Comment by chrisfromthelc** [comment]
This has also been reported by another user (#2909604-t).

**Comment by chris-budd** [comment]
This has just been reported by another user running version 2.1 (2953663-t).

**Comment by iamgabrielma** [comment]
Reported a case at 2959507-t , user attaches a screenshot with details of the error.

**Comment by yukikatayama** [comment]
Another report by user (#1384728-t)

**Comment by liviopv** [comment]
#2967254-t

Windows 10 64bits

**Comment by nunyvega** [comment]
Another report by user 2968774-t

**Comment by kristarella** [comment]
Another report with screenshot #3026018-t

Windows 10 (10.0.14393) 32bit, Wordpress App (2.2.0) on Microsoft Surface

**Comment by JasonSnow-Mad** [comment]
Reported in 3042109-t, version 2.2.0

> Sometimes it happened after the network drop, when I continue writing or try save draft. But sometimes it went error after my laptop being idle for a while.

**Comment by kevmarsden** [comment]
Also reported in 3073842-t.  Windows 10 and app version 2.2.0.

**Comment by hoverduck** [comment]
Another report here - https://github.com/Automattic/wp-desktop/issues/273 (closed as dupe)

**Comment by alexjgustafson** [comment]
3090592-t
Win 10 app version 2.2.0

**Comment by rachelmcr** [comment]
Also reported in https://github.com/Automattic/wp-desktop/issues/274 (closed as a dupe)

**Comment by rachelmcr** [comment]
Also reported in https://github.com/Automattic/wp-desktop/issues/277 (closed as a dupe)

**Comment by designsimply** [comment]
Also reported in #284 (closed as a dupe).

**Comment by katinthehatsite** [comment]
Another user reported in 750680-zen; 

windows 10 and the app version is 2.9
