### ISSUE TITLE
"Uh Oh!" page has missing image

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-desktop#249]
My wifi stopped working which meant the "Uh Oh!" page was shown in the desktop app.

It looks like the image was missing from this page:

<img width="398" alt="couldnt connect screenshot" src="https://cloud.githubusercontent.com/assets/128826/20101559/865108c0-a590-11e6-9b12-00e7a2c569e8.png">

Version: 2.0.0-beta1 OSX

**Comment by ryanboren** [comment]
Experienced the same.

https://test.wordpress.com/2016/11/10/session-notes-back-buttons-hidden-sites-touch-image-flow-notifications-site-switching-flow-keyboard-flow-media-section-desktop-first/

**Comment by lancewillett** [comment]
I saw it also recently, when traveling and had a proxy settings issue.
