### ISSUE TITLE
RPM packages for Linux

### ISSUE THREAD

**Issue by sudhirkhanger** [Automattic/wp-desktop#25]
Hi,
1. Thanks for the release of Linux packages.
2. You guys are awesome.

It would be really useful if along with `.deb` there were also `.rpm` packages for RPM based distros like RHEL, Fedora, OpenSUSE.

**Comment by DamionGans** [comment]
I would love a rpm package too! Sorry for the bump, but this issue is created first at 18 dec 2015 and not much activity happened yet. ;-)

**Comment by nsakaimbo** [comment]
Thanks for the request - closing this issue as it's quite stale. Only Ubuntu is officially supported at present (and for the foreseeable future), but we certainly welcome you to play around with the [open-source repository](https://github.com/Automattic/wp-calypso/tree/trunk/desktop) to build `rpm` packages for your own purposes.
