### ISSUE TITLE
Can't be opened - Mac OSX (El Capitan)

### ISSUE THREAD

**Issue by blitz999** [Automattic/wp-desktop#252]
I was using the app just fine and it prompted to update. It then showed this ambiguous message. I deleted it and downloaded again from the wordpress.com page and reinstalled - same issue with the latest version.

![screen shot 2016-11-21 at 17 04 51](https://cloud.githubusercontent.com/assets/1020584/20492443/ab8dc0e8-b00c-11e6-94e1-3cbd915882a0.png)

**Comment by rachelmcr** [comment]
Thanks for the report! Have you tried rebooting your computer after reinstalling the app?

Possibly related: https://github.com/Automattic/wp-desktop/issues/213

**Comment by blitz999** [comment]
I deleted and re-downloaded. Works now, thanks!

**Comment by rachelmcr** [comment]
That's great! Thanks for the update. :) I'll close this issue as resolved.
