### ISSUE TITLE
Reader: Single post view missing white background, desktop app only

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#253]
### Expected behavior

I expect single posts in the Reader to match the Calypso web view, e.g. this single post view:

![screen shot 2016-11-22 at 1 32 47 pm](https://cloud.githubusercontent.com/assets/8658164/20525621/2d97dbb8-b0b8-11e6-8bff-b3ad3ae66a1d.png)

### Actual behavior

The single post view in the desktop app is missing the white background on the single post view, leading to a mix of light blue and white backgrounds on different elements:

![screen shot 2016-11-22 at 1 33 30 pm](https://cloud.githubusercontent.com/assets/8658164/20525644/4506b800-b0b8-11e6-8b17-cb2de99f1d6b.png)

This is the post I was viewing in the Reader: https://wordpress.com/read/blogs/53424024/posts/18697

##### Tested on Mac OSX 10.12.1, WP Desktop app version 2.10-beta2

cc @blowery

**Comment by blowery** [comment]
Digging in.

**Comment by blowery** [comment]
Need to pull in https://github.com/Automattic/wp-calypso/pull/9478

@sendhil how do we accomplish something like this? Cherry-pick the PR? Move `calypso` up to a different commit in `master`s line?

**Comment by blowery** [comment]
Looks like the following merges are in between the commit desktop is tracking and 9478:
```
c1ed871 Reader: Pull config check out of ReaderMain (#9478)
9b88210 Jetpack Personal Plan: Fix my-plans redirection and monthly selectors
d68c8b0 Themes: split single-site JSX in DotCom and Jetpack JSXs (#9453)
289a9b6 Update fetchCurrentTheme, with proper naming and tests. (#9419)
edec8ce Domains: Add message for TLDs in maintenance (#9390)
6993682 Plans: Align the info icon
fb8e20a Plans: Mark new plans as primary upgrades
7be20e2 Jetpack Personal Plan: Remove 'popular' ribbon
b9680c2 Personal plan: remove rebase havok
635b7f6 Jetpack: Adds personal plan
1a05cff JPC: Clean redux state after the flow is completed
35ed1ee Signup: Redirect non-wordpress.com sites to http, because they may not be HTTPS ready yet. (#9462)
b4b9efd Cart: Make the cart error notice persistent
c098696 Cart: ES6ify cart-messages-mixin
54250bf Merge pull request #9378 from Automattic/update/plugins-remove-get-selected-site
0944cbb Plugins: Fix site plugins in store when there is no site
c8d7589 Plugins: Modify PluginsList tests to use unconnected component
6789ef9 Plugins: Optimize selectors to directly use getSelectedSite
45e0497 Jetpack Plugins: Fix plugins list tests
4253954 Jetpack Plugins: Remove sitesList.getSelectedSite(), use Redux Jetpack selectors and cleanup PluginsBrowser
5796d5e Jetpack Plugins: Fix controller issues when selected site is not loaded
b9ca9d9 Jetpack Plugins: Remove sitesList.getSelectedSite(), use Redux Jetpack selectors and cleanup SinglePlugin
c9afe35 Jetpack Plugins: Remove sitesList.getSelectedSite(), use Redux Jetpack selectors and cleanup PluginsMain
c11ce90 Jetpack Plugins: Remove sitesList.getSelectedSite() usage and cleanup in PluginsList
f7db663 GuidedTours: target-based blanket exit without `Continue` (#9432)
d46127e Taxonomies: Adding the possibility to delete terms from the taxonomies settings page (#9343)
```

**Comment by sendhil** [comment]
@blowery - I'll cherry pick it into https://github.com/Automattic/wp-calypso/tree/desktop/2.1.0

**Comment by sendhil** [comment]
Closing this as this code is cherry picked in https://github.com/Automattic/wp-desktop/commit/f83d3e71dd2f20e7aedc1789718a66f787bb686d

**Comment by blowery** [comment]
thanks @sendhil !
