### ISSUE TITLE
Desktop App (both Official and Beta latest versions) on Windows 10 Pro does not open My Sites

### ISSUE THREAD

**Issue by kr3t3n** [Automattic/wp-desktop#259]
Hi, 

I've seen other users are experiencing the same problem (saw a thread on the wordpress support forums) so decided to describe the issue:

Before I click on "My Sites": http://imgur.com/wqNlJEj
After I click on "My Sites": http://imgur.com/3ACpKJX

And nothing happens afterwards. I can click on "Reader" and continue using the app as "Reader" but I don't really need it for that...

I hope I was of any use of you guys. 

Good luck!

**Comment by drinky** [comment]
Exact same issue for the Wordpress Desktop App on Windows 10 since most recent wp-desktop update.

**Comment by rachelmcr** [comment]
Thank you for reporting this! We have another issue describing the same problem, so I'm going to close this issue and we'll continue tracking it there: https://github.com/Automattic/wp-desktop/issues/258
