### ISSUE TITLE
Mac Desktop App Freezing on write click in editor

### ISSUE THREAD

**Issue by code4copy** [Automattic/wp-desktop#264]
On mac book, app is freezing when right click on editor, need to restart app.

**Comment by lancewillett** [comment]
Hello, could you please add your OS version and app version? Thank you. Does uninstalling and re-installing the app fix the problem?

**Comment by rachelmcr** [comment]
This is a known issue that we're tracking here: https://github.com/Automattic/wp-desktop/issues/241

I'm going to close this issue since it's a duplicate of the one above. Thanks for reporting it!
