### ISSUE TITLE
Likes unliking by themselves

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-desktop#266]
I experienced a very odd sort of poltergeist like behaviour with likes today. I found they unliked themselves. You can see here:

![selfunliking](https://cloud.githubusercontent.com/assets/253067/22953187/0a2d2c72-f308-11e6-82c8-df2bbdc51550.gif)

I shut down the app and restarted, the behaviour did not continue. However, I did think worth reporting just incase.

**Comment by delputnam** [comment]
A user reported this same issue that happens for him in Safari and in the WP Desktop app on Mac OS. Restarting his machine did not resolve the issue in his case. For reference, here is the ticket: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3068199
