### ISSUE TITLE
Editor: unknown taxonomy sidebar dropdowns appear on a VIP site

### ISSUE THREAD

**Issue by dartiss** [Automattic/wp-desktop#268]
I have a VIP client who is finding on his editor screen a blank label...

![image](https://cloud.githubusercontent.com/assets/14928971/23162249/1ca49ab2-f825-11e6-9a1a-d792a91d35dc.png)

The client explains it best...

> In the Desktop App we see Taxonomies (Category, TV Shows, Sections), and we also see 'Zones' which I'm guessing is from Zoninator plugin and another item just below 'Zones' is blank, with no label (see attached screenshot). We found that the blank one is for Authors (co-authors plugin?) ... can we make sure the Authors label shows up?

I know this is a VIP specific issue but is this something that can be investigated?

Ticket is #62793-z

**Comment by lancewillett** [comment]
Hi @dartiss Can you confirm it's not happening in a web browser with Calypso? If only desktop, could be something fixed within the time since the last desktop release. There have been CPT and taxonomy changes recently.
