### ISSUE TITLE
JPG Thumbnails Not Appearing

### ISSUE THREAD

**Issue by dartiss** [Automattic/wp-desktop#269]
A VIP client has reported that when viewing media it is not showing thumbnails for JPG images, only PNG images. I can't recreate this on my own desktop app, as both image types correctly display.

![image](https://cloud.githubusercontent.com/assets/14928971/23162436/e514a9f6-f825-11e6-9152-eb80412da22a.png)

Ticket is #62793-z

**Comment by lancewillett** [comment]
Hello @dartiss Have you confirmed the behavior in a web browser with Calypso? Desktop app is a wrapper for wordpress.com — so shouldn't differ too much in behavior.

**Comment by dartiss** [comment]
Hi @lancewillett ,

VIP clients don't use Calypso so, unfortunately, I don't have a method of comparison. I'll try and do some more digging and see if there is anything further I can find for you.

**Comment by lancewillett** [comment]
Sounds good. You can use a test VIP site on your own, as well — if needed (ping Andrea Bishop for info).

Closing for now.

**Comment by dartiss** [comment]
No, sorry, I didn't want this closed as the VIP client is chasing this issue.

Okay, I may have found something relevant. All of the images with no thumbnail are JPGs and looking at their WP Admin media library I can see that they have Photon parameters appended on the end of the URL.

Here's one that works - https://cnnespanol2.files.wordpress.com/2017/03/170323185759-cnnee-biclicleta-mas-ligera-del-mercado-full-169.png
Here's one that doesn't - https://cnnespanol2.files.wordpress.com/2017/03/170323191305-cnnee-showbiz-diego-verdaguer-full-169.jpg?quality=90&strip=all

This is standard with VIP sites and was wondering if you could confirm if this is likely to be the cause?

**Comment by lancewillett** [comment]
Can you please test in web with Calypso? I don't think this is a specific bug with the desktop app.

If you want to talk it through happy to direct message in Slack.

**Comment by dartiss** [comment]
Hi Lance,

I've contacted you via Slack but, to confirm, the issue can be reproduced via Calypso. I've also tried another VIP Client site and they have the same issue too.

I believe the Photon parameters on the end of the URLs are the cause.

**Comment by dartiss** [comment]
At Lance's request, I've moved this issue to Calypso - https://github.com/Automattic/wp-calypso/issues/12665
