### ISSUE TITLE
Scrolling in an open post causes the Reader to scroll

### ISSUE THREAD

**Issue by pento** [Automattic/wp-desktop#27]
To reproduce:

* Go to the reader
* Click on a post
* Scroll
* Escape out of the post

The reader scroll position will have changed. The same behaviour doesn't occur in Calypso in Chrome.

**Comment by johngodley** [comment]
Reproduced in this video:

https://cloudup.com/cp1iACtStkv

Note how when I click on the post and scroll down the scroll bar starts off big. When the post gets to the bottom in that readjusts itself to a smaller size. It's at this point that it is scrolling the reader and not the post (if you dont force the scroll beyond the bottom of the post then scrolling it doesn't affect the reader).

@jasmussen could this be a CSS thing? When you open a post from the reader the reader is still in the DOM in the background so it seems like something could be getting messed up with layering. If you don't think it's a CSS thing then I'll try and dig further.

**Comment by jasmussen** [comment]
It's a CSS thing, thanks for the thorough investigation. I'll work on a fix right now.
