### ISSUE TITLE
Windows App not opening

### ISSUE THREAD

**Issue by charliescheer** [Automattic/wp-desktop#274]
When opening the windows app on windows 10 the app crashes every time resulting in this error message appearing 
![wordpress error message](https://cloud.githubusercontent.com/assets/22015538/23583195/0e311aa2-00f2-11e7-90e2-4305be0c4e02.PNG)

Problem began after upgrading to version 2.2.

**Comment by rachelmcr** [comment]
Closing as a duplicate of https://github.com/Automattic/wp-desktop/issues/248
