### ISSUE TITLE
Crashing in Windows 10 with Electron error

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-desktop#277]
This is on behalf of a person using Windows 10 to use the app. They are seeing the following error message when opening the desktop app.

![image](https://cloud.githubusercontent.com/assets/2036909/23912978/dbabc4e2-08b7-11e7-8b15-8d8aa8741cd4.png)

**Comment by rachelmcr** [comment]
Closing as a dupe of https://github.com/Automattic/wp-desktop/issues/248

**Comment by sirbrillig** [comment]
Thanks! Don't know how I didn't find that.
