### ISSUE TITLE
Login screen: weird blue background box around form and footer areas

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-desktop#278]
Raised by the keen-eyed @scruffian 

![bg](https://cloud.githubusercontent.com/assets/66797/24056973/e2a157c4-0b02-11e7-98f2-d620abbe2d36.gif)

Confirmed by @marekhrabe 

> I thought it was some kind of glitch on my computer but I can clearly see the weird background in your screenshot too. There are two shades of blue.

**Comment by abhishekgahlot** [comment]
@lancewillett Looks like this will be fixed soon as per my PR but only after review is accepted :)

**Comment by lancewillett** [comment]
Thanks for your pull request @abhishekgahlot.

I hope that we can all talk about "Shades of Blue" someday soon, as part of Calypso lore. 😸

**Comment by abhishekgahlot** [comment]
@lancewillett This is fixed in new release. Tested by downloading latest release.

**Comment by lancewillett** [comment]
@abhishekgahlot Yay! Could you please upload an "after" screenshot here, for future reference?

**Comment by abhishekgahlot** [comment]
@lancewillett Here you go!
<img width="1680" alt="screen shot 2017-04-24 at 8 55 27 pm" src="https://cloud.githubusercontent.com/assets/1985457/25344682/7b2d59fc-2930-11e7-836b-883efdad90ef.png">

**Comment by abhishekgahlot** [comment]
@lancewillett Can we close this? Looks like its resolved.

**Comment by marekhrabe** [comment]
Let's close it. Thanks! :)

**Comment by abhishekgahlot** [comment]
Unfortunately, somehow shades of blue have returned. I have raised the PR again which should fix the issue, but need to see why it returned again. Will discuss with devs on PR

<img width="1680" alt="screen shot 2017-06-16 at 3 27 32 am" src="https://user-images.githubusercontent.com/1985457/27203557-028bbcc2-5244-11e7-9715-3692659cfa4d.png">
