### ISSUE TITLE
Remove hardcoding of Linux desktop icon

### ISSUE THREAD

**Issue by theel0ja** [Automattic/wp-desktop#279]
The wpcom.desktop file looks like this, but the icon is hardcoded. (can't use icon packs for that icon)
```
[Desktop Entry]
Name=WordPress.com
Comment=WordPress.com Desktop Client
Exec=/usr/share/wpcom/wpcom
Icon=/usr/share/pixmaps/wpcom.png
Type=Application
StartupNotify=true
Categories=Development;
```

**Comment by mkaz** [comment]
What icon were you looking at using? 
Would it solve the issue if switch to `Icon=wpcom` ?

We struggled a bit to get the icon to show properly in the various distributions and different spots that is shows in Linux. Would welcome any suggestions?

**Comment by theel0ja** [comment]
Numix Circle seems to have `Icon=wordpress`, but if the `wordpress.svg` etc. is put to /usr/share/icons/hicolor/scalable/wordpress.svg`, it uses it as fallback.

**Comment by grvrulz** [comment]
I agree with @theel0ja here. Putting the icon into the hicolor icon theme will make sure any FDo compliant desktop uses it properly. An example of an electron app that does this is Keeweb (https://github.com/keeweb/keeweb/blob/master/package/deb/usr/share/applications/keeweb.desktop)

**Comment by nsakaimbo** [comment]
Closing this issue - stale.
