### ISSUE TITLE
Cannot select tags by clicking on list of previously used tags

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-desktop#28]
The update to v 1.2.1 appears to have broken tag selection in the post editor.

Tags cannot be selected by clicking on the list of previously used tabs using a mouse. Clicking on a tag merely causes the drop-down to collapse without adding the tag.

![selecting tags](https://cloud.githubusercontent.com/assets/11873759/11925556/4f309d8e-a7c5-11e5-8ce4-f15deb64ad4b.gif)

Adding tags by typing their names still works, though.

I tested this using the Mac version, but a user in 678123-f also reported this happening in the Windows version.

**Comment by lancewillett** [comment]
@KokkieH Could you please confirm this is working correctly in Calypso in a normal web browser? It doesn't seem like this would be desktop-app specific.

**Comment by KokkieH** [comment]
@lancewillett It works correctly in Calypso in Firefox, but not in Chrome and Safari.

**Comment by lancewillett** [comment]
Cool, let's move it over to https://github.com/Automattic/wp-calypso instead.
