### ISSUE TITLE
WordPress.com ran into an error

### ISSUE THREAD

**Issue by boostmoth** [Automattic/wp-desktop#284]
A user forwarded us this crash report. No other information. See ticket 3141595

![image001](https://cloud.githubusercontent.com/assets/26887976/24638048/748a15b4-189a-11e7-9bea-64111439229f.jpg)

**Comment by spen** [comment]
Seems to relate to #248

**Comment by designsimply** [comment]
Thank you for the report! 

Closing this one as a duplicate of #248.
