### ISSUE TITLE
Windows: check NSIS for dll injection

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-desktop#29]
Make sure we are using a version of NSIS that isn't vulnerable to DLL injection:

http://textslashplain.com/2015/12/18/dll-hijacking-just-wont-die/

**Comment by mkaz** [comment]
Bumped `makensis` in Homebrew up to 2.49 in https://github.com/Homebrew/homebrew/pull/47256

To build with latest installer, 
```
brew update
brew upgrade makensis
```

Deployed Windows v1.2.3 with updated NSIS installer.
