### ISSUE TITLE
Cannot preview drafts

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#290]
Steps to reproduce:

1. Open an existing draft or create a new one.
1. Check to make sure the status indicator at the top says "Saved."
1. Click the "Preview" button.
1. Check to see if the preview shows up as expected.
1. Go to My Site > Blog Posts > Drafts.
1. Click the "Preview" link under any draft.
1. Check to see if the preview shows up as expected.

<strong>Result:</strong> I expected to see a preview of my draft, but I'm getting a 404 error for any draft I try to preview.

<strong>Video:</strong> [33s](https://cloudup.com/ch6h5gQLkyM)

![screen shot 2017-04-17 at mon apr 17 12 35 39 pm](https://cloud.githubusercontent.com/assets/1119271/25099639/662a65b6-236a-11e7-8d68-8c280ec1a261.png)
<sup>Tested with WP Desktop 2.4.0-beta1 using Mac OS X 10.12.4.</sup>

**Comment by lancewillett** [comment]
I can't repeat this — testing with a WordPress.com site, WP desktop app 2.4.0-beta1.

**Comment by designsimply** [comment]
Thanks for the assist! I tried logging out and logging back in and now I can preview drafts as expected on design5279.wordpress.com blog logged in as design5279. I also tested from two other accounts (user552, user476) and was unable to reproduce on those accounts.

Not sure why it was getting stuck before! Closing, but will re-open if it comes up again.
