### ISSUE TITLE
Website pt-br translations are awful

### ISSUE THREAD

**Issue by renatorib** [Automattic/wp-desktop#294]
The brazilian portuguese translations of your [website](https://apps.wordpress.com/desktop) are terrible! It seems that was translated by a computer (google/bing).

These translations are open source? How/where I can help to fix some translations?

**Comment by designsimply** [comment]
Thank you for the offer to help! Many of the translations are done by volunteers.

This is the collection of all of the Brazilian Portuguese translations:
https://translate.wordpress.com/projects/wpcom/pt-br/default/

From there, you can find specific strings to translate if you click "Filter" and search for the term in English with a "Status" of "Any." Here is an example: 
https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=A+desktop+app+that+gives+WordPress+a+permanent+home+in+your+dock&filters%5Buser_login%5D=&filters%5Bstatus%5D=either&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc#

You can find out more about how translate.wordpress.com works at 
https://translate.wordpress.com/faq/

This forum is the best place to ask for help if you need anything else or have additional questions about translations going forward:
https://en.forums.wordpress.com/forum/translations
