### ISSUE TITLE
Better messaging in update prompt

### ISSUE THREAD

**Issue by pmaiorana** [Automattic/wp-desktop#297]
I hadn't opened WordPress for Desktop in a little while, and when I launched it today I was met with this message:

<img width="1226" alt="screen shot 2017-05-09 at 9 22 05 am" src="https://cloud.githubusercontent.com/assets/194155/25854912/ab981986-349f-11e7-9912-5a73e2d09cca.png">

Seems like this dialog could use some additional copy to explain what's going on/encourage users to update -- even something simple like "WordPress v2.4.0 is now available—please update!"

**Comment by lancewillett** [comment]
💯 
Great idea, Paul. CC @rachelmcr @designsimply 

Should that prompt show recent changes like our mobile apps do?

**Comment by designsimply** [comment]
> even something simple like "WordPress v2.4.0 is now available—please update!"

This sounds good to me. Even simpler maybe: "Please update to WordPress v2.4.0"

> Should that prompt show recent changes like our mobile apps do?

I'd love to see a top 4 or 5 things with a link out to more info on a post at https://apps.wordpress.com/blog/ which I just realized is a bit outdated (latest post Aug 26, 2016).

**Comment by astralbodies** [comment]
Sounds like a plan! It's easy enough to add the blurb to the prompt. We'll eventually want to consider cultivating release posts as @designsimply mentioned; and if there are any tent-pole features to call them out. As it stands this mechanism is not localized so everyone will get an English description.

**Comment by astralbodies** [comment]
I've been adding more useful descriptions in the text - @pmaiorana do you think we can close this for now?

**Comment by pmaiorana** [comment]
Sounds good to me -- closing.
