### ISSUE TITLE
Notifications: List doesn't load after returning to app

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-desktop#30]
A few times after I've returned to the app after not using it (It was open and running, just not used in a while), the notifications panel doesn't load any data.

<img width="402" alt="screen shot 2015-12-29 at 9 58 02 am" src="https://cloud.githubusercontent.com/assets/789137/12039166/fa1370ac-ae12-11e5-8bfa-87d077f38d69.png">

**Comment by roundhill** [comment]
Note: Restarting the app fixes the issue.

**Comment by johngodley** [comment]
That is when the notifications iframe isn't authenticated. We use cookies for this, and they are set when the app starts and are set to expire when the session ends. I wonder if it's possible that Electron is expiring the session early, or after a long period of not being used.

@beaucollins thoughts on setting a expiry period or maybe periodically refreshing the session cookies?

**Comment by Art-Chap-Enjoin** [comment]
I have this problem - I click on the "manage your notifications" button and nothing happens. I've tried restarting my laptop, and restarting the app - makes no difference. I'm using a Macbook Pro OS El Cap
