### ISSUE TITLE
Error occurs when inserting images

### ISSUE THREAD

**Issue by bissy** [Automattic/wp-desktop#304]
I use this add-on on my Chrome (ver.58.0.3029.110 (64-bit)) , Mac OS 10.12.5. in Japanese language.
I tried 3 file, named "114906.jpg", "nigaoe-04.png" and "スクリーンショット 2017-06-07 18.04.47.png". and all of them caused an error.
And they were not inserted in wordpress post.
Error dialog message is below.

`{"message":"Cannot call method \"split\" of null.","name":"TypeError","fileName":"Code (WordPress.com for Google Docs)","lineNumber":3388,"stack":"\tat Code (WordPress.com for Google Docs):3388 (hasImageFileExtension)\n\tat Code (WordPress.com for Google Docs):3409 (uploadImage)\n\tat Code (WordPress.com for Google Docs):305 (upload)\n\tat Code (WordPress.com for Google Docs):4095\n\tat Code (WordPress.com for Google Docs):3890 (renderInlineImage)\n\tat Code (WordPress.com for Google Docs):3543 (renderElement)\n\tat Code (WordPress.com for Google Docs):3525 (renderContainer)\n\tat Code (WordPress.com for Google Docs):3656 (renderParagraph)\n\tat Code (WordPress.com for Google Docs):3539 (renderElement)\n\tat Code (WordPress.com for Google Docs):3525 (renderContainer)\n\tat Code (WordPress.com for Google Docs):310 (postToWordPress)\n"}`

Thank you and best regards.

**Comment by designsimply** [comment]
Tested and confirmed.

Moved the issue to the `google-docs-add-on` project as this one is for the WordPress.com Desktop app and not the WordPress.com for Google Docs add-on. Cheers and thanks for the report!

https://github.com/Automattic/google-docs-add-on/issues/80
