### ISSUE TITLE
Export: Opening the export section leads to a blank screen

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#306]
Opening a site's Export section (under Settings) leads to a blank screen:

![screen shot 2017-06-12 at 3 48 50 pm](https://user-images.githubusercontent.com/8658164/27039835-13a7bfa2-4f87-11e7-8245-9647a3cf5d71.png)

Steps to reproduce:

1. Open the desktop app.
2. Open the My Sites section.
3. Go to a site's Settings section.
4. On the General tab, select Export.

Result: The page refreshes, leading to a blank screen.

##### Tested on Mac OSX 10.12.5, WP Desktop app version 2.6.0-beta1

**Comment by seear** [comment]
The export feature is not enabled in desktop for some reason. Testing with it enabled now...
