### ISSUE TITLE
Plans: Plans page doesn't load

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#307]
The Plans page (under My Sites) does not load in the desktop app, although it loads as expected on the web. Instead, the Plans section in the sidebar is highlighted but whatever section you were previously viewing in the app is displayed. This console error also appears:

`build.js:184 Uncaught TypeError: Cannot read property 'getDescription' of undefined`

![screen shot 2017-06-15 at 2 42 12 pm](https://user-images.githubusercontent.com/8658164/27184105-ed05faa4-51d8-11e7-9895-c67728b842c3.png)

##### Tested on Mac OSX 10.12.5, WP Desktop app version 2.6.0-beta1

**Comment by jeremeylduvall** [comment]
For some reason, I can't replicate this. I tested various sites (JP/AT/WP.com) with different plan levels, but the Plans page loads on my side. Here's a screenshot for a sanity check on `2.6.0-beta2 dev`. Perhaps this was fixed from `beta1` to `beta2`? Admittedly, I know very little about the desktop development process here.

<img width="2544" alt="screen shot 2017-06-20 at 9 41 14 am" src="https://user-images.githubusercontent.com/7240478/27342278-f902f812-559c-11e7-8fde-e460b4efbd8d.png">

**Comment by rachelmcr** [comment]
@jeremeylduvall Did you test with an a8c WordPress.com account? I checked with my a8c account and the Plans page loads, but from a test account it doesn't.

**Comment by lancewillett** [comment]
I can repeat with an a8c test account as well: `build.js:184 Uncaught TypeError: Cannot read property 'getDescription' of undefined`

**Comment by jeremeylduvall** [comment]
I tested with a test account this time locally, and I experienced the same thing. It works fine on the local dev build, but it appears broken on the release build enabled through the app. The only console errors appearing locally are from notifications.

![test](https://user-images.githubusercontent.com/7240478/27384926-011623e2-564e-11e7-8172-1703b0d74dc0.gif)

I'm not quite sure why that would be happening on the release build but not dev.

Quick question - how are you accessing the console with the release build? I can only seem to access that when I'm running the dev build locally, not when running the beta through the app.

**Comment by rachelmcr** [comment]
It looks like the console error is coming from this line in the plan features:

https://github.com/Automattic/wp-calypso/blob/c607cca89ddafe31c7819bd094de3698661e9967/client/my-sites/plan-features/index.jsx#L336

@scruffian it looks like you worked on this most recently — could you take a look and see if you recognize what's happening and/or let us know if you think this issue is a blocker for the version 2.6.0 desktop release?

**Comment by scruffian** [comment]
Created a fix here: https://github.com/Automattic/wp-calypso/pull/15429
