### ISSUE TITLE
Calendar layout is incorrect

### ISSUE THREAD

**Issue by Commodoortje** [Automattic/wp-desktop#313]
With status change date, weekdays are incorrect
July 9, 2017 is not a monday its a sunday.
![2017-07-09_09-01-35](https://user-images.githubusercontent.com/17632950/27991924-5bfdef9c-6486-11e7-908d-82fe070041a4.jpg)

**Comment by rachelmcr** [comment]
Thanks for reporting this issue! This isn't specific to the desktop app (it also happens on the web). It's being tracked here: https://github.com/Automattic/wp-calypso/issues/15615
