### ISSUE TITLE
Norton's warning in WP 2.6

### ISSUE THREAD

**Issue by allberry2001** [Automattic/wp-desktop#316]
I keep getting a virus waning from WP desktop app : Filename: wordpress-com-2-6-0-setup.exe
Threat name: WS.Reputation.1Full Path: d:\downloads\wordpress-com-2-6-0-setup.exe

**Comment by rachelmcr** [comment]
Symantec explains that `WP.Reputation.1` isn't a specific class of threat (e.g. a virus); it's a warning for files with a "low reputation score": https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

It looks like we can report the false positive and/or submit the app to Symantec's whitelist to avoid this: https://submit.symantec.com/whitelist/

**Comment by KokkieH** [comment]
Still happening in 2.7.1, via [Twitter](https://twitter.com/kimberley_x_/status/894525596956581888)

**Comment by rachelmcr** [comment]
Symantec whitelisted `wordpress-com-2-7-1-setup.exe` so at least for version 2.7.1 this shouldn't be an issue. I'm going to keep this issue open a bit longer so we can check to see if 2.8.0 is flagged by Symantec or if the whitelisting they've done is also good for future updates.

Internal ref: p1502127333976315-slack-wordpress-desktop

**Comment by nsakaimbo** [comment]
Closing this issue as it is stale. Also - usage of the desktop application on Windows has not surfaced this issue.

The latest build can now be downloaded for all platforms (Windows, Mac, Linux) from the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
