### ISSUE TITLE
Stats: sparkline icon is appears broken with an 403 error

### ISSUE THREAD

**Issue by nickmomrik** [Automattic/wp-desktop#317]
I'm currently using 2.7.0-beta1, though this happened is several of the previous releases as well.

Whenever I'm on a site menu item other than Stats, it looks like maybe some image title text is showing up.

![screen shot 2017-07-13 at 8 47 32 am](https://user-images.githubusercontent.com/684691/28167049-2aa3343c-67a8-11e7-9e41-21b9aa9a4962.png)

When viewing Stats it doesn't show up.

**Comment by lancewillett** [comment]
Thanks for the report @nickmomrik — just to be clear: this isn't happening in Calypso on the web right?

**Comment by lancewillett** [comment]
Any JS errors in your console, or broken image (404, 403) in console?

Note: in the desktop app you can turn on debug with Ctrl-Shift-i to see the console output.

**Comment by nickmomrik** [comment]
> his isn't happening in Calypso on the web right?

Correct. I've only seen it in the Desktop app on 2 computers (1 with proxy and 1 without).

Good call on the console. I didn't know you could do that. This is interesting...

https://nickmomrik.wordpress.com/wp-includes/charts/admin-bar-hours-scale-2x.php?masterbar=1&s=5931239
Failed to load resource: the server responded with a status of 403 ()

If I switch sites the sparkline loads for the other site. I switch back to nick.blog and when it refreshes, the sparkline loads properly.

**Comment by nickmomrik** [comment]
I tried the same thing on my non-proxied computer and switching between sites has the bug for both of them. Both sites are showing a 403 in the console for the sparkline image url.

**Comment by nickmomrik** [comment]
This seems to be fixed in the 2.8 betas.

**Comment by nickmomrik** [comment]
Spoke too soon. It's happening again. :-(

**Comment by designsimply** [comment]
/ht @alisterscott for reporting this in #manual-testing for 3.3.0 beta (p5T066-Dg-p2).

Tested and confirmed using WPDesktop 3.3.0 beta on macOS 10.13.4.

<pre>admin-bar-hours-scale-2x.php 
Failed to load resource: the server responded with a status of 403 ()</pre>

![screen shot 2018-05-14 at mon may 14 4 18 36 pm](https://user-images.githubusercontent.com/1119271/40026630-4e050e6a-5793-11e8-8b8e-7471f62db5f8.png)

**Comment by rachelmcr** [comment]
This came up again in beta testing version 3.7.0-beta1 (internal ref: p5T066-Hz-p2).

![image](https://user-images.githubusercontent.com/8658164/47420993-8eb35e80-d777-11e8-89ca-4489ae40a1be.png)

I confirmed that it's working in 3.7.0-beta1 for me, so it still isn't a consistent issue.

**Comment by nickmomrik** [comment]
This is still happening and is actually worse because it's showing more text now. Here's a screenshot in 4.4.0.
![Screen Shot 2019-10-24 at 8 22 42 AM](https://user-images.githubusercontent.com/684691/67485159-7fd7e400-f637-11e9-9d12-9e0c27f1b0ec.png)

**Comment by designsimply** [comment]
This came up again in 5.0.1 beta testing, with a twist. In my most recent testing of this case, I found that the problem only happens for sessions if you have not viewed Stats already in the same session.

Steps to reproduce:

1. Go to the WPDesktop app and browse to any screen other than Stats.
1. Quit the WPDesktop app and re-open it.
1. Look for the stats sparkline next to "Stats" in the main menu on the left.

**Result:** if you view the app prior to opening the Stats screen, the stats sparkline appears broken with a 403 forbidden error in the main menu on the left.

<img width="1280" alt="Screen Shot 2020-04-07 at Apr 7 4 29 38 PM" src="https://user-images.githubusercontent.com/1119271/78732172-202c7700-78ff-11ea-93d4-3ed5c81a8f99.png">
<p style="clear:both;"><sup>Tested with WPDesktop 5.0.0.1-beta2 on macOS 10.14.6.</sup></p>

**Comment by nsakaimbo** [comment]
Closing as this issue has been fixed.

The latest build of the app can be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
