### ISSUE TITLE
Enhancement: Add captions for multiple uploaded images

### ISSUE THREAD

**Issue by olind** [Automattic/wp-desktop#32]
I upload multiple images to one post or page. I cannot find any way to add captions to them easily.

In the old Dashboard you could select one image, add the caption and then browse to the next image to add caption.

**Comment by johngodley** [comment]
You can add a caption by clicking the edit icon on the uploaded image and then entering in the caption field.

Additionally, when editing the post (visual) you can click on the image and then click on the speech bubble icon to enter a caption directly.

![caption](https://cloud.githubusercontent.com/assets/1277682/12170899/16583118-b53d-11e5-8a10-87955d1efdf1.jpg)

**Comment by olind** [comment]
Thanks!

Will that caption end up on the image in my media library? I think it's a plus if it does. That way I can more easily search for images later.

**Comment by jasmussen** [comment]
If you want to edit image titles and captions and other metadata in the media library, you can access it from the write post page:

![screen shot 2016-01-07 at 14 09 19](https://cloud.githubusercontent.com/assets/1204802/12171250/82aeef18-b548-11e5-896d-0d6fd0e8412d.png)

From there you can select multiple images, then tap the edit button:

![screen shot 2016-01-07 at 14 09 54](https://cloud.githubusercontent.com/assets/1204802/12171253/891cdc52-b548-11e5-9ff8-cfd2a716e2a4.png)

You can now step through each image, add text/captions, then press done, and/or insert the images afterwards.

**Comment by olind** [comment]
Perfect! I didn't realise that I could change multiple items. Works perfekt! Thanks a lot!
