### ISSUE TITLE
Theme system that support midnight writing

### ISSUE THREAD

**Issue by teerasej** [Automattic/wp-desktop#320]
I have been used a lot of apps for writing, and publish to Wordpress. Many times has done in the mid-night. 

I know there's option to turn screen's color to 'yellow' in Windows and MacOS for using in the night. But total white screen still effect writing in the dark.

I want to propose theme setting for desktop version, something similar to custom CSS on the web version. 

The app can bundle with 2 starter theme, day and night. and provide people to custom the theme in some easy way. (I know CSS is not suitable for everyone)

You can reference to [Ulysses' theme page](https://styles.ulyssesapp.com/tagged/Theme)

**Comment by marekhrabe** [comment]
Some work around Calypso themes has started: https://github.com/Automattic/wp-calypso/pull/15731

**Comment by belcherj** [comment]
When WordPress.com supports dark mode desktop will support it.
