### ISSUE TITLE
Reader broken after upgrade to 2.8.0-beta1

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#327]
I upgraded to version 2.8.0-beta1 on Mac OSX 10.12.5 and the Reader was broken (empty):

![screen shot 2017-08-03 at 6 02 43 pm](https://user-images.githubusercontent.com/8658164/28965614-d7ca0e70-7909-11e7-9dcb-58afa9520409.png)

There were several errors in the console:

![screen shot 2017-08-03 at 6 02 51 pm](https://user-images.githubusercontent.com/8658164/28965626-f3edba48-7909-11e7-8f51-68b07dcc7955.png)

The problem persisted even after completely closing and reopening the app. However, logging out of the app and back in to the same account resolved it.

cc @astralbodies @v18 since you were noting some similar errors in the build before release.

**Comment by v18** [comment]
@rachelmcr did you happen to see if any network requests were returning an error responses, like `"error":"authorization_required"`?

Did refreshing the page (command-R) help? That worked for me, in addition to logging out and back in.

**Comment by rachelmcr** [comment]
I didn't check the network requests or try refreshing the page before logging out/in.

To test again, I just tried reinstalling the last stable version, logging in there, and then updating to 2.8.0-beta1 again and it didn't reproduce this bug. However, after that I found reliable steps to reproduce separate from the version update:

1. Open the My Sites section (it opened to my site's stats and I left it there).
2. Close the app.
3. Reopen the app (it opens to the same stats screen it was on before).
4. Open the Reader.

I'm now also seeing this console error, which appeared as soon as I reopened the app (before I could get the console open to record network requests, and before navigating back to the Reader):

`build.js:92 Uncaught AuthorizationRequiredError: You do not have permission to access this resource.`

That as well as the first three console errors I originally reported appear when I open the app. This is the only console error that shows up after that, when I navigate back to the Reader:

`build.js:314 Uncaught (in promise) Error: Reducer "items" returned undefined handling "READER_TEAMS_RECEIVE". To ignore an action, you must explicitly return the previous state.(…)`

As you observed, refreshing the page resolves the problem.

**Comment by v18** [comment]
Your repro steps work for me too, 🎉.

@Tug and @stephanethomas - do you think the authorization errors described here might be related to using WpLogin on desktop in [81b4edf71da826d63d15d2dc447a261c595f532d](https://github.com/Automattic/wp-calypso/pull/16187/commits/81b4edf71da826d63d15d2dc447a261c595f532d), https://github.com/Automattic/wp-calypso/pull/16187?

> `Uncaught (in promise) Error: Reducer "items" returned undefined handling "READER_TEAMS_RECEIVE"`

Looks like this is due to poor error handling of the error response from the API for the request at `https://public-api.wordpress.com/rest/v1.2/read/teams?http_envelope=1`. I'd say this is unrelated to the main problem of authorization errors.

**Comment by Tug** [comment]
Indeed I'd say that error is not handled properly: https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/read/teams/index.js#L18
We still emit the same `READER_TEAMS_RECEIVE` in that case and the reducer does not check for an error.
Now I'm not sure why it's failing in that case...

Concerning WpLogin, would that be possible to hold on the v2.8.0 release for a few days? We recently decided to drop the support for Social Login on the Desktop app and we haven't decided yet if we should revert https://github.com/Automattic/wp-calypso/pull/16187.

**Comment by v18** [comment]
> Concerning WpLogin, would that be possible to hold on the v2.8.0 release for a few days? 

I think it'll be in beta for 2 weeks. cc @astralbodies 

> we haven't decided yet if we should revert Automattic/wp-calypso#16187

Will you be reverting it in Calypso, or only on desktop?

A note on that: @astralbodies if Automattic/wp-calypso#16187 is reverted, then the Gravatar feature will no longer work and I'll need some time to debug + fix it.

**Comment by blowery** [comment]
Fix for the teams reducer in https://github.com/Automattic/wp-calypso/pull/16970

**Comment by v18** [comment]
https://github.com/Automattic/wp-calypso/pull/16994 fixes this issue. You can use these modified steps from @rachelmcr to test:

1. `cd calypso` in the desktop directory, and `git checkout 93a64c6c1028b2ba0e196b65872a21db8128ed5c`
2. `make run`', & open the My Sites section (it opened to my site's stats and I left it there).
3. Close the app.
4. `make run`', & reopen the app (it opens to the same stats screen it was on before).
5. Open the Reader.
6. See everything loading 👍

@astralbodies will this be cherry-picked to 2.8?

**Comment by astralbodies** [comment]
@v18 Cherry-picked into `release/2.8.0` via wp-calypso `release/desktop/2.8.0`

**Comment by rachelmcr** [comment]
Thanks! Confirmed that this issue is resolved in 2.8.0-beta2; closing as resolved.
