### ISSUE TITLE
Enhancement: Right-click support

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-desktop#33]
Having right-click support to copy links (like in the Reader) would be a great addition :)

**Comment by johngodley** [comment]
We need to implement our own context menu and right click handler, which is all possible in Electron. This would also be a good place for an inline copy menu.

For copying links we'd need to be careful not to expose internal app links - just external ones.

**Comment by jasmussen** [comment]
> For copying links we'd need to be careful not to expose internal app links - just external ones.

We use a CSS trick to disable dragging links that refer to `localhost`:

```
a:not([href*="//"]) {
	-webkit-touch-callout: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
	-webkit-user-drag: none;
}
```

Feels like we can probably use something similar to force-hide a context menu for anything but external links.

**Comment by rachelmcr** [comment]
Right-click support would also be useful in the editor, to enhance the spellcheck — e.g. allow right-click to see suggestions or add words to the dictionary. (A user requested this ability for spellcheck.)

**Comment by jasmussen** [comment]
@apeatling has also suggestedthis should be a thing: 

> We don’t have spell check yet, but I can’t even use the Mac OS spellchecker because right click is disabled
works in the browser

If we actually have to implement our own right-click handler for the app, I have a feeling we can't tap into the OS level spellchecker though.

**Comment by Maggew** [comment]
(R) Click would be amazing. Especially if I'm trying to share an image, permalink comment, text selection print and / or google search...

**Comment by Viper007Bond** [comment]
With signup making its way into the app, it's yet another case where having a right-click menu is a pretty big deal. Users pasting in passwords from example from their password manager. They either have to use the keyboard paste combination (which isn't common knowledge for everyone surprisingly) or navigate through the edit menu.

We should probably increase the priority on this issue.

**Comment by mjangda** [comment]
Something we can borrow from: https://www.npmjs.com/package/electron-editor-context-menu

**Comment by drw158** [comment]
This might be of help. Nylas is an open source email client built with React/Electron. They have a native looking spell check (could be native, I don't know):

![screen shot 2016-03-01 at 3 36 14 pm](https://cloud.githubusercontent.com/assets/618551/13442849/cfb6f788-dfc3-11e5-8391-98907dfbe705.png)

https://nylas.com/n1

**Comment by mjangda** [comment]
@drw158 Good find. Looks like it uses the same spellchecker module that we do. Some code references:

Main lib: https://github.com/nylas/N1/blob/0606d9009eae5537abac8ed3198048fe048cd3ba/src/nylas-spellchecker.coffee
UI integration: https://github.com/nylas/N1/blob/3fc6582718277afd7cfa21a10ce6cd61092b3451/internal_packages/composer-spellcheck/lib/spellcheck-composer-extension.es6

**Comment by apeatling** [comment]
:tada:
