### ISSUE TITLE
Make the application available within Microsoft Store

### ISSUE THREAD

**Issue by hajekj** [Automattic/wp-desktop#337]
It would be really nice if the application was available for download directly from Microsoft Store for Windows 10 users. Electron application can be easily packaged and published into the Store. It then allows easier distribution and discoverability.

More information about adding Windows Store support can be found here: https://electron.atom.io/docs/tutorial/windows-store-guide/

**Comment by hajekj** [comment]
Has anyone managed to build this on a Windows machine? I don't have a Mac available to setup the build for Windows Store deployable...

**Comment by nsakaimbo** [comment]
Closing - the application is now available in the Windows Store! 🎉
