### ISSUE TITLE
Markdown only support?

### ISSUE THREAD

**Issue by corysimmons** [Automattic/wp-desktop#34]

**Comment by johngodley** [comment]
Can you provide some more details about this and how it relates to the WP desktop app? Do you mean removing the visual editor and just going pure text Markdown?

If it's something that should be in the WordPress.com front-end in general then the best place to request the feature is here:

https://github.com/Automattic/wp-calypso

**Comment by corysimmons** [comment]
Yeah I meant disabling the GUI editor completely in favor of markdown-only. Will post this where you suggested.
