### ISSUE TITLE
Error en aplicación de escritorio

### ISSUE THREAD

**Issue by Nuestraaventuradino** [Automattic/wp-desktop#340]
hola,

Hace varios días instalé una actualización de wordpress que apareció al iniciar la aplicación. Desde entonces cada vez que abro la aplicación aparece el siguiente error: https://nuestraaventuradinosaurica.files.wordpress.com/2017/10/captura-error-wordpress.jpg

Me gustaría, por favor, recibir información de cómo subsanar dicho error y que la aplicación pueda funcionar correctamente. El sistema operativo del pc es Windows 10 Home Version 1703.

Muchas gracias, un saludo.

**Comment by rachelmcr** [comment]
Thanks for the report! We are tracking this issue here: https://github.com/Automattic/wp-desktop/issues/339
