### ISSUE TITLE
GUI not displayed in win10

### ISSUE THREAD

**Issue by bytefly** [Automattic/wp-desktop#341]
The app GUI runs and displays ok after installing, but when I finished adding my own blog host, the GUI cannot display and the icon freezed in taskbar even if I restart my laptop. 
By the way, My app version is 2.9.

**Comment by nsakaimbo** [comment]
@bytefly Are you still experiencing this issue? Have you tried more recent versions of the application (v4.7.0 or v.5.0.0-beta2)?

> when I finished adding my own blog host

Just to clarify - are you referring to using the application with a self-hosted site?

**Comment by nsakaimbo** [comment]
Closing as there has been no follow-up from the user.

We also expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
