### ISSUE TITLE
Display bug w/ "Yesterday" and other headers in notifications in small windows

### ISSUE THREAD

**Issue by stephdau** [Automattic/wp-desktop#345]
The "Yesterday" and "Older than 2 days" headers in the notifications view is overlapping some of the item, obstructing them from view, when the app's window is reduced to a certain width.

<img width="349" alt="screen shot 2017-10-19 at 10 22 19 am" src="https://user-images.githubusercontent.com/1891/31775798-986dcc14-b4b7-11e7-94f0-1f73ef6d9b79.png">
<img width="350" alt="screen shot 2017-10-19 at 10 22 37 am" src="https://user-images.githubusercontent.com/1891/31775799-987c6828-b4b7-11e7-9417-591faafc653c.png">
<img width="751" alt="screen shot 2017-10-19 at 10 23 00 am" src="https://user-images.githubusercontent.com/1891/31775800-988a9826-b4b7-11e7-994d-55371f3757c7.png">
<img width="752" alt="screen shot 2017-10-19 at 10 23 15 am" src="https://user-images.githubusercontent.com/1891/31775801-989977f6-b4b7-11e7-86b6-d64e33134fda.png">

Running v2.9.0, on SOX, display issue exist wether I select the `stable` or `beta` mode.

**Comment by lancewillett** [comment]
A quick note: it’s rare for display issues to be desktop-only — usually this is a Calypso bug in any browser. If that’s the case here, we should move this to the appropriate repo (there’s also a notifications-client repo for specific notifs bugs).

**Comment by stephdau** [comment]
Acknowledged, thanks.

**Comment by hoverduck** [comment]
@stephdau - I can't reproduce this (in either the desktop app or Calypso web)...is it still happening for you?  Does it happen every time you open the notifications display, or just sometimes?

**Comment by designsimply** [comment]
I tested opening notifications using WPDesktop 3.1.0-beta2 on Mac OS X 10.12.6 and resizing to various browser width and the "Older than 2 days" (and similar) headings/separators in the notifications panel are always stuck to the top in my testing.

![screen shot 2017-11-15 at wed nov 15 2 16 01 pm](https://user-images.githubusercontent.com/1119271/32860700-a5d76bd6-ca0f-11e7-88ed-93b98078bcf6.png)
