### ISSUE TITLE
Store Stats Inaccessible 

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-desktop#351]
Store Stats results in "Page not found". The code powering the page lies in the <code>/client/extensions</code> folder, perhaps there is a config missing? Or maybe a flag?I poked around a bit and could not find anything apparent.

To reproduce: 
1. Choose a site with Jetpack and WooCommerce plugins installed.
2. See an extra tab in Stats section called "Store".

<img width="223" alt="screen shot 2017-11-06 at 11 08 22 am" src="https://user-images.githubusercontent.com/1922453/32419678-eaf812c6-c2e2-11e7-9f71-f6ad463d22fb.png">

3.Click Store

<img width="780" alt="screen shot 2017-11-06 at 11 08 34 am" src="https://user-images.githubusercontent.com/1922453/32419680-f1bc9b5e-c2e2-11e7-9438-6bdf0c52dc1d.png">

cc @astralbodies @samouri

**Comment by rachelmcr** [comment]
Noting that this should be resolved with a release of the desktop app that includes https://github.com/Automattic/wp-calypso/pull/19692. I'll leave this issue open until then so we can confirm the fix.
