### ISSUE TITLE
2FA text fails to send

### ISSUE THREAD

**Issue by tryptc** [Automattic/wp-desktop#358]
When logging into the app, it fails to send a verification text to my phone. I was forced to go to use my internet browser to WordPress.com/me/security and request a new code. The code worked to log in.

**Comment by rachelmcr** [comment]
I tested this with WPDesktop 3.1.0-beta3 on Mac OS 10.12.6, and I can't reproduce the issue.

I tested with a WordPress.com account that uses SMS as the primary 2FA method, and the SMS was sent after I entered my account credentials in the app, as expected. I was able to log in with the SMS code.

I also tested with a WordPress.com account that uses an authenticator app as the primary 2FA method. After entering my account credentials and selecting "Send code via text message" in the app, I received an SMS with a 2FA code and was able to finish logging in with that code.

Closing this as I can't reproduce the issue in the latest beta.
