### ISSUE TITLE
Mac OS X App locked up and unresponsive

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-desktop#36]
I ran into a case where the Mac app became unresponsive. I'm on OS X 10.10.5 (14F1509), and have version 1.2.1 of the WP.com app.

https://cloudup.com/c5-SPCC07Mg

Order of operations:
- I was editing a post and about to publish (had recently opened the preview)
- Noticed that Facebook and Google+ publicize were not connected.
- I tried to reconnect Facebook, and it failed (invalid nonce)
- I opened wordpress.com in a browser and went to sharing and reconnected Facebook and Google+
- Went back in the desktop app and was trying to clear/refresh the sharing. Tried to go back to all blog posts, and i think clicked somewhere else too
- The UI completely froze in that screen shot.

None of the UI elements in the main page area are responsive, the two gray areas are flashing like they are trying to load something. I can still scroll the page. The site selector works, but selecting other sites or other paths (eg /posts or /pages) does not work.

After quiting the app and restarting everything is working again. Google+ still claims to not be connected. But oh well, it is Google+ :)

**Comment by johngodley** [comment]
I suspect the spell checker may be responsible for the lockup, although this is just based on reports of it using a lot of CPU.

The sharing sounds like a different problem. The way it currently works is not ideal for the desktop app, and hopefully it will be more of an inline experience in the future. Are you able to connect/disconnect anything at all?

If you can somehow replicate even a part of the problem then CTRL+SHIFT+i enables the dev tools where you might see some errors.

**Comment by mkaz** [comment]
Not reported in awhile, with #138 we default disable spellcheck for unrelated performance reasons with a preference to enable
