### ISSUE TITLE
Can't log out of the app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#360]
It's no longer possible to log out of the app.

### Steps to reproduce

1. Open the app (and log in if not already logged in).
2. Click your Gravatar to open the Me section.
3. In the sidebar, click the `Sign Out` button.

Result: The URL http://127.0.0.1:41050/oauth-login opens in a browser and redirects to http://127.0.0.1:41050/desktop/hey.html. You remain logged in to the app. Restarting the app has no effect.

##### Tested on Mac OS 10.12.6, WPDesktop 3.1.0-beta2

**Comment by designsimply** [comment]
Props Tehila for the original report 10:56 am on November 10, 2017! [internal ref: p5T066-xP-p2]

**Comment by designsimply** [comment]
Tested and confirmed using the steps provides and WPDesktop 3.1.0-beta2 on Mac OS X 10.12.6.

**Comment by rachelmcr** [comment]
I tested this with WPDesktop 3.1.0-beta3 on Mac OS x 10.12.6, and I can now log out as expected. Closing this as resolved; please reopen if it's still an issue.
