### ISSUE TITLE
Settings: Jetpack connection settings don't load/API returns a 400 error

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#365]
### Expected behavior

I expect the Jetpack connection settings (located at https://wordpress.com/settings/manage-connection in a browser) to load in the app.

### Actual behavior

The "Site Ownership" section never loads, and the console shows a 400 error returned from this request:

`https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/{SITEID}/rest-api/`

![screenshot 2017-11-13 17 25 58](https://user-images.githubusercontent.com/8658164/32739640-66a5d5c4-c898-11e7-8bff-face5931007b.png)

### Steps to reproduce

1. Open the app and log in to an account with a Jetpack-linked site.
2. Go to My Sites and select a Jetpack site.
3. Open the Settings section.
4. Select "Manage your connection" (at the bottom of the page).

Result: The request noted above returns a 400 error and the page doesn't finish loading. In Calypso in a browser, the request is successful and the page loads for the same site.

##### Tested on Mac OS 10.12.6, WPDesktop 3.1.0-beta2

**Comment by designsimply** [comment]
I checked Settings > General with WPDesktop 3.1.0 for alittletestblog.com running WordPress 5.0-alpha-42251 and Jetpack 5.6-beta-16479-7844644-master and I was unable to find the "Manage your connection" link. I made sure Jetpack is connected. Am I looking in the right place?
 Is there something else I need to do before I should be able to see it? 

<img width="1280" alt="screen shot 2017-11-29 at wed nov 29 9 28 29 am" src="https://user-images.githubusercontent.com/1119271/33386981-686ad140-d4e9-11e7-8581-58b5d058917b.png">

**Comment by rachelmcr** [comment]
You're seeing WordPress.com site settings, which makes me think something else is borked for that site (and that `Uncaught TypeError` looks fishy). Do you see the same thing in a browser or that settings screen only visible in the app?

Do you get the same results for other Jetpack sites (e.g. a Jetpack site with a domain that was never used with a WordPress.com site)?

**Comment by rachelmcr** [comment]
Noting that this still happens in version 3.2.0 but there's a change on the Calypso side that might help when it lands in the app: https://github.com/Automattic/wp-calypso/issues/22720
