### ISSUE TITLE
publish release notes

### ISSUE THREAD

**Issue by Uli-Armbruster** [Automattic/wp-desktop#367]
I would appreciate if you could publish release notes. The releases are the right place for that:
https://github.com/Automattic/wp-desktop/releases

Automapper is a good example
https://github.com/AutoMapper/AutoMapper/releases

**Comment by rachelmcr** [comment]
Thanks for the suggestion! We are working on release notes and hope to start including them with the upcoming 3.1.0 release. :) cc @astralbodies
