### ISSUE TITLE
Do not convert posts/drafts from Markdown to HTML

### ISSUE THREAD

**Issue by habi** [Automattic/wp-desktop#37]
I'm writing all my blog posts in Markdown and rely on the awesome JetPack plugin to do it's thing with the posts afterwards.
When I prepare my posts with the [desktop app](http://desktop.wordpress.com/) (Version 1.2.1 on OS X 10.11.2 (15C50)) the posts get converted from Markdown to HTML when publishing them.
I'd rather not have that, since it also does not happen when I do it in the admin interface of my (self-hosted) blog, which makes after-publishing-editing much more convenient in my view.

**Comment by johngodley** [comment]
Hi @habi can I get you to re-post this here?

https://github.com/Automattic/wp-calypso/issues/new

That repo is the core of the desktop app. Thanks!

**Comment by habi** [comment]
Sure, just did that.
I just thought here's the correct place, since that repository is linked from https://desktop.wordpress.com :)
