### ISSUE TITLE
OSX Bug: Blank Revision Saved on Load

### ISSUE THREAD

**Issue by clickysteve** [Automattic/wp-desktop#380]
I have had a few instances recently where upon loading the app, a post I have been working on is totally blank. The only way to restore it back to what it was before is to go into wp-admin and use the Revisions tool.

An example is here: https://allmyfriendsarejpegs.wordpress.com/wp-admin/revision.php?revision=13416015155

<img width="1261" alt="screen shot 2017-12-10 at 11 14 06" src="https://user-images.githubusercontent.com/6227598/33804377-485f3d04-dd9b-11e7-8119-6d9ef1b7e223.png">

This seems to happen when editing a post, then shutting down the app, and re-opening it. It doesn't happen all of the time.

**Comment by rachelmcr** [comment]
Hm, this is a tricky one as it can't be consistently reproduced; I haven't been able to reproduce it yet. It also sounds similar to an issue that has been reported by non-desktop users, where the post content disappeared but was available in a previous revision (internal ref: p2EDhh-dN-p2).

**Comment by clickysteve** [comment]
Just noting that I just lost an entire draft post from today:

https://allmyfriendsarejpegs.wordpress.com/wp-admin/post.php?post=13416016645&action=edit

With no revisions available.

The app said that the post had been saved, but in actual fact it apparently hadn't. I wonder if it's something that happens when there are a number of images uploaded to a post, and the app can't keep up. 

Either way it makes the desktop app pretty unreliable as is sadly :/
