### ISSUE TITLE
OSX Bug: Drafts Button Count

### ISSUE THREAD

**Issue by clickysteve** [Automattic/wp-desktop#381]
**Issue:** When in a post, clicking on the number of draft posts next to the 'Write' button does nothing. If you then click on the 'Back' arrow to get back to the list of sites, nothing happens. If you click again on the back button, the right hand side sidebar pops out. If you try to close it, it moves around the screen.

**Reproducible?** Yes.

<img width="1438" alt="screen shot 2017-12-10 at 11 18 15" src="https://user-images.githubusercontent.com/6227598/33804403-da1aacc4-dd9b-11e7-9719-b54e8d29f447.png">

**Video demo of the bug:** 

[wpdesktopbug.zip](https://github.com/Automattic/wp-desktop/files/1545568/wpdesktopbug.zip)

**Comment by rachelmcr** [comment]
I tested but was unable to reproduce this on Mac OS 10.12.6, WPDesktop version 3.1.0.

What OS/app versions are you seeing this in?

**Comment by clickysteve** [comment]
WPDesktop 3.1.0
OSX: 10.12.2
