### ISSUE TITLE
OSX: Image Upload Progress Indicator

### ISSUE THREAD

**Issue by clickysteve** [Automattic/wp-desktop#382]
On a slow connection, it can appear like images have been uploaded to a post when they in fact have not, meaning that when you go back to look at the post later, there are blank spaces where you would expect the images to be.

An upload progress indicator, or some kind of notification to distinguish when images are just in the app as a placeholder, versus uploaded and included in the post would avoid this confusion.

**Comment by rachelmcr** [comment]
Does this only happen in the desktop app, or also in Calypso in a browser?

**Comment by clickysteve** [comment]
Appears to happen in Calypso as well.

**Comment by nsakaimbo** [comment]
Closing as this issue is specific to Calypso, and not necessarily the desktop application.
