### ISSUE TITLE
Cannot switch accounts

### ISSUE THREAD

**Issue by lordofscripts** [Automattic/wp-desktop#385]
I tried the procedure for setting up a new account on the Windows desktop app but that does not work. It can only remember the credentials of ONE blog at a time, so everytime I have to remember the passwords. I have two, one for a technical blog account and another for my personal (creative writing).

Would be nice if one could switch back and forth easily without having to go to the app where I keep my credential information as I am not good at remembering passwords.

**Comment by designsimply** [comment]
@lordofscripts thank you for the feedback! I feel this is a problem for the WordPress.com service as a whole and not just for the WordPress.com for Desktop app. Do you agree?

**Comment by rachelmcr** [comment]
Closing since this request is a duplicate of https://github.com/Automattic/wp-desktop/issues/289.
