### ISSUE TITLE
Wordpress Error code 105 on Desktop app

### ISSUE THREAD

**Issue by lordofscripts** [Automattic/wp-desktop#387]
See https://github.com/Automattic/wp-desktop/issues/334 I decided to repost it because the other one has been NEGLECTED, nobody has been assigned to it and it still marked as a Question when it is actually a BUG.

**Comment by designsimply** [comment]
I would like to close this issue in favor of keeping the other one open because it has more information. I have adjusted the labels for https://github.com/Automattic/wp-desktop/issues/334.
