### ISSUE TITLE
OSX Bug - Can't open desktop app

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-desktop#388]
**User reported issue:** desktop app crashes every time I launch it. I uninstalled the app and installed the newest one, the same error pops up.

**Operating System:** MacOS 10.13.2
**WordPress application version:** 3.1.0

```
Error: self signed certificate in certificate chain
at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:603:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
System info: {"platform":"darwin","release":"17.3.0","version":"3.1.0","build":"release"}
```
**Can it be replicated?** Unsure, I don't have a Mac yet so I'm not able to test.

Ticket: 848626-zen

**Comment by designsimply** [comment]
@xpurichan, thank you for reporting this! I like the way you handled the latest response at 848626-zen.

Sounds similar to https://github.com/Automattic/wp-desktop/issues/334.

The error mentioned sounds like a problem with proxy settings to me. The following `npm` issue shows a similar error and has a workaround which may be worth trying: https://github.com/npm/npm/issues/7519#issuecomment-295762964. Here is another similar issue and solution: https://github.com/Microsoft/vscode-cpptools/issues/744.

**Comment by xpurichan** [comment]
Thanks! I sent both of these solutions to them, waiting for a response. They did just provide us with a key though, it looks like the issue may have started _after_ they installed and setup OpenDNS. Working to whitelist now and waiting for results:
https://support.opendns.com/hc/en-us/articles/227988067-Getting-Started-Blocking-Allowing-Specific-Domains-with-Whitelist-Blacklist

**Comment by xpurichan** [comment]
@designsimply hey there! Hope you had a happy holiday!

I realize that I told the user how to use the modifier _"http.proxyStrictSSL": false_ (from: https://github.com/Microsoft/vscode-cpptools/issues/744) completely wrong (told them to chuck it into the terminal). Seems they need to manually edit the .json file but I can't seem to find that for the WP app. Can you provide some direction?

In other news they're back to working on the Open DNS issue and that alone may resolve the problem but I wanted to touch base with you incase it doesn't and we need to move forward.

**Comment by simison** [comment]
Another customer reported an identical issue via 880589-zen.

I asked if they could test using another internet connection as I suspect this is due connection intercepting traffic and breaking the SSL chain during authentication (happens sometimes in corporate networks, at hotels, airports, cafes, universities/colleges and other public institutions).

Operating System: MacOS 10.12.6
WordPress application version: 3.1.0

@xpurichan 's ticket suggests this error would occur only in initial launch but not during normal communication with the API.

**Comment by simison** [comment]
More similar ones: 
https://github.com/Automattic/wp-desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+ssl

**Comment by designsimply** [comment]
@xpurichan, my apologies, `"http.proxyStrictSSL": false` is a VSCode configuration value—it is relevant because it shows the problem is likely proxy-related. 

Whitelisting WordPress.com in OpenDNS, as you have already suggested, is a good next step to try. It may also be worth checking if any other proxy is running and if it can be temporarily turned off to see if that allows the app to launch without the Error: self signed certificate in certificate chain" error.

It is also noteworthy that the reporter mentioned being able to open WPDesktop when connected to a different wifi (Xfinity hot spot).
