### ISSUE TITLE
OSX: Define menu keeps popping up.

### ISSUE THREAD

**Issue by BlameDutchie** [Automattic/wp-desktop#390]
The Define/cut/Copy/Paste/Select All menu keeps popping up after performing one of the actions.

See capture of behavior: https://youtu.be/I2cURXChiTA

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the following testing steps:

1. Open any post for editing.
1. Highlight a word.
1. Right-click the highlighted word and select Copy.
1. Move the cursor and click somewhere else within the body of the post.

<strong>Result:</strong> the contextual menu disappears in my test as expected.

I tested with WPDesktop 3.1.0 on Mac OS X 10.13.1.

@BlameDutchie may I ask which version of the desktop app you tested with?

Doe this problem also happen if you try editing a WordPress.com post directly in a browser too?

Does this problem happen for you in any other editing apps that you know of?

**Comment by BlameDutchie** [comment]
@designsimply 
WPD 3.1.0 on Mac OS X 10.13.2
Problem only occurs in this app, nowhere else.

**Comment by nsakaimbo** [comment]
Closing this as stale since we have not been able to repro and no other reports of this issue have been submitted since. Please feel free to re-open or submit a new issue if you encounter this bug in our latest release (v5.0.0-beta2 as of this writing).
