### ISSUE TITLE
Publicize opens a browser window for "reconnect"

### ISSUE THREAD

**Issue by zandyring** [Automattic/wp-desktop#391]
When one of these options shows the marigold alert to RECONNECT a broken connection (I'm sorry I didn't take a screenshot), it shows the classic box-with-arrow, indicating that you will be taken to a new screen. And you are, but it's in the browser, and it looks like this:
<img width="732" alt="screen shot 2017-12-19 at 2 39 05 pm" src="https://user-images.githubusercontent.com/7304712/34175893-ec4ebc3c-e4cb-11e7-9aac-8d362527bad4.png">

**Comment by rachelmcr** [comment]
As reported in #396:

> From a draft post editing screen, I'm attempting to connect a new service for Publicize, and instead of doing that it takes me to my default browser and loads this page instead: http://127.0.0.1:41050/desktop/hey.html
> 
> Here's a video:
> 
> http://cld.wthms.co/rabdBn
> 
> I'm using 3.1.0 of WordPress.com for macOS (with the Stable build, though it's there in Beta too).

**Comment by astralbodies** [comment]
@johngodley Do you have a moment to check this one out? I think it's related to the security changes made.

**Comment by johngodley** [comment]
I think the original report is pre-some of the recent changes as the error page icon has been fixed for a while.

I'm not entirely sure about the reconnect button as these never work for me anyway, but I did notice that clicking the 'add new service' from the sharing panel in the post editor was causing the same problem to occur.

I added #417 which expands the allowed range of URLs that can be opened in a new window, and also connects up the preload security script thing.

**Comment by johngodley** [comment]
Just to add that, as mentioned in the PR, I'm not sure it's the best thing to do anyway. The PR fixes the bug but I think really the behaviour needs changing in Calypso as it doesn't suit the desktop app.

**Comment by zandyring** [comment]
I just got this again, and I'm happy to report that the giant emoji is working now.
<img width="607" alt="screen shot 2018-02-19 at 11 34 00 am" src="https://user-images.githubusercontent.com/7304712/36388269-5364ace2-1569-11e8-94b8-b2aa785ef59d.png">

(directed here from the below):
<img width="305" alt="screen shot 2018-02-19 at 11 34 05 am" src="https://user-images.githubusercontent.com/7304712/36388280-5aa0e9e4-1569-11e8-8da9-5a4e2c26e41a.png">

**Comment by rachelmcr** [comment]
I confirmed that this is fixed in the desktop app v. 3.8.0 (currently in beta) with the change made in https://github.com/Automattic/wp-desktop/pull/530.
