### ISSUE TITLE
Payment Button cannot be added using the desktop app

### ISSUE THREAD

**Issue by nielslange** [Automattic/wp-desktop#392]
**Steps to reproduce**

1. Open WordPress.com desktop app
2. Add new page or post
3. Click on _Add_ in the editor toolbar to add the _Payment Button_

**Expected result**

- _Payment Button_ can be added

**Current result**

- _Payment Button_ can be added (only the options _Media_, _Media from Google_ and _Contact Form_ are visible)

**OS/App**

- OS X 10.13.2 (17C88)
- WordPress.com 3.1.0

![screen shot 2017-12-20 at 19 24 06](https://user-images.githubusercontent.com/3323310/34207076-804420c2-e5bb-11e7-9e95-2b3321d20e04.png)

**Comment by rachelmcr** [comment]
This is because the Simple Payments feature hasn't yet been enabled in the Calypso desktop config here:

https://github.com/Automattic/wp-calypso/blob/master/config/desktop.json

cc @jhnstn as you enabled simple payments in production — is the feature stable enough/ready to be tested/enabled in the desktop app?

**Comment by nielslange** [comment]
Thanks @rachelmcr!

**Comment by jhnstn** [comment]
@rachelmcr yes, simple payment is stable and ready to be tested in the desktop app

**Comment by nielslange** [comment]
@rachelmcr & @jhnstn I'm happy to test it. How can I test it? I assume the change hasn't been deployed yet, right?

**Comment by nielslange** [comment]
@jhnstn I'm happy to test the feature in the desktop app and set the Release Channel to Beta within the app preferences (see screenshot), but I'm not getting the latest version, despite reopening the desktop app several times. Have you deploy the change to the beta branch yet?

<img width="494" alt="screen shot 2017-12-22 at 13 30 38" src="https://user-images.githubusercontent.com/3323310/34287839-569b9554-e71c-11e7-9d3e-781cd7578dd3.png">

**Comment by rachelmcr** [comment]
@nielslange The feature will need to be enabled in the Calypso desktop config first, and then a beta build will need to be released that includes the Calypso PR. The next beta (3.2.0) is coming out at any moment, so this feature won't be enabled until 3.3.0 or later. :)

@jhnstn Would you mind doing the PR in Calypso to enable this on desktop? Thanks!

**Comment by nielslange** [comment]
@rachelmcr Thanks for clarifying this. 😉

**Comment by erricgunawan** [comment]
The user in 1025963-zen also reported this similar issue. He's using Windows Desktop App.

**Comment by MindyPostoff** [comment]
User in 1297182-zen reported same trouble. Running MacOS desktop app.

**Comment by edequalsawesome** [comment]
User in #1306484-zen also reported the same issue, using the Windows desktop app.

**Comment by SiobhyB** [comment]
We had another report of this in 1373375-z. @jhnstn: Any chance you could look into this?

**Comment by rachelmcr** [comment]
I confirmed that the Simple Payments block is available in the block editor in the app. I'm going to close this issue since development focus is on the block editor and I'd encourage anyone looking for the latest editor features to switch to the block editor for this.
