### ISSUE TITLE
OSX: latest drafts does not update

### ISSUE THREAD

**Issue by BlameDutchie** [Automattic/wp-desktop#393]
My workflow:

I write my article in the app and when I'm done, I go to the site to add photo's to finish the article.
If I then publish the article using the site's back-end, the app does not update the amount of drafts.
After a while, clicking on the number shows the right amount in the drop down, but not in the bar.

The only way to get an updated view is sign out/in.

See screenshots.
![dropdown closed](https://user-images.githubusercontent.com/12746371/34308047-22064074-e743-11e7-9083-3e176541130f.jpeg)
![dropdown opened](https://user-images.githubusercontent.com/12746371/34308049-25dfc314-e743-11e7-9496-e8ff1d57f092.jpeg)

**Comment by nickgallop** [comment]
I have a user also reporting this discrepancy in 1450116-zd-woothemes

**Comment by nsakaimbo** [comment]
Closing this issue as I suspect it's not unique to the desktop application, but to using WordPress in a regular browser as well.

Generally speaking we expect we expect this and a whole host of other issues to be resolved or mitigated by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
