### ISSUE TITLE
Don't start on Ubuntu 18.04.

### ISSUE THREAD

**Issue by NohaTech** [Automattic/wp-desktop#394]
I have installed it but when I'm clicking on the application icon it will not start.

**Comment by levlaz** [comment]
This might be the same issue as https://github.com/Automattic/wp-desktop/issues/592

**Comment by nsakaimbo** [comment]
Confirmed I've been able run the latest beta (v5.0.0-beta2) on Ubuntu 18.04. Closing this issue for the time being but please re-open if it still persists.
