### ISSUE TITLE
Bug - Right Click not functioning

### ISSUE THREAD

**Issue by abf310866** [Automattic/wp-desktop#395]
URL:

What I expected: When writing a new post in the Windows 10 app I expected to see a menu when I right clicked - in order to paste a URL in.

Steps to reproduce: (1) Opened Firefox browser and right-clicked - worked
(2) Tried similar process on my iPad - worked
(3) Ctr+V 'work around' in App - worked

What happened instead:  When right clicking in the App literally nothing happens.

Notes:

App - V 1.2.3
Firefox - V 57.0.2
Windows - Windows 10 Home V 1709

**Comment by johngodley** [comment]
V1.2.3 is a very old version. Can you try with the latest 3.2.0? I've just tried on Windows 10 and right click is working fine in the post editor.

**Comment by nsakaimbo** [comment]
Right-click seems to be working correctly at least of the most recent beta (v5.0.0-beta2). Closing this issue but please feel free to re-open if you encounter the issue again.
