### ISSUE TITLE
Can't create new Publicize connection in app

### ISSUE THREAD

**Issue by pmaiorana** [Automattic/wp-desktop#396]
From a draft post editing screen, I'm attempting to connect a new service for Publicize, and instead of doing that it takes me to my default browser and loads this page instead: http://127.0.0.1:41050/desktop/hey.html

Here's a video:

http://cld.wthms.co/rabdBn

I'm using 3.1.0 of WordPress.com for macOS (with the Stable build, though it's there in Beta too).

**Comment by rachelmcr** [comment]
Thanks for the report! I'm closing this issue as we're tracking it here: https://github.com/Automattic/wp-desktop/issues/391
