### ISSUE TITLE
Calypso build is being called twice during compilation

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-desktop#397]
I just cut 3.2.0-beta2 today and got current on wp-calypso master. I noticed that there is an issue with webpack being executed twice during compilation. I think that there is something wrong with the desktop conditionals in the calypso build that's making something execute twice (not just webpack). For example I see `Building Calypso (Desktop on branch release/desktop/3.2.0)` twice in the log file.

The resulting app seems to execute properly but we should make sure nothing is broken and get the duplicate build to stop. @samouri do you have a bit of time to fix this?

**Comment by samouri** [comment]
I'm sorry I never saw this back in Jan 2018 😬. I'm no longer the expert for this, hopefully this issue is either resolved or a different webpack tinkerer can help.

**Comment by astralbodies** [comment]
No worries @samouri I'm going to close this now anyway 😄
