### ISSUE TITLE
Enhancement: Custom Post Statuses

### ISSUE THREAD

**Issue by ngetchell** [Automattic/wp-desktop#398]
I use custom post statuses to keep work sane. Ideas come in as a stub, I outline a few if I have time, then mark the posts I'm working on. 

![firefox_2018-01-10_20-54-04](https://user-images.githubusercontent.com/813422/34804788-72b64848-f648-11e7-8804-bb7ba9c1ef7d.png)

I'd love it if I could use Wordpress Desktop and have it support my workflow.

**Comment by designsimply** [comment]
(Out of curiosity,) may I ask where that screenshot is from and how the "Stub" option was added? Is it from using a specific plugin?

**Comment by ngetchell** [comment]
The Edit Flow Wordpress plugin.

**Comment by nsakaimbo** [comment]
Thanks for the feature request! Closing as this issue isn't specific to the Desktop app. If you're still interested in this feature, please file it in the https://www.github.com/Automattic/wp-calypso repository.
