### ISSUE TITLE
Remind people to pin the app to the dock, so it's always there

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-desktop#40]
Possibly related to #39, right now once you install the app by draggging to the applications folder, there aren't any instructions on putting the app in your dock. 

There are two ways I know of: dragging the app from the applications folder to your dock, or once the app is running, right-click the app when it's running, pick Options, pick Keep in Dock.

Ideas for how to instruct users on this could be a first-launch information bubble that pops up once you open the app the first time, and instructs (perhaps with screenshots) how to add the app to the dock. Would be nice if we could reuse such a information bubble to instruct how to add to the taskbar in Windows, or perhaps even dock in Gnome/Ubuntu (though Linux is arguably harder as we can't know which shell a user runs).

**Comment by mjangda** [comment]
Added in #63
