### ISSUE TITLE
3.2.0-beta2 | Windows 10 | Pressing sign-in button opens external browser

### ISSUE THREAD

**Issue by justsomeguy5** [Automattic/wp-desktop#401]
Installed the 3.2.0-beta2 version on Windows 10

I open the app.  By default the app is showing me a tag feed, presumably the last one I looked at?  TAGS >> CODING

I press the "sign-in" button in upper right.  This opens a new tab in my default browser, IE.  I enter credentials and am now logged into WordPress in IE.  The WordPress app remains logged-out and continues to display the TAGS >> CODING feed.

![wp](https://user-images.githubusercontent.com/34745338/34910054-89f985b0-f8a5-11e7-89d6-4a2628a01f27.JPG)

**Comment by rachelmcr** [comment]
Thanks for the report! This looks like the same issue as reported in https://github.com/Automattic/wp-desktop/issues/400 — I'll close this issue and we'll keep tracking it there.
