### ISSUE TITLE
Help: Error when submitting a support ticket

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#402]
Submitting a support ticket from Help > Contact Us in the app displays this error:

> Parser is unable to parse the response

The user can then resubmit the ticket. However, the ticket is actually submitted successfully, potentially leading to duplicate tickets.

### Steps to Reproduce

1. Open the desktop app.
2. Select the (?) icon at the bottom of the left sidebar to open the Help section.
3. Select the "Contact Us" button to open the contact page.
4. Fill out the contact form and select "Email Us" to submit the support ticket.

Result: The network request receives this response:

> Zendesk API POST Error  (Code: )<br />{"success":true}

And the following error appears on-screen to the user:

> Parser is unable to parse the response

I confirmed that the same steps in a web browser work as expected, with a success message after submitting the ticket.

### Screenshot

![screenshot 2018-01-16 10 42 29](https://user-images.githubusercontent.com/8658164/34985357-b2d52a5e-faab-11e7-8521-6c1236a554f4.png)

##### Tested with Mac OS 10.12.6, WPDesktop 3.2.0-beta2

**Comment by rwaynick** [comment]
User report in 924591-zen

> version 2.5.0. I am running on High Sierra
