### ISSUE TITLE
WPGlobus plugin support

### ISSUE THREAD

**Issue by AiratHalitov** [Automattic/wp-desktop#404]
### Behavior
Titles of pages in analytics looks like this:
`{:ru}Блог{:}{:en}Blog{:}`
To fix this you need add [WPGlobus plugin](https://wordpress.org/plugins/WPGlobus/) support ([GitHub](https://github.com/WPGlobus/WPGlobus)).

The same behavior in WordPress-Android App [#7126](https://github.com/wordpress-mobile/WordPress-Android/issues/7126).
In JetPack plugin analytics titles looks normal.

### Steps to reproduce the behavior
Open App and go to Stats

##### Tested on Ubuntu 16.04, WP-Desktop 3.1.0

- WordPress Forum: https://wordpress.org/support/topic/optimization-for-mobile-devices/#post-9871949
- WP-Desktop 3.1.0
- JetPack  5.7.1
- WordPress 4.9.2

### Screenshot from desktop app: 
![wp-desktop](https://user-images.githubusercontent.com/4050715/35083916-33c013f2-fc43-11e7-96ad-d95425904bf8.png)

**Comment by designsimply** [comment]
Can you please tell me steps for testing so I can see the incorrect titles in my own test site or perhaps provide a link to one of the posts that has a title such as `{:ru}Блог{:}{:en}Blog{:}` in your stats page so I can take a closer look?

Example steps for testing might be something like:

1. Start with a Jetpack-connected site.
1. Publish a post with a title of [please include a sample title].
1. Make sure the post gets some views.
1. Go to https://wordpress.com/ > My Sites > Stats and find the title to check whether it appears normally.

**Comment by AiratHalitov** [comment]
My examples:
https://airat.biz/
https://airat.biz/blog/
https://airat.biz/random/

Steps:
1. Install WordPress, JetPack, WPGlobus, Mobile and Desktop Apps
1. Connect JetPack to your site
1. Add in settings of WPGlobus some languages (like Russian and English or other).
1. Open or create some page and translate Title of page to different languages
1. Open page in incognito mode to collect stats of page (Make sure the post gets some views)
1. Open Stats in Mobile or Desktop App
1. Welcome!

**Comment by AiratHalitov** [comment]
Here is a solution: https://wordpress.org/support/topic/optimization-for-mobile-devices/#post-9877531

> With WPGlobus, it’s all very simple: just filter the database entry before you output it.
> 
> `apply_filters( 'the_title', $text_from_database );`
> 
> Should be as simple as that.
> 
> Thanks
> Gregory
> WPGlobus

Of course if you can apply this solution for Mobile or Desktop App.

**Comment by AiratHalitov** [comment]
Are you still need author reply?

**Comment by nsakaimbo** [comment]
Clsoing as this issue is quite stale.

Further, we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
