### ISSUE TITLE
v3.2.0 beta Desktop App - Site Stats icon in menu

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-desktop#409]
## What I expected

The icon to the right of the `Site Stats` icon is usually a miniature representation of the site stats, depicted as a graph.

## Steps to reproduce

Refreshed the app, clicked on different menu items.

## What happened instead

The icon to the right of the `Site Stats` link doesn't display correctly. This appears when the `Site Stats` link is _not_ selected.

![site_pages_ _paul_jacobson_s_p2_ _wordpress_com](https://user-images.githubusercontent.com/2912202/35487132-e66aab6c-0480-11e8-8d26-33919f70e1e5.png)

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to close this issue in favor of https://github.com/Automattic/wp-desktop/issues/317.
