### ISSUE TITLE
Auto-login when following link from app to WP.com-hosted-page

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-desktop#41]
It would be amazing if following an external link from the app, you would automatically be logged in to the web version by following that link, if you weren't already. 

I'm not aware of the security implications of this, but it would be such a cool feature, probably worth investigating!

**Comment by lancewillett** [comment]
We could also enable the login via mobile app request when you have 2FA enabled, like we do now for WordPress.com.

Flow:
1. Enter username and password.
2. Instead of prompting for 2FA, send request via WordPress mobile app.
3. Confirm in the mobile app.
4. Boom! Logged in to desktop app.
