### ISSUE TITLE
v3.2.0 beta Desktop App - `Published` and `Drafts` counts at 0

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-desktop#411]
## What I expected

`Published` and `Draft` post counts should update to reflect the number of posts under each tab.

## Steps to reproduce

Creating a new draft post and viewing the post lists in the Desktop App.

## What happened instead

Both the `Published` and `Drafts` post counts remained at `0` despite this not being accurate.

![blog_posts_ _paul_jacobson_s_p2_ _wordpress_com](https://user-images.githubusercontent.com/2912202/35487296-9cb9b8bc-0482-11e8-8aa8-212ec35f0814.png)

**Comment by rachelmcr** [comment]
Thanks for the report! I'm closing this issue in favor of the report at https://github.com/Automattic/wp-desktop/issues/399.
