### ISSUE TITLE
WP Desktop app beta v3.2.0 Proxy issues

### ISSUE THREAD

**Issue by Stanjo84** [Automattic/wp-desktop#412]
## What I expected:

The app to run with or without proxy depending on settings under "preferences". The app seems not to take preference changes into account. When it finally opened up, proxy message appears again after log in.

## Steps to reproduce:

- Run app on proxy (enabled/disabled on Windows 10 PC, and in app's preferences).

## What happened instead:

- On proxy and without prompts error message (takes many refreshes and restarting the app for the app to work):

![2018-01-30_7-52-05](https://user-images.githubusercontent.com/9350980/35554026-8c1d7174-059a-11e8-9559-37c4afa3690f.png)

- Hitting "Try again" multiple times either produces result or an error message appears:

![2018-01-30_8-21-52](https://user-images.githubusercontent.com/9350980/35554327-996833fe-059b-11e8-8604-9f156c3cc21b.png)

**Comment by rachelmcr** [comment]
Thanks for the report! The error message mentioned at the end is being tracked in this issue: https://github.com/Automattic/wp-desktop/issues/248

The proxy issue is being tracked and discussed here: https://github.com/Automattic/wp-desktop/issues/334

I'm going to go ahead and close this issue as it looks like it's covered by these two existing issues.
