### ISSUE TITLE
On the profile screen, app makes a call to unreachable API method pinghub/wpcom/me/newest-note-data

### ISSUE THREAD

**Issue by igladun** [Automattic/wp-desktop#419]
#### Steps to reproduce
1. Launch WP desktop app for MacOS
2. Log in with valid credentials
3. Open profile page
4. Open developers tools 
5. Wait for 5 seconds

#### What I expected
No errors in the network tab

#### What happened instead
Calls to unreachable method https://public-api.wordpress.com/rest/v1.1/pinghub/wpcom/me/newest-note-data

#### App Version / OS version
3.2.0-beta2 release, macOS 10.13.3

#### Screenshot / Video
![my profile wordpress com 2018-02-14 09-56-53](https://user-images.githubusercontent.com/4245201/36193397-6b3965dc-116e-11e8-887a-4d81f4b775f9.png)

#### Context / Source
There are other 404 errors on Reader's screen, but they are not related to *.wordpress.com

**Comment by designsimply** [comment]
Great find! This has also been reported in https://github.com/Automattic/notifications-panel/issues/250 and I'd like to close this issue in favor of tracking it in the `notifications-panel` repo since that should cover both Calypso and WPDesktop Calypso.
