### ISSUE TITLE
Bug: "Saving of draft failed" notification makes this unusable :(

### ISSUE THREAD

**Issue by billisalive** [Automattic/wp-desktop#420]
Thanks for this awesome app! I would love to use it, but a small problem is making it unusable.

When I'm editing a post, the app appears to try to save my work almost constantly back to the server. The problem is, if the server doesn't respond well, a notification pops up: "Saving of draft failed."

This would be kind of annoying anyway, but the real problem is that **every time the notification appears, the editor window scrolls to the top.**

![image](https://user-images.githubusercontent.com/3833809/36435395-8f053962-162f-11e8-88c0-d51d175d1d1c.png)

This means that once your post gets beyond a couple hundred words, this notification is almost constantly throwing you back to the top of the screen, losing your place. When this starts happening every five seconds, I quit.

Possible fixes:

- Add preference to disable the notification entirely (my preferred solution).
- At least prevent the notification from scrolling the window up.

I'm using the most recent stable Linux version, 3.2.0, on Ubuntu. This has been a problem for previous versions as well.

Please fix this! It seems like a small fix, and it would make all the difference. I love the idea of editing WordPress posts offline.

**Comment by rachelmcr** [comment]
Thanks for the report! This isn't specific to the desktop app — it's a bug in the Calypso editor itself. I'm going to close this issue as we're tracking that bug here: https://github.com/Automattic/wp-calypso/issues/21484

**Comment by rachelmcr** [comment]
Also just a quick note about this:

>I love the idea of editing WordPress posts offline.

The desktop app currently doesn't support offline editing (which is why you'll see this error if you're offline). Offline support in the app is an enhancement we're tracking here: https://github.com/Automattic/wp-desktop/issues/132

**Comment by billisalive** [comment]
Wow, thanks for such a quick reply @rachelmcr ! I'll comment in the other bug.

Thanks for the tip about the offline editing. Actually, I am seeing this error even when I am online. Maybe my host is glitching ... there could even be some security feature that is intermittently blocking the app. But I don't think so, because sometimes I see this error several times and then it quiets down, having successfully saved (for the moment).
