### ISSUE TITLE
Republicize doesn't recognize Jetpack plan, prompts to upgrade.

### ISSUE THREAD

**Issue by catehstn** [Automattic/wp-desktop#427]
#### Steps to reproduce
1. Jetpack site, with premium plan.
2. Publicize setup and connected.
3. Go to blog post list.
4. Select "share".

#### What I expected
I can use republicize to share my post.

#### What happened instead
I am prompted to upgrade.

#### App Version / OS version
3.2.0

#### Screenshot / Video
<img width="903" alt="screen shot 2018-03-16 at 18 30 31" src="https://user-images.githubusercontent.com/6810182/37538563-e2bf1f92-2948-11e8-9649-6a857c747ee9.png">

#### Context / Source
Could not repro in Safari.
#dogfooding

Let's enable this in the desktop.json. I believe that folks forgot to follow up on this.

**Comment by rachelmcr** [comment]
Noting that republicize is still disabled in the desktop config (but for some reason that doesn't entirely prevent it from appearing in the app): https://github.com/Automattic/wp-calypso/blob/ce3286ed3f3cab9c8524d8e905e44d20589a176d/config/desktop.json#L88

The feature came up in past calls for testing the desktop app (internal ref: p5T066-rt-p2) but there was never a decision made about whether to enable it. I'd be happy to help beta test it in the app if we enable it there.
