### ISSUE TITLE
Mac app: Unread status indicator doesn't go away

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#44]
Moved from https://github.com/Automattic/wp-calypso/issues/2463 hat tip @isaackeyet 

I installed the WordPress.com desktop app (yay!) but the unread indicator won't turn off. I've double checked my Notifications within the app and it says I'm "All caught up".

<img width="151" alt="screen shot 2016-01-15 at 12 54 25" src="https://cloud.githubusercontent.com/assets/3073557/12352577/7aad81d6-bb87-11e5-85c7-a5e73c62ce96.png">
![screen shot 2016-01-15 at 12 54 30](https://cloud.githubusercontent.com/assets/3073557/12352581/80d070a0-bb87-11e5-904b-aaab377c5321.png)

**Comment by designsimply** [comment]
@isaackeyet, does the problem go away if  you close and reopen the app? When this problem happens, are you using a stable internet connection or are you behind a very strict firewall or proxy?

**Comment by dllh** [comment]
I've reproduced this lately too. I think closing and reopening the app does clear the red dot, at least for a bit. My internet connection in general has tended to be stable, but I've noticed a lot of transient network failures in chrome lately that honestly I suspect are related to a proxy bouncing (since others on the same proxy and using different internet providers in different cities have reported similar things).

**Comment by isaackeyet** [comment]
Sorry for missing this! I should change my email notifications for Github.

I just tested it, the dot doesn't clear when I close the app. It also doesn't clear when I reopen the app (even if I go to Notifications again).

I can't get to WP Inbox 0! ;)

**Comment by rachelmcr** [comment]
I have been seeing this issue the past day or so, too. Closing and reopening the app clears the red dot, but after the next notification it reappears and persists after I've read the new notifications.

I noticed that when I opened the app (before I get any notifications/see the red dot) I am getting the following error at `public-api.wordpress.com/:453` in the console:

`WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403`

No other console errors appear after getting and reading the new notification.

**Comment by kraftbj** [comment]
I've been seeing this too. Normally, clicking through notifications will eventually clear it.

**Comment by trepmal** [comment]
I'm a newcomer to the Calypso party :) Just installed an I'm seeing the red dot. Restart didn't help, nor did random clicking in notifications (yet...?).

Internet connection has been stable and I am proxied.

Console just showing `https://public-api.wordpress.com/rest/v1.1/pinghub/wpcom/me/newest-note-data` return a 404

**Comment by dougaitken** [comment]
Confirming I'm seeing this on `3.0.0-beta2`. 

* Updated, then restarted app
* cycled through notifications
* checked `Unread` filter
* repeated steps 1-3

**Comment by nickmomrik** [comment]
This has been happening to me for as long as I can remember. I upgraded to 3.0.0, read the one notification I had, and it's still happening in this latest version of the app. Usually if I close the app and reopen the red circle goes away.

![wp-desktop-unread-notifs](https://user-images.githubusercontent.com/684691/32445088-bb29c216-c2d2-11e7-92e9-06ff8eff80be.png)

**Comment by dougaitken** [comment]
FWIW for the past few days, this hasn't happened anymore for me. No change to the app version between my post above and now.
