### ISSUE TITLE
Question: User privacy and the number of tracking/advertising/analytics scripts

### ISSUE THREAD

**Issue by metmarkosaric** [Automattic/wp-desktop#442]
Been using the WordPress desktop app for Mac to edit/write my blog posts over the last few days. I like the experience a lot. Feels fresh and faster than the browser version too. Would love to continue using it but have a question about user privacy.

How much importance is placed on user privacy and security? The app seems to load a huge number of tracking/advertising/analytics scripts for an open-source project. Some may be necessary to advertise/improve the product but the number seems overboard.

Here's a list of some external scripts loaded and this is not the full list: 

GA 
Quantserve 
Doubleclick 
Googleadservices 
Twitter ads 
LinkedIn ads 
Outbrain 
Adsrvr 
Yahoo analytics? 
Bing 
Facebook 
Advertising.com 
Adnxs

**Comment by nsakaimbo** [comment]
Hello! The Desktop application's analytics are directly inherited from Calypso, and this question would be more appropriate if filed there.

You may also refer to Automattic's Privacy Policy ([link](https://automattic.com/privacy/)) for more information.
