### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by ethitter** [Automattic/wp-desktop#47]
I tend to leave the app minimized on a particular screen I'm interested in, notably stats. If I come back to the app, there's no way to refresh the current view without switching away and back again. If it's meant to auto-refresh, it doesn't do so quickly enough. Sometimes, the app can be persistent and quitting is needed to refresh.

Suggestions based on my usage:
- Refresh on focus after a lengthy period
- Drag-to-refresh support rather than the window-moves-down behaviour we have now
- Maybe allow CMD+R to refresh?

**Comment by jancavan** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/2533

**Comment by rralian** [comment]
I think we just need to implement polling for the stats endpoint. I opened https://github.com/Automattic/wp-calypso/issues/2966 in the calypso repo to request this.
