### ISSUE TITLE
Update development guide

### ISSUE THREAD

**Issue by doublepithre** [Automattic/wp-desktop#476]
#### Steps to reproduce
1. Go to [development guide ](https://github.com/Automattic/wp-desktop/blob/develop/docs/development.md)
2. Check **Tell me more about the server** section
3. It states that the Calypso is loaded in the forked process

#### What I expected

More updated doc about webpack build and loading of Calypso

#### What happened instead

Calypso is not loaded in the forked process since [this](https://github.com/Automattic/wp-desktop/commit/1f922e19e9711e007c1310e0224e9f38db1cb1c8#diff-9ca5fa7ec76f1e688bd3e2fa57f57a8e) commit.

**Comment by belcherj** [comment]
Development guide is updated.
