### ISSUE TITLE
Change secrets instructions to add http://calypso.localhost:3000 to 'Redirect URLs' and 'JavaScript Origins' fields

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-desktop#478]
While reviewing #477 (following setup instructions found at p4TIVU-906-p2), I [couldn't get the app to properly run](https://github.com/Automattic/wp-desktop/pull/477#issuecomment-406275378). The same issue was also present on `master`:

![image](https://user-images.githubusercontent.com/96308/42944847-0c79a80e-8b67-11e8-9bf2-5ad8bd0844d5.png)

('Try again' would yield the same screen.)

Firing up the dev console (Ctrl+Shift+I), I got 

> `public-api.wordpress.com/rest/v1.1/me?meta=flags&<REDACTED>` Failed to load resource: the server responded with a status of 405 ()
> Failed to load resource: the server responded with a status of 405 ()

and

> XMLHttpRequest cannot load `https://public-api.wordpress.com/rest/v1.1/me?meta=flags&<REDACTED>`. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://calypso.localhost:3000' is therefore not allowed access. The response had HTTP status code 405.

I was able to get this to work by adding `http://calypso.localhost:3000` to both 'Redirect URLs' and 'JavaScript Origins', (contrarily to what [the docs](https://github.com/Automattic/wp-desktop/blob/develop/docs/secrets.md) currently suggest)

![image](https://user-images.githubusercontent.com/96308/42948173-3a93b8f8-8b6f-11e8-9c69-8d795eb125c4.png)

Do we need to change secrets instructions accordingly?

/cc @adlk @sirreal @jsnajdr @astralbodies

**Comment by adlk** [comment]
@ockham good catch! Since we now have a dev mode, this should definitely be updated.
