### ISSUE TITLE
Plan: i18n: Some translations are missing

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-desktop#48]
For both WordPress.com and Jetpack sites, the "Plans" pages are missing translations in some parts.

<img width="991" alt="plan-japanese" src="https://cloud.githubusercontent.com/assets/34067/12501270/a4a9685c-c0fe-11e5-87f1-02e0c33a3a75.png">

<img width="647" alt="comparison-japanese" src="https://cloud.githubusercontent.com/assets/34067/12501365/7d07f2ea-c0ff-11e5-8d51-4fa6a057b35d.png">

On browser, the same pages look fine.
e.g. https://wordpress.com/plans/example.com and https://wordpress.com/plans/compare/example.com

<img width="759" alt="plan-browser-japanese" src="https://cloud.githubusercontent.com/assets/34067/12501269/a46f44c4-c0fe-11e5-8cfc-f2da445836d5.png">

**Comment by mjangda** [comment]
@naokomc can you check if this is still broken in the latest version (1.2.7)?

**Comment by naokomc** [comment]
@mjangda I'm still seeing a partially translated screen.
Now the checkmark for the Free plan looks out of place too.

<img width="1070" alt="about_wordpress_com_ _ _ _naoko_takano_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/34067/13242175/9172145a-da35-11e5-8b3f-5b70e4e4de35.png">

**Comment by naokomc** [comment]
FYI I'm still seeing the same screen as my last comment on 1.3.0.
