### ISSUE TITLE
Wordpress for desktop: can not log in

### ISSUE THREAD

**Issue by AnnEm29** [Automattic/wp-desktop#489]
#### Steps to reproduce
1. can not log in into the Wordpress desktop app
2. It writes: "Incorrect username or password" despite the fact that online version is working without issues
3.
4.

#### What I expected
I wanted to log in and use Wordpress for desktop

#### What happened instead
not possible log in

#### App Version / OS version
version 3.4.0.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/42236360/43890312-a9bc292e-9bc6-11e8-8132-0e9970e1c895.png)

**Comment by rachelmcr** [comment]
Thanks for reporting this issue! Are your login details for a WordPress.com account (login at https://wordpress.com/log-in ) or for a WordPress site hosted elsewhere?

This is the WordPress.com for Desktop app, and only accepts WordPress.com account logins. If you'd like to use it with a self-hosted WordPress site (not hosted at WordPress.com) you can select "Add self-hosted site" at the bottom of the login screen for more details.

If you are using a WordPress.com account, and you confirmed that you can log in at WordPress.com in a web browser but not the desktop app, please let us know.

**Comment by AnnEm29** [comment]
Oh, yes, I am using self-hosted site. I did not see this option (maybe you could make a bigger button or just pop up if user don´t use self-hosted site after some unsuccessful logs)

I found that this version of JetPack plans is for payment. Isn´t there some option for NGO for free? 

Thank you!

**Comment by rachelmcr** [comment]
Thanks for confirming! You can sign up for Jetpack's Free plan if you prefer: https://jetpack.com/pricing/
