### ISSUE TITLE
Build: Align babel plugins with Calypso

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-desktop#499]
[Babel config](https://github.com/Automattic/wp-desktop/blob/ac615cb296f3df194f1e0ab752c0e999182a4819/babel.config.js#L6-L8) does not align with [Calypso](https://github.com/Automattic/wp-calypso/blob/1f9b3e6872412b47f1247d8082564afebb826bbb/babel.config.js#L28-L57), which can result in builds [working on one platform](https://github.com/Automattic/wp-calypso/pull/26810), but [not the other](https://circleci.com/gh/Automattic/wp-desktop/22629). 

Let's ensure these configurations align.

**Comment by designsimply** [comment]
I believe this issue is still valid.

**Comment by nsakaimbo** [comment]
Closing as the build system of the desktop application has undergone a lot of changes since this issue was reported. The desktop app now remote-loads the WordPress webapp.
