### ISSUE TITLE
Track Crashes

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#5]
We should have a way of tracking Electron crashes and JS exceptions

From @johngodley 

What we kind of need is:
- An API endpoint to accept 'crashes' from the app (the endpoint would be alongside the download endpoints)
- We hook up the Electron crash reporter to this endpoint
- We hook up app JS exceptions to this endpoint (see desktop/app-handlers/exceptions.js)
- Potentially hook up Calypso client exceptions through IPC to the app, and then the endpoint (although really this is something Calypso should be doing itself)

The endpoint could then bump stats, and store the data somewhere useful ?

The crash reporter is in `desktop/app-handlers/crash-reporter.js`, but the config currently disables it.

I've added `lib/crash-tracker.js` which does most of what I described above, and is used when we get a JS exception in the wrapper app (not in Calypso).

It uses the `crash_reporter_url` config setting, which is currently empty. When we have an endpoint we can then point the Electron crash reporter and our crash tracker at this.

**Comment by mjangda** [comment]
Calypso is currently looking into a service to store js exceptions as well and we can probably piggyback off whatever they end up using.

See https://github.com/Automattic/wp-calypso/pull/2107
