### ISSUE TITLE
Fix Packaging

### ISSUE THREAD

**Issue by mjangda** [Automattic/wp-desktop#50]
Continued from #45:

Since moving to running Calypso in a separate process, we can no longer package the app.

This is because we package the app in an `asar` to avoid path length issues on Windows. However, `asar` has limitations with `child_process` + fork (we can't set a `cwd` correctly, which causes Calypso boot up to fail when running a packaged version of the app).

We need to fix this. Some options:

- Make Calypso work properly even when `cwd` isn't properly set.
- Use `asar` for only some parts of the app (e.g. node_modules)
- Fix issues with asar and forked processes

**Comment by johngodley** [comment]
I haven't been able to test it out on a Windows machine yet, but I believe we can use npm 3+ flat modules to work around the Windows path problem. This means we could then leave `asar` disabled and be able to package the app for all platforms.

This would allow us to make new releases while seeing if we can figure out a better way.

#52

Appreciate any Windows testing help - it'll take a while for me to set it up on my laptop.

**Comment by gziolo** [comment]
This is what I see when I run `make package-mas`:
![screen shot 2016-01-26 at 11 56 34](https://cloud.githubusercontent.com/assets/699132/12580634/6b7a3db4-c431-11e5-9f96-996f510cac77.png)

**Comment by mkaz** [comment]
@gziolo The `package-mas` is a build for the Mac App Store, which was initially started and put on hold to get the rest stable. For Mac, you can use `package-osx`

**Comment by gziolo** [comment]
@mkaz we started working on In App Purchases, which targets only Mac App Store version. It's going to use native Store Kit and needs to be signed off using certificate. When I was testing it back in December 'package-mas' was working properly. I'll try 'package-osx' tomorrow, maybe it's enough to do initial development :)

**Comment by mjangda** [comment]
No longer necessary as of #66
