### ISSUE TITLE
Mac OS X App: Update Stats Auto-refresh label showing wrong refresh rate

### ISSUE THREAD

**Issue by scherem** [Automattic/wp-desktop#502]
#### Steps to reproduce
1. Open app
2.Move mouse over date under traffice graph, box appears stating Auto-refreshing time.

#### What I expected
The dialogue to say "Auto-refreshing every 30 minutes".

#### What happened instead
The dialogue says "Auto-refreshing every 3 minutes"

#### App Version / OS version
3.5 / Mac OS X / Windows (Updated 9/13/2018)

#### Screenshot / Video
![statsrefresh-desktop](https://user-images.githubusercontent.com/5226222/45445671-dd5ddb00-b698-11e8-9d62-3fbbfba5d228.gif)

#### Context / Source
#user-report

Found Github change request for Calypso regarding this issue: [Calypso Issue:26839](https://github.com/Automattic/wp-calypso/issues/26839)
In Calypso issue it mentions that the old time of 3 minutes was hardcoded.  Is it possible that the same issues is happening in desktop apps?

**Comment by pauljacobson** [comment]
To add to the initial report, this is from 1411098-zen.

The user followed up to let us know that they're using the app on Windows.

**Comment by adamleone** [comment]
Hello, similar report mentioned from zen-1406882.

**Comment by rachelmcr** [comment]
Calypso updated this text in https://github.com/Automattic/wp-calypso/pull/26840. The desktop app packages and releases Calypso changes periodically, and this change was made after the last version was packaged. It will be included in the next desktop release.
