### ISSUE TITLE
Login: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by lakejason0** [Automattic/wp-desktop#516]
#### Steps to reproduce
1. Open the app in China
2. Input the email and the password
3. Meet the problem: "The request to undefined failed (code UNABLE_TO_VERIFY_LEAF_SIGNATURE), please check your internet connection and try again."

#### What I expected
The control panel of my blog shows up.

#### What happened instead
A notice: "The request to undefined failed (code UNABLE_TO_VERIFY_LEAF_SIGNATURE), please check your internet connection and try again."

#### App Version / OS version
Version 3.6.0 release
Windows 7
#### Screenshot / Video

![default](https://user-images.githubusercontent.com/36039861/47251558-5950fd00-d467-11e8-901a-72633bea0565.PNG)

**Comment by lakejason0** [comment]
Just in case you think that you can't connect to WordPress.com in China:
![1](https://user-images.githubusercontent.com/36039861/47251642-a1245400-d468-11e8-8271-766b75fa012b.PNG)

**Comment by rachelmcr** [comment]
Thank you for the report! This is a known issue for certain proxy situations, and we are tracking it here: https://github.com/Automattic/wp-desktop/issues/152

**Comment by rachelmcr** [comment]
Thank you for the report! This is a known issue for certain proxy situations, and we are tracking it here: https://github.com/Automattic/wp-desktop/issues/152
