### ISSUE TITLE
Enhancement: Reader: Clicking on post/comment timestamps with Cmd key should open the link as well

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-desktop#517]
## Description 

When clicking on the timestamp on posts/comments on the WordPress.com Reader, the link doesn't load on a new browser tab, which can be done as well.

## Steps to reproduce 

- Open the WordPress.com desktop app and open the WordPress.com Reader section.
- Find a post and click on the timestamp shown over there, **while holding the `Cmd` key on Mac**.

<img width="753" alt="screenshot 2018-10-22 at 21 07 07" src="https://user-images.githubusercontent.com/18581859/47302226-93282c00-d63e-11e8-978c-f66c3c8bcf22.png">
<sup>Image indicating a post from the WordPress.com Reader on the WordPress.com desktop app</sup> 

## What is expected 

The link loads on a new tab on the browser.

## What happened instead

No response seen. Although, clicking on the timestamp without holding `Cmd` loads the link on a new tab on the browser.

## App Version / OS version

Tested on WordPress.com desktop app v3.7.0-beta1 release.

## Context / Source

Out of habit, I often click on new links/timestamps while hold the `Cmd` key to open it in a new tab. Trying to do the same on the WordPress.com desktop app, and that not responding can be something that can be changed.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. 

Clicking the timestamp now opens a post from the Reader in-app.

The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
