### ISSUE TITLE
Why is compulsory to use Jetpack for self-hosted sites?

### ISSUE THREAD

**Issue by marqmarti** [Automattic/wp-desktop#528]
I've found it unnecessary to use of Jetpack to make the app work on self-hosted sites. The Android version doesn't have this requirement. This way the app could become way more used and useful for wordpress users (as the number of sites not using Jetpack is a vast majority)

**Comment by rachelmcr** [comment]
Thanks for the question! This app is specifically WordPress.com for Desktop, and it packages the WordPress.com dashboard called [Calypso](https://github.com/Automattic/wp-calypso). WordPress.com/Calypso work for sites hosted at WordPress.com and self-hosted sites using Jetpack.

This is different from the [WordPress mobile apps for Android and iOS](https://make.wordpress.org/mobile/), which are not specific to WordPress.com.
