### ISSUE TITLE
MacOS: Switching from Beta to Stable channel remains on Beta.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-desktop#535]
#### Steps to reproduce
1. Download the app for MacOS and switch to the Beta channel in Preferences.
2. Re-open the app, confirm the update to the beta.
3. Once you're using the beta, switch back to the Stable channel in Preferences.
4. Re-open the app; the prompt to update the app never appears, and the app continues to be the Beta version (confirmed in the Finder).

#### What I expected
I expected to be prompted for the update back to stable.

#### What happened instead
Nothing. The app remained on the Beta channel.

#### App Version / OS version
3.7 -> 3.8beta1

**Comment by tbradsha** [comment]
Perhaps update issues related to #250?

**Comment by rachelmcr** [comment]
Closing as this was resolved in https://github.com/Automattic/wp-desktop/pull/543.
