### ISSUE TITLE
OSX: WordPress app version 3.8.0 doesn’t load images or videos in media library

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/wp-desktop#545]
#### Steps to reproduce

For the user's flow, who reported the issue, please see the [video](https://bradowenme.files.wordpress.com/2018/12/Screen-Recording-2018-12-13-at-5.18.29-AM.mov) below.

For my experience reproducing the issue:

1. Trying to add an image to a post. Media library opens up. 
2. Adding image via uploading image.
3. After choosing image from my computer, the upload starts and I see preview of image during the upload progress. 
4. The moment the upload is finished though, I see "broken" thumbnail.

#### What I expected

Thumbnail from image in media library.

#### What happened instead

Broken thumbnail.

-> By the way, choosing the thumbnail, then publishing the post etc. works, the image will show up in the published post.

#### App Version / OS version
WordPress app version 3.8.0
(mine) MacBook - macOS 10.13.4 on 
(user)  iMac - macOS 10.14.1

#### Screenshot / Video
Screenshot by user: 
https://bradowenme.files.wordpress.com/2018/12/4.jpg?w=900

Video by user: 
https://bradowenme.files.wordpress.com/2018/12/Screen-Recording-2018-12-13-at-5.18.29-AM.mov

#### Context / Source

#user-report
#1642214-zen

**Comment by rachelmcr** [comment]
Thanks for the report! I see that the site in this report is private — this case is covered by https://github.com/Automattic/wp-desktop/issues/408, where we're tracking the issue for now. I'll close this issue as a duplicate.
