### ISSUE TITLE
Test fork process when sandboxed

### ISSUE THREAD

**Issue by mjangda** [Automattic/wp-desktop#55]
@johngodley: "we should test the server version when sandboxed too. I think we have the correct permissions setup already, but it may need more to allow forking".

See #45

**Comment by beaucollins** [comment]
Looks like we need a new entitlement:
> 2/1/16 11:04:34.038 AM launchservicesd[77]: SecTaskLoadEntitlements failed error=22

**Comment by beaucollins** [comment]
I can't figure out exactly what the issue is, this is the log from `DEBUG=* make run-mas`:

```
  desktop:server app.stdout: wp-calypso booted in 58ms - http://127.0.0.1:41050
 +1ms
  desktop:server app.stdout: 
Getting bundles ready, hold on...
 +0ms
  desktop:server Did not get boot signal from Calypso; exiting. +10s
  desktop:server Killing server +30ms
  desktop:server app.exit with code: 0 (SIGTERM) +19ms
  desktop:server app.close with code: 0 (SIGTERM) +1ms
```

**Comment by mjangda** [comment]
No longer necessary as of #66
