### ISSUE TITLE
Bug: When a link is added, the scrolls reset on top

### ISSUE THREAD

**Issue by albnavper** [Automattic/wp-desktop#552]
#### Steps to reproduce
1. Introduce a lot of content (I saw it in a 7700 words article).
2. Insert a link in the bottom (for example) of the post.
3. The scroll will send you up and you will need to search again the point to continue writing.
4. When you add or edit an image it also happend.

#### What I expected
I expected the scroll to stay in place.

#### What happened instead
Reset to top.

#### App Version / OS version
WP.com Desktop 3.8.0 / W10 with last update

**Comment by rachelmcr** [comment]
Thanks for the report! This was also an issue in Calypso web, as reported in https://github.com/Automattic/wp-calypso/issues/27226.

This should be resolved in the desktop app once the fix in https://github.com/Automattic/wp-calypso/pull/29832 is included in the app build; I'll leave this issue open for now until we can confirm that in a future app version.

**Comment by rwaynick** [comment]
User reported this issue on the Mac app. I've replied asking for their version number in 1942143-zen. Also, confirmed that it's an issue on my test site using the 4.0 release of the app.

**Comment by gemmagarner** [comment]
Another report in: https://en.forums.wordpress.com/topic/bug-wordpress-mac-app-jumps-to-top-of-post-after-linking/ (Mac app).

**Comment by rachelmcr** [comment]
I confirmed that this issue still occurs in the Calypso classic editor (macOS 10.14.5, WPDesktop 4.1.0 stable release) despite the desktop app including the Calypso fix mentioned above.

However, I also confirmed that the issue doesn't occur in the Gutenberg editor. Given that we're no longer actively developing the Calypso classic editor, I wouldn't prioritize this issue for development. @gemmagarner @rwaynick have the users who reported this issue tried Gutenberg instead?

**Comment by tsetend** [comment]
I just had a user who complaint about this same issue, found that they are using Calypso classic editor, before asking the user to switch to Gutenburg, I just ran a quick test using Block editor, which took me back to top after adding link. It does work fine when we have couple of paragraph blocks. But I doubt if users will be happy if they have to add blocks every time they want to add links.

I have made a short Gif here using my WordPress Desktop 4.3.0 Beta2 : 

![wordpressdesktop](https://user-images.githubusercontent.com/5397284/62423909-ef979c00-b6e4-11e9-9d34-a9d09cfeaa31.gif)

**Comment by rachelmcr** [comment]
Thanks for re-testing this and reporting the issue, @tsetend. I confirmed the same issue occurs in Calypso web with the Gutenberg editor now, so this isn't specific to the desktop app in Gutenberg. Could you please report that on the web side so it can be investigated for a fix?

**Comment by tsetend** [comment]
Thank you @rachelmcr! I just tested it and yes there is same issue in Calypso web with the Gutenberg editor. I will report that on web side as well. :)

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released, which remote-loads the WordPress webapp. As noted above, this issue should be resolved once it's fixed upstream in Calypso (if it hasn't been already). 

The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
