### ISSUE TITLE
Permissions errors block some features on private sites

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#554]
This issue is a followup to https://github.com/Automattic/wp-desktop/issues/408 to track permissions errors that persist on private sites in the app:

* Individual media items may not load, e.g. in the media modal (Console error: `403: Access Denied This file requires authorization: You must be logged in and a member of this blog.`)
* Post preview shows logged-out view

#### Steps to reproduce
1. Log in to a test account in the desktop app.
2. Open My Sites > Media. Result: Some or all images do not load.
3. Start a new blog post.
4. Open the media modal. Result: Some or all images do not load.
5. Preview the post. Result: You see the logged-out view of the post with the private site notice.

#### App Version / OS version

WPDesktop 3.9.0-beta1 / macOS 10.14.2

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/8658164/51742188-ef14ad80-2090-11e9-8841-55ba107fbc64.png)
![image](https://user-images.githubusercontent.com/8658164/51742193-f2a83480-2090-11e9-91d0-d21f2299bb7d.png)

cc @pauljacobson

**Comment by jacoswan** [comment]
Variation on this issue: 

* Can't _View Site_ of a site set to private. 

**Steps to Reproduce**

1. Log in to an account on the app that has a site set to private;
2. Select that site, then click View Site
3. See the "Protected Blog" screen or "Something awesome is coming" if site is not published. 

Clicking to other menu items or other sites, and coming back to this site's View Site does not make a difference. However...

4. With View Site still selected, close the app and relaunch. 
5. It relaunches with View Site still showing "Protect Blog". 
6. Click on something else, View Stats for instance, now back to View Site. 
7. Site displays normally. 
8. Close app to repeat 4 - 7, or log out of app to repeat 1-3. 

Based on issue seen in 2021139-zd 

**App Version/OS Version**

WPDesktop 4.0.0 / macOS 10.14.4

**Screenshot / Video**

![bug-report-01](https://user-images.githubusercontent.com/15178758/57519671-26dff200-731c-11e9-91f8-96f67dcf4b58.jpg)

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
