### ISSUE TITLE
Publish release notes/changelog

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#560]
We occasionally get requests to publish release notes/changelogs for desktop releases, both in the app and on our [releases page](https://github.com/Automattic/wp-desktop/releases).

I've tried to compile release notes in the past after we cut the beta, but it was time consuming with hundreds of Calypso PRs included in a single release of the desktop app.

It would be great to come up with a process whereby Calypso contributors could flag their PRs as relevant for public release notes. We could even adopt something like what was done with the WordPress mobile apps (for example https://github.com/wordpress-mobile/WordPress-Android/pull/8740) to ask developers to write a release note for significant changes and use them for desktop releases.

cc @loremattei

**Comment by designsimply** [comment]
Adding a screenshot of the releases page for reference:

![screen shot 2019-02-07 at 12 04 17 pm](https://user-images.githubusercontent.com/1119271/52436151-c056f800-2ad0-11e9-9195-7472d86cdb93.png)

(I looked but couldn't find them in the app, it's possible I just don't know where to look for them!)

Would it make sense to add it to the pull request template only or is it ideal to have a checkbox in the pull request template plus a separate RELEASE-NOTES.txt file like WPAndroid does?

Drafted this but feel free to take it or leave it or change it:

```
### Add a Release Note for WPDesktop
<!--- If there are user-facing changes, please add a release note 
to include in the WordPress.com for Desktop App. Release notes
may be used in the app and on the releases page at 
https://github.com/Automattic/wp-desktop/releases -->
```

Current pull request templates for `wp-desktop` and `wp-caly` for reference:

* https://raw.githubusercontent.com/Automattic/wp-desktop/develop/.github/PULL_REQUEST_TEMPLATE.md
* https://raw.githubusercontent.com/Automattic/wp-calypso/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by StefanNieuwenhuis** [comment]
This looks like a great enhancement, but this issue is inactive for almost a year now...Is it still relevant and is there a way for me to contribute?
