### ISSUE TITLE
Bug: Quitting app in Reader Tag view leaves you logged out at next launch

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-desktop#563]
#### Steps to reproduce
1. Open WordPress app on macOS
2. Navigate to any Tag view in Reader
3. Quit the app
4. Launch the app

#### What I expected
Be logged in and be able to use the app normally

#### What happened instead
I am presented with Tag view but I am also logged out. When clicking `Sign In` the link opens in an external browser. So the app becomes unusable as there is no way to log in within it.

I was able to reporoduce it on my end.

#### App Version / OS version
WordPress.com App 3.9.0 / macOS Mojave 10.14.3

#### Screenshot / Video
![](https://cld.wthms.co/N3b1JQ+)

User's recording: https://cld.wthms.co/qoGQFI

#### Context / Source

Reported in #1810844-zen

#user-report

**Comment by rachelmcr** [comment]
Thanks for the report! This is being in tracked in https://github.com/Automattic/wp-desktop/issues/563, so I'll close this duplicate report. You can find a workaround in https://github.com/Automattic/wp-desktop/issues/400#issuecomment-430563819 to delete and reinstall the app to get it out of this state.

Thanks for also noting the reproducibility — previously it wasn't consistently reproducible just by exiting while on a Reader tag, but it seems the issue has gotten worse as I'm now able to reproduce it with the same steps you noted here. I'll make a note of that on the other issue.
