### ISSUE TITLE
Mac 101 Error upon login

### ISSUE THREAD

**Issue by PaulCyberEngel** [Automattic/wp-desktop#565]
#### Steps to reproduce
1. Delete ~/Library/Application Support (presumably to clear config)
2. Start Wordpress.com App.
3. Login
4.

#### What I expected
To access my sites

#### What happened instead
Uh oh!

WordPress.com ran into an error! (code 101)

#### App Version / OS version
App: 3.9.0
OS: 10.14.3

#### Screenshot / Video
<img width="1012" alt="screen shot 2019-02-23 at 12 21 25 pm" src="https://user-images.githubusercontent.com/8237744/53290155-ceaa4280-3765-11e9-99e6-52ba8be51214.png">

**Comment by designsimply** [comment]
I tested this using WPDesktop 4.0.0-beta1 on macOS 10.13.6 and couldn't see the same problem happen. ([20s](https://user-images.githubusercontent.com/1119271/53436114-a31e9680-39b7-11e9-8fb5-57d673fb599f.gif))

I noticed the screenshot asks whether you are using a proxy, are you using a proxy or are you behind a firewall which could be blocking access for you somehow?

I noticed a similar issue (except their error has a different number than "code 101") where someone said that switching DNS providers solved the problem for them ([ref](https://github.com/Automattic/wp-desktop/issues/334#issuecomment-365541576)). Is switching the DNS temporarily something you are able to try as a test? If you are not sure how, your Internet Service Provider should be able to help you with that.

<blockquote>1. 1. Delete ~/Library/Application Support (presumably to clear config)</blockquote>

To clarify, you deleted the `WordPress.com` folder there, not all of `Application Support` correct?

Is Two-factor Authentication turned on for your account? (asking to know whether to note it as a testing step in case you have it on but forgot to mention it)

Were you able to log in successfully to the same account from the same location with a version of the app prior to 3.9.0 or is 3.9.0 the first version you've tried?

**Comment by PaulCyberEngel** [comment]
I saw similar posts about the 105 error.  I am behind a firewall, but there is no proxy andI have a Windows machine and two iOS devices on the same network that work fine.  This is the first time I’ve tried logging in via a Mac, so I don’t have any previous versions.

You are correct, I deleted the Wordpress.com <http://wordpress.com/> folder, not the entire Application Support.

**Comment by designsimply** [comment]
To confirm, you are able to use the WordPress.com desktop app available at https://apps.wordpress.com/d/windows/ to log in as the same username on the same domain that you are testing with the macOS app?

I can't see the error when testing myself so far, is there any chance that pressing `ctrl + shift + i` on the Mac desktop app after you see the error results in pulling up a console screen where you can see additional information about the errors in the Console or Network tabs?

**Comment by PaulCyberEngel** [comment]
Yes, I have a Windows 10 machine on the same network, and the current version of the app, (3.9.0) works fine.

When I try ctrl+shift+I, nothing happens.  I opened the Console app and searched for errors from Wordpress.com <http://wordpress.com/> and found the following pattern.

I get two instances of "Unable to load Info.plist exceptions (eGPUOverrides)” from WordPress.com <http://wordpress.com/> Helper about 1/2 a second apart, then I see “ nw_path_close_fd Failed to close guarded necp fd 22 [9: Bad file descriptor]” from WordPress.com <http://wordpress.com/> almost immediately after that.

Paul Engel
Author, Blogger, Podcaster, Preacher
and Overall Computer Geek
paul@cyberengel.com

**Comment by designsimply** [comment]
I searched for those error messages and found a possibly-related solution linked from https://stackoverflow.com/questions/52507950/unable-to-load-info-plist-error-xcode-10-under-macos-10-14-mojave which mentions the first error you noted in your last reply which then lead me to https://forums.developer.apple.com/thread/109561 where it says:

<blockquote>if your app is linked with the 10.14 SDK then you must include the NSAppleEventsUsageDescription privacy string in your Info.plist. Without this any attempt to send an Apple event will be denied with an authorisation error.</blockquote>

@astralbodies do you have time to take a look at this or recommend someone who may be able to?

**Comment by astralbodies** [comment]
I checked 3.9.0 and 4.0.0-beta1 on my macOS machine running 10.14.3 and couldn't reproduce the `Uh oh!` unfortunately. I did see, however, that the Info.plist warning and file descriptor error happened to me as well - so I don't think those are necessarily related.

@PaulCyberEngel do you have access to another macOS machine that you could try the app with? I'm trying to eliminate if there's a data-related issue with your account that's affecting the app or if it's related to something with your system configuration.

Thanks!

**Comment by PaulCyberEngel** [comment]
Sorry for the delay, it’s been a busy couple of weeks.

I checked again this morning and both of my macOS devices do the same thing.  First I get a “Page not found” message.  When I click the button to return home I see one of my sites for a moment, then get the 101 error.

Paul Engel
Author, Blogger, Podcaster, Preacher
and Overall Computer Geek
paul@cyberengel.com

**Comment by PaulCyberEngel** [comment]
While one of my Macs had the app open it found an upgrade to 4.0.  (Oddly, only one of my two devices automatically checked for the upgrade.). After upgrading the app worked on both of my devices.

Paul Engel
Author, Blogger, Podcaster, Preacher
and Overall Computer Geek
paul@cyberengel.com

**Comment by designsimply** [comment]
> After upgrading the app worked on both of my devices.

🎉 Thank you for the update! I'd really like to blame internet gremlins but I know this type of error can be specific to either local network or system configurations. 😁
