### ISSUE TITLE
Error: The application was unable to start correctly (0xc0000005). Click OK to close the application.

### ISSUE THREAD

**Issue by nateh1973** [Automattic/wp-desktop#571]
I downloaded the latest app 3.9.0, for Windows 10 Pro, version 1803, as of the 28th of Feb, 2019.  It had worked before and had started giving this error.  I deleted the AppData folder and installed again for just this user as I do every time.  It installs just fine, but when I go to start it, it gives the error in subject line every time.  I had heard that mandatory ASLR causes problems, so I turned it off.  It still won't start.  The WordPress desktop app one day just started giving this error.  I had mandatory ASLR turned on before and it worked, so I don't think that is it, unless memory fails me.

#### Steps to reproduce
1.  Install WordPress 3.9.0
2.  Start WordPress 3.9.0
3.  Error
4.

#### What I expected
A working app.

#### What happened instead
The application was unable to start correctly (0xc0000005). Click OK to close the application.

#### App Version / OS version
WordPress Desktop App 3.9.0
Windows 10 Pro 1803

#### Screenshot / Video
![wordpress-desktop-app-windows-10-1803](https://user-images.githubusercontent.com/48113620/53616668-f6a00880-3ba0-11e9-8a84-26d7dea9336d.png)

I found the error in the course of opening the app in order to edit some blogs of mine.

**Comment by designsimply** [comment]
I searched for that error on Google at https://www.google.com/search?q=The+application+was+unable+to+start+correctly+(0xc0000005) and found several articles indicating it may be a problem related to Windows itself. 

Several of the suggestions in [forums at `microsoft.com`](https://www.google.com/search?q="The+application+was+unable+to+start+correctly+%280xc0000005%29"+site%3Amicrosoft.com) suggest trying a clean boot first. I suggest starting there, then trying one of the articles with the more detailed instructions if it doesn't work, and then contacting a Windows support forum if you continue to have trouble from there.
