### ISSUE TITLE
Dashboard Color Scheme setting isn't respected

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-desktop#578]
#### Steps to reproduce
1. Log into the app, click on your profile, then Account Settings
2. Set the Dashboard Color Scheme to Classic Blue
3. Save settings
4. Click around in the app. Notice the setting makes no difference.

#### What I expected
For the fuchsia to go away in lieu of our less-bright orange scheme

#### What happened instead
The fuchsia wins, even if I restart the app

#### App Version / OS version
4.0.0 / macOS 10.14

#### Context / Source
Complaint on Twitter
https://twitter.com/bixmediocre/status/1110975813820649472

**Comment by rachelmcr** [comment]
Thanks for the report! I confirmed that even after closing and relaunching the app, my color scheme changes aren't reflected there (although they are reflected on the web).

@blowery Could you or someone else from the color schemes project take a look at this?

**Comment by robertocyrino** [comment]
Confirmed while testing 6.0.0-beta4.

**Comment by nsakaimbo** [comment]
Thanks for re-verifying this issue, @robertocyrino! Sounds like this bug is still present.

**Comment by ersatzpenguin** [comment]
Just noting that this came up in 3601425-zen. I confirmed that the issue was still present in 6.0.2, and let the user know that it's a known issue.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
