### ISSUE TITLE
Opening Default Web Browser Instead of within App When Loading Customizer or Editor

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-desktop#581]
#### Steps to reproduce
1. Manage a WordPress.com Business plan site, eCommerce site, or a Jetpack site in the WordPress.com app for Mac.
2. Attempt to open the Customizer or a page/post within the editor

#### What I expected
The Customizer or the editor to load within the WordPress.com app.

#### What happened instead
The page is opened within your default browser.

#### App Version / OS version
WordPress.com version 4.0.0 and macOS Mojave 10.14.3.

#### Screenshot / Video

Image link: https://d.pr/free/i/Qkx57H

#### Context / Source
#user-report
First reported here: 1920707-zen

**Comment by rachelmcr** [comment]
Thanks for the report! This is currently the expected behavior for any sites using Jetpack (e.g. Atomic or self-hosted sites). Any links that direct outside of Calypso (e.g. to the site's WP Admin) will open in the default web browser instead of in the app.
