### ISSUE TITLE
Block Editor: TypeError after select Jetpack > "Connect an account" in app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#586]
#### Steps to reproduce
1. Start a new post in the block editor in the app.
2. Add some content and confirm the draft is saved.
3. Open the Jetpack menu for the post.
4. Click on "Connect an account."

#### What I expected

I expected the app to open my site's Sharing page at https://wordpress.com/sharing/ in a web browser, so I can connect an account.

#### What happened instead

The Sharing page opened, but I also started seeing this console error repeated over and over until I closed the editor:

```
Uncaught TypeError: Cannot read property 'closed' of null
```

#### App Version / OS version

WPDesktop 4.1.0-beta2 / macOS 10.14.4

#### Screenshot / Video

![Screenshot 2019-04-10 16 09 22](https://user-images.githubusercontent.com/8658164/55890679-0d2b7d80-5bab-11e9-9df2-7c4b48beb2be.png)
![Screenshot 2019-04-10 16 02 33](https://user-images.githubusercontent.com/8658164/55890683-0f8dd780-5bab-11e9-9964-4e52c59ba3bf.png)

#### Context / Source
#manual-testing

**Comment by nsakaimbo** [comment]
Clarifying - the expected functionality works, save for the fact that it leads to a persistent console error? (Sounds like something that should be fixed regardless, but just wanted to make sure of the details.)

**Comment by rachelmcr** [comment]
Yep, functionally everything is working ok (I even confirmed that the new connection appears in the app editor without having to exit the editor or reload the app, at least on a WordPress.com Simple site). The only issue is the persistent console error.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
