### ISSUE TITLE
Jetpack connection/site addition flow in app leads to dead end

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#587]
cc @Automattic/luna since this is an issue with the Jetpack connection flow.

#### Steps to reproduce
1. In the app, go to My Sites.
2. Select "Switch Site" in the sidebar.
3. At the bottom of the sidebar, select "Add New Site."
4. Using a self-hosted site without Jetpack, follow the prompts for "Add an existing WordPress site with Jetpack."
5. After Jetpack is installed on your site (this takes you to a web browser) return to the app.

#### What I expected

Ideally the Jetpack connection flow would remain entirely within the app (or the connection flow, if it doesn't work in the app, wouldn't be available there).

Given that it takes me to a web browser, I expected that when I returned to the app I would be taken back to that Jetpack site's dashboard in the app.

#### What happened instead

When I returned to the app, I was stuck on the initial Jetpack connection screens with no way to get back to the dashboard. I had to close the app and clear its settings (deleting `~/Library/Application\ Support/WordPress.com/settings.json` on macOS), and then reopen the app to be able to use it again.

#### App Version / OS version

WPDesktop 4.1.0-beta3 / macOS 10.14.4

#### Screenshot / Video

This screencast shows the Jetpack connection flow with the app on top and a web browser on the bottom: https://cloudup.com/cqdW6F5YzCO (too large to upload directly here)

#### Context / Source
#manual-testing
h/t @supernovia for prompting me to test this flow.

**Comment by designsimply** [comment]
I tested adding a Jetpack site and purchasing a Jetpack Personal Plan using WPDesktop 4.3.0-beta1 on macOS 10.14.5 today and found that it is still leading to a dead end for the desktop app. ([2m9s](https://cloudup.com/cbfwbDf9oKb))

**Comment by designsimply** [comment]
Raising in priority because this came up in beta testing and because of how the app gets completely stuck in this flow requiring modifying system files to get it working again.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
