### ISSUE TITLE
Unable to start wpcom on Debian testing 

### ISSUE THREAD

**Issue by levlaz** [Automattic/wp-desktop#592]
#### Steps to reproduce
1. Using debian testing
2. Download latest .deb from the downloads page 
3. Install with `dpkg -i `
4. Add additional packages with `apt-get -f install` 
5a. Try to start Wordpress from Application Menu 
OR
5b. Execute `/opt/Wordpress.com/wpcom`

#### What I expected
The Wordpress App to Launch

#### What happened instead
5a - Nothing happens 
5b - An error message appears 

```
./wpcom: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

#### App Version / OS version
OS: Debian Testing 
WP: 4.0.0

#### Context / Source

Note, I recognize that debian testing is not released, so I don't necessarily expect this to work. Im filing this bug report because debian testing is almost ready to become stable, and it looks like this effects other distributions based on debian as well. 

Workaround is to install the libgtkextra-dev package as described in this blog post[1]. 

[1] https://linuxconfig.org/how-to-install-wordpress-com-desktop-app-on-ubuntu-19-04-disco-dingo-linux

**Comment by nsakaimbo** [comment]
Thank you for the report, however we're closing this issue as the application is officially built and supported only for Ubuntu.
