### ISSUE TITLE
Editor: Block editor preview on a site with a custom domain returns a 404 the first time

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#595]
#### Steps to reproduce
1. Confirm you are using a version of the app that includes the block editor (4.1.0 or higher).
2. Log in to the app. (If you are already logged in, quit the app and then start it again to ensure the issue will be triggered.)
3. Go to My Sites and select a site with a custom domain.
4. Start a new post or edit an existing post.
5. Switch to Gutenberg (block editor) if you aren’t already using it.
6. Preview the post. Result: You see a preview of your site with a 404 error, instead of the post you are trying to preview.
7. Attempt to preview a second time. Result: The preview works (as we saw in the iOS app).

#### What I expected

I expected the preview to always work.

#### What happened instead

The preview fails with a 404 error the first time on a site with a custom domain. Any attempt to preview a post on the site after that first time will work.

We thought this could be an issue with remote login, but an attempt to resolve the issue on the backend (r191332-wpcom) did not resolve this preview issue.

It looks like this 404 error also appears in Calypso web, but the preview window immediately refreshes to show the preview. The app preview window does not refresh, so the 404 error remains on screen until you manually close the preview and try it again.

#### App Version / OS version

WPDesktop 4.1.0-beta4 / macOS 10.14.4

#### Screenshot / Video

![Screenshot 2019-05-07 14 57 18](https://user-images.githubusercontent.com/8658164/57381961-e8bfc280-71a3-11e9-9300-55e3007c01db.png)

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
I retested this issue in v5.0.0-beta.2 and confirmed I can still reproduce it there.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
