### ISSUE TITLE
Community translator is visible but doesn't activate in the app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#61]
The [WordPress.com community translator](https://en.support.wordpress.com/community-translator/), when enabled in a user's account settings, shows up as a small globe in the bottom right corner. The globe appears in the app, but when you click on "activate translator" nothing happens:

![screen shot 2016-02-01 at 7 05 07 pm](https://cloud.githubusercontent.com/assets/8658164/12727855/c95d5b34-c916-11e5-9a18-249e8dc2f6f9.png)

Steps to reproduce:
1. Under Me > Account Settings, check the box next to "Enable the in-page translator where available."
2. Set your Interface Language to a non-English language.
3. Save your account settings and notice the globe now appears in the bottom right.
4. Hover over the globe, and see that the (translated) text "activate translator" appears. Click it.

Result: Nothing responds (the translator isn't activated) after clicking to activate the translator.

Tested on Mac OS X 10.11.3, app v. 1.2.5.

**Comment by lancewillett** [comment]
I think this is due to JavaScript errors, see https://github.com/Automattic/wp-calypso/issues/2554 — this feature might not be working as expected in the desktop apps. Needs debugging.

**Comment by rachelmcr** [comment]
I tested this issue again, and it is now partially working. Translatable text in the app is being highlighted (as it is in a browser), but it is not correctly identified as translated/untranslated.

Here's how it looks in a browser (text highlighted green to indicate it is already translated):

![screen shot 2016-04-29 at 5 37 22 pm](https://cloud.githubusercontent.com/assets/8658164/14922732/26dea290-0e31-11e6-83b6-f3ca0d5243e2.png)

And here it is in the desktop app (text highlighted orange incorrectly):

![screen shot 2016-04-29 at 5 38 02 pm](https://cloud.githubusercontent.com/assets/8658164/14922739/363d835a-0e31-11e6-8da8-1f9e709b3e24.png)

The translator also doesn't work, as it relies on right-click to submit a translation. Right-click in the browser brings up a translation pop-up:

![screen shot 2016-04-29 at 5 39 48 pm](https://cloud.githubusercontent.com/assets/8658164/14922788/63a1f614-0e31-11e6-8619-48bf8de00bc7.png)

Right-click in the desktop app brings up a copy/minimize menu:

![screen shot 2016-04-29 at 5 40 15 pm](https://cloud.githubusercontent.com/assets/8658164/14922798/76c24db6-0e31-11e6-88a5-af15409d28ef.png)
