### ISSUE TITLE
Plugins no longer available in desktop app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#636]
The latest version of the desktop app (4.2.0) enables the new Calypso streamlined nav bar. However, with that new nav bar the Plugins section is no longer available in the app.

@griffbrad It looks like the streamlined sidebar relies on the `calypsoify/plugins` feature flag to show the Plugins sidebar item:

https://github.com/Automattic/wp-calypso/blob/9df353f7a06d7885548cdf33454b83bda35b2e9d/client/my-sites/sidebar/tools-menu.jsx#L141

But that feature flag isn't defined in the [desktop config](https://github.com/Automattic/wp-calypso/blob/master/config/desktop.json) at all. Is that an oversight or was the Plugins section intentionally removed from the app?

New nav on the web:

![sidebarnav-web plugins](https://user-images.githubusercontent.com/8658164/59838892-aadbbf80-9347-11e9-9f8f-f018ee518725.png)

New nav in the app:

![sidebarnav-wpdesktop plugins](https://user-images.githubusercontent.com/8658164/59838899-aca58300-9347-11e9-85fc-a8b4364ac0c0.png)

**Comment by rachelmcr** [comment]
cc @Automattic/team-calypso

**Comment by jsnajdr** [comment]
> It looks like the streamlined sidebar relies on the `calypsoify/plugins` feature flag to show the Plugins sidebar item:

The old sidebar implementation used the `calypsoify/plugins` flag only to determine the target location of the "Plugins" link: Calypso's `/plugins` section or the Calypsoified wp-admin Plugins UI.

Whether the "Plugins" sidebar item is shown at all depended on other information: whether the user has permissions to install plugins or whether the site is Simple, Atomic, Jetpack, domain-only, etc.

**Comment by rachelmcr** [comment]
Thanks for clarifying, @jsnajdr. Any idea why the Plugins sidebar item isn't showing up in the app anymore (as of v 4.2.0)? Even when it should be shown (based on other information, and when it appears on the web) it isn't showing in the app now.

**Comment by jsnajdr** [comment]
The Plugins sidebar item is not showing on desktop because the `calypsoify/plugins` flag is not set there, while in all other environments (i.e., web) it is.

How do we open wp-admin links in the desktop app? Inside the Electron window, or do we open them in a regular browser?

**Comment by rachelmcr** [comment]
> The Plugins sidebar item is not showing on desktop because the `calypsoify/plugins` flag is not set there, while in all other environments (i.e., web) it is.

Ok, thanks, that's what I thought. I realize now that your previous comment was about the old sidebar implementation (I thought you were referring to the current implementation and got a bit confused).

> How do we open wp-admin links in the desktop app? Inside the Electron window, or do we open them in a regular browser?

We open them in a regular browser.

**Comment by designsimply** [comment]
Tested and confirmed that I cannot see an option for Plugins on a Jetpack site in WPDesktop 4.3.0-beta1 on macOS 10.14.5.

![Screen Shot 2019-07-08 at 5 17 30 PM](https://user-images.githubusercontent.com/1119271/60848620-8b94bd00-a1a4-11e9-8ed0-246908aec334.png)
<sub>Tested with Jetpack 7.5.2 WordPress 5.2.2 on separate-panther.jurassic.ninja using WPDesktop 4.3.0-beta1 on macOS 10.14.5.</sub>

**Comment by designsimply** [comment]
@jsnajdr would it be a good solution to add back Plugins to the left menu and open it in a regular browser? Is that something you can update?

**Comment by designsimply** [comment]
Raising to high priority because access to Plugins missing completely from the WPDesktop app was identified as a point of confusion during beta testing.

**Comment by jsnajdr** [comment]
@designsimply I submitted a patch for this issue in Automattic/wp-calypso#34676.
