### ISSUE TITLE
Windows: Add spell check solution

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-desktop#637]
Since support for After the Deadline was removed in https://github.com/Automattic/wp-calypso/pull/31865, the apps no longer have spell check capabilities on Windows.

On the web version, we can rely on the browser's spell check or an extension like Grammarly. These solutions don't apply to the apps though.

I've checked 4.2.0 on Windows and there's no way to check for typos with the classic editor, block editor, or classic block in the block editor.

#### App Version / OS version
Windows 4.2.0

The corresponding issue for OSX https://github.com/Automattic/wp-desktop/issues/389

#### Context / Source
#8859787-hc

**Comment by thebud15** [comment]
Requested in #2267204-zen

**Comment by tijosh** [comment]
Another request for this on Mac in #2626854-zen

**Comment by nsakaimbo** [comment]
Update: more reliable spellchecking across all platforms (Windows included) is part of a forthcoming update (v5.0.0) that includes an upgrade of Electron and core dependencies (see #757).
