### ISSUE TITLE
Editing Page Sends User to Browser

### ISSUE THREAD

**Issue by gsmumbo** [Automattic/wp-desktop#638]
#### Steps to reproduce
When the user edits a page on https://www.infosecmonkey.com in the Desktop App it sends them out of the app and in to their browser

#### What I expected
Edit the page in the app

#### What happened instead
Sent to web browser instead

#### App Version / OS version
App 4.2.0 / MacOS Mojave 10.14.5

#### Screenshot / Video
Can't upload due to file type. Can be found in 2126293-zen

#### Context / Source

#user-report

**Comment by manfernan** [comment]
It started to happen after the last update of the desktop app.

**Comment by rachelmcr** [comment]
I confirmed that the site is a Jetpack site, and it's set to use the block editor. It's currently expected that sites using the block editor will open editor links outside the desktop app (in the browser).

The latest version of the desktop app no longer forces Jetpack sites to use the classic Calypso editor, but it doesn't yet include the block editor within Calypso for Jetpack sites. You can refer to https://github.com/Automattic/wp-calypso/issues/32048 for progress on enabling that in the desktop app. Once the app supports the block editor within Calypso, links to the block editor will open in the app. Until then, the app will direct to the browser for the block editor.

**Comment by designsimply** [comment]
We are now also tracking this in #640.
