### ISSUE TITLE
Question about plugin management

### ISSUE THREAD

**Issue by indig0F10w** [Automattic/wp-desktop#639]
As some people have already asked and got half-answers...

**Will plugin management in desktop app be coming back or not?**

Removing plugin management as a fix for Jetpack errors seems like a bad choice.

**Comment by rachelmcr** [comment]
Thanks for raising this question! I've opened https://github.com/Automattic/wp-desktop/issues/636 to see if that was an intentional change, and I'd invite you to follow along there. I'll close this as a duplicate issue.
