### ISSUE TITLE
Signup: Signup flow in the desktop ends with blank page instead of checklist

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#641]
#### Steps to reproduce
1. Start logged out of the desktop app.
2. Select "Create account" to begin the signup flow.
3. Continue through the signup flow to set up a new account and site.

#### What I expected

I expected to end the signup flow logged in on the site checklist screen.

#### What happened instead

I ended logged in (with a working masterbar) but otherwise the screen in blank. The app navigated to `/checklist/my-new-site.wordpress.com` but nothing loads there.

It looks like this is because the phase 2 checklist is behind a feature flag (`onboarding-checklist/phase2`) but that flag wasn't added to the desktop config.

#### App Version / OS version

WPDesktop 4.2.0 / macOS 10.14.5

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/8658164/60492777-55db6a00-9cb4-11e9-85cd-0510c81de3fd.png)

#### Context / Source
#beta-testing 
internal ref: p5T066-SK-p2#comment-2987

cc @Automattic/start-dev

**Comment by rachelmcr** [comment]
For context, we get ~35 signups a day via the desktop signup flow (low impact compared to web signup volume, although it affects every new signup in the app).

**Comment by designsimply** [comment]
Tested as part of 4.3.0-beta1 testing and confirmed that the Create Account flow on WPDesktop ends in a blank page. ([50s](https://cloudup.com/cFnkso9eMr5))

![wpdesktop-blank-landing-page-after-signup](https://user-images.githubusercontent.com/1119271/61017836-da338a00-a351-11e9-8a75-0b2bd8f76a2c.png)
<sup>Tested with WPDesktop 4.3.0-beta1 on macOS 10.14.5.</sup>

**Comment by designsimply** [comment]
Raising to high priority because it was reported in the last two beta testing sessions and because signup is an important flow for our users in any platform.

**Comment by ramonjd** [comment]
Possible fix in https://github.com/Automattic/wp-calypso/pull/34447

**Comment by rachelmcr** [comment]
I tested the fix in version 4.3.0-beta2 and the checklist appears as expected! I'll close this as resolved; we can reopen it or open a new issue if any problems with the checklist behavior are uncovered in further testing.
