### ISSUE TITLE
Checkout: Plan purchase in app leads to dead-end flow

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#642]
#### Steps to reproduce
1. Start logged out of the app.
2. Create a new account and site.
3. On the Plan step in the signup flow, select a paid plan.
4. Complete the signup and checkout steps.
5. After checkout, try to continue using the app.

Alternate user flow:
1. Start logged in to the app.
2. Go to My Sites > Plans and select a new paid plan for your site.
3. Complete the checkout to purchase the new plan.
4. After checkout, try to continue using the app.

#### What I expected

I expected a clear user flow to continue using the app after checkout.

#### What happened instead

The main call to action after checkout is to visit your site, which opens the site in a browser window. There is no clear path to continue using the app — even restarting the app opens it again on this screen.

The only way to continue using the app is to click the Help icon in the bottom right and select "More Help" there. This directs you to Calypso Help and brings back the masterbar so you can navigate again.

#### App Version / OS version

WPDesktop 4.3.0-beta1 / macOS 10.14.5

#### Screenshot / Video

![Screenshot 2019-07-08 10 32 50](https://user-images.githubusercontent.com/8658164/60800530-4739fa80-a16d-11e9-9f98-46b0ebfa03fd.png)

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
I'm not sure which team is best positioned to investigate this — the checkout experience works, but the post-checkout flow is where things are broken. @Automattic/fixing-the-flows is this a flow you can help with?

For comparison, on the web after checkout I'm taken to this Quick Start offer:

![Screenshot 2019-07-08 11 20 38](https://user-images.githubusercontent.com/8658164/60803349-ead9d980-a172-11e9-8998-61355b9208c3.png)

And if I decline that offer I'm taken to my site checklist, which isn't available in the desktop app (see also https://github.com/Automattic/wp-desktop/issues/641).

**Comment by designsimply** [comment]
I tried the alternate flow first. I tried purchasing a WordPress.com Premium Plan using WPDesktop 4.3.0-beta1 and then clicking all of the post-purchase buttons. In this test, the buttons all worked well and the flow went back into the app. ([3m48s](https://cloudup.com/czATEg1Q1yl))

The thank you page looked like this in my test:

![congratulations-on-your-purchase](https://user-images.githubusercontent.com/1119271/61069751-3b973f80-a3ca-11e9-9559-bf4491466bbf.png)
<sup>Tested with WPDesktop 4.3.0-beta1 on macOS 10.14.5.</sup>

**Comment by rachelmcr** [comment]
Ah, I _think_ this depends on the age of the account you test with. It looks like the screen I saw is the "streamlined paid NUX thanks page" (defined [here](https://github.com/Automattic/wp-calypso/blob/6324c6d30d4ece27eeb00faa3e7cc0aa1f817f83/client/my-sites/checkout/checkout-thank-you/index.jsx#L436)) shown to new users (defined as users who created their account within the last two hours). I believe I tested the alternative flow on a fairly new account, which would be why I saw the same screen for both flows.

It looks like you saw the standard thanks page, which doesn't have this issue.

**Comment by designsimply** [comment]
I tested two more times, this time purchasing a WordPress.com Personal Plan, and I was able to get stuck in the purchase flow in the app on the thank you page as described in this issue above.

Plan purchase flow with domain: [2m21s](https://cloudup.com/cEByb6daUJv)

Plan purchase flow: [2m28s](https://cloudup.com/cHDTM8pEvAx)

The thank you page in this flow shows no masterbar and obvious way back into the app:

![thank-you-for-your-purchase-screen](https://user-images.githubusercontent.com/1119271/61072140-e9591d00-a3cf-11e9-8fbe-d01ceb3902fc.png)
<sub>Tested with WPDesktop 4.3.0-beta1 on macOS 10.14.5.</sub>

I found that if I restarted the app a few times then I could see the same screen _with_ a masterbar which I could use to navigate. The flow Rachel mentioned about clicking the bottom-right question icon and then "More Help" also works but it isn't very obvious at all how to get back to the app from here.

**Comment by designsimply** [comment]
Raising to high priority because it was found during beta testing and because it's a blocked purchase flow.

**Comment by rachelmcr** [comment]
I ran into this again after making a plan purchase on a brand new account/site while smoke testing the 4.4.1 beta:

![Screenshot 2019-10-22 11 26 57](https://user-images.githubusercontent.com/8658164/67277545-f1d8ed80-f4be-11e9-8829-a853832c4ddd.png)

@Automattic/neutron @rralian Would this fall under the umbrella of the redesign work you're doing on the checkout flow?

**Comment by fditrapani** [comment]
@racheleldracher this isn't related to the redesign we're working. It looks like it's signup related. If the checklist isn't working in the app, can we directed folks to the preview of their site within Calypso (`https://wordpress.com/view/{site}`) when they press the button

**Comment by ianstewart** [comment]
I was able to see something similar in Calypso as well when making a purchase while my site was private in an pre-"launch" state.

**Comment by rachelmcr** [comment]
Thanks for taking a look!

> If the checklist isn't working in the app, can we directed folks to the preview of their site within Calypso (`https://wordpress.com/view/{site}`) when they press the button

To clarify, this issue isn't related to the checklist. Even if I've completely completed the checklist and launched my site, and then I go back to purchase a plan, I end up at this dead-end thank you screen after checkout. However, it is related to checking out with a fairly new account, since this checkout screen isn't shown to users after a certain time past signup.

> I was able to see something similar in Calypso as well when making a purchase while my site was private in an pre-"launch" state.

@ianstewart When you make the purchase in Calypso web, do you see a masterbar? I tested a couple checkout scenarios with a new account on the web and each time I saw the masterbar so I was able to navigate away from this screen:

![Screenshot 2019-10-23 12 20 41](https://user-images.githubusercontent.com/8658164/67388512-b60e5880-f590-11e9-8812-38ea04616409.png)

That's different from the app experience, where the masterbar doesn't appear so I'm stuck at a dead end unless I use the Help icon to navigate away.

**Comment by fditrapani** [comment]
> To clarify, this issue isn't related to the checklist. Even if I've completely completed the checklist and launched my site, and then I go back to purchase a plan, I end up at this dead-end thank you screen after checkout.

Thanks for clarifying @rachelmcr.  In that case, we should be sending folks to the screen in this comment after they checkout: https://github.com/Automattic/wp-desktop/issues/642#issuecomment-510568262. 


> @ianstewart When you make the purchase in Calypso web, do you see a masterbar? I tested a couple checkout scenarios with a new account on the web and each time I saw the masterbar so I was able to navigate away from this screen:

I tried upgrading a new private site, after I signed up, and an old site and in both cases I was taken to this screen:

![image](https://user-images.githubusercontent.com/6981253/67392298-48513500-f56e-11e9-9d18-f5068d04a52f.png)

> I'm not sure which team is best positioned to investigate this

The whole new user thing sounds kind of familiar to me. I wonder if @taggon from Customer Marketing might have any insight into what's happening here. Taegon, for some background, we are having reports of people being taken to an old post purchase screen after upgrading a new site. When we implemented the checklist, do you remember if we had a timer set to direct people to the checklist or not?

**Comment by rachelmcr** [comment]
> Not seeing the wpcom-branded screen in Calypso is the issue I'm reporting. (Might need to be a separate issue?)

Ah yeah, that's probably worth a separate issue. I believe the screen in this report is the "streamlined paid NUX thanks page" (defined https://github.com/Automattic/wp-calypso/blob/6324c6d30d4ece27eeb00faa3e7cc0aa1f817f83/client/my-sites/checkout/checkout-thank-you/index.jsx#L436).

The crux of the original report here is that in the app this checkout flow is a dead end, and it's an issue that's specific to the app.

**Comment by fditrapani** [comment]
> The crux of the original report here is that in the app this checkout flow is a dead end, and it's an issue that's specific to the app.

Two options for fixing this could be:
1. Change the destination of the "Visit your site" url so that it takes people to the site preview in Calypso (`https://wordpress.com/view/{site}`). This will keep people in Calypso and allow them to see their sites. 
2. Display the thank you screen we show after the plan purchase which offers more direction based on your plan purchase. [Screenshot in this comment](https://github.com/Automattic/wp-desktop/issues/642#issuecomment-545418251)

Either way, we should also look into displaying the master bar on that screen.

**Comment by lcollette** [comment]
>Not seeing the wpcom-branded screen in Calypso is the issue I'm reporting. (Might need to be a separate issue?)

Can you please create a separate issue for the Calypso issue?

**Comment by ianstewart** [comment]
> Can you please create a separate issue for the Calypso issue?

Yep! New issue here:

https://github.com/Automattic/wp-calypso/issues/37009

**Comment by sixhours** [comment]
I recorded the process of both purchasing a new plan with a brand new account, and upgrading from an existing plan with an existing account. 

**Purchasing a plan with a brand new account**

https://cloudup.com/i2AvspwzN6E and https://cloudup.com/igd7jW3fOsF

^ This worked as expected for me, redirecting to the checklist after purchase.

**Upgrading a plan on an existing account**

https://cloudup.com/iuDi8BmDRWp

I was able to reproduce the bug by logging into the new account I'd just made and upgrading my plan. I'm brought to the old confirmation screen, with no masterbar, and no way to get back to the app without going through the help section.

I suspect the app is using an old version of Calypso, as evidenced by a number of updates I'm not seeing (the signup experience is very old, the site privacy flag in the sidebar uses an icon rather than text, and when you upgrade a private site to the Business plan there's no warning about this switch making it public).

I suspect if we upgraded `/wp-desktop` to use the latest version, we would at least have access to the masterbar on that final checkout screen. /cc @Automattic/hogwarts or @Automattic/team-calypso since the documentation suggests y'all are responsible for that sync?

**Comment by rachelmcr** [comment]
> I suspect if we upgraded /wp-desktop to use the latest version, we would at least have access to the masterbar on that final checkout screen.

I tested the "Upgrading a plan on an existing account" flow again in the new desktop beta (version 4.5.0-beta1). That version was frozen today, including Calypso as of this commit: https://github.com/Automattic/wp-calypso/commit/46879183ea9d0c7f36e9235e151564077ace5df1

The good news is that the masterbar is now showing up in the app in this flow! 🎉 

<img width="1228" alt="Screen Shot 2019-10-24 at 5 20 40 PM" src="https://user-images.githubusercontent.com/8658164/67505263-d1599080-f682-11e9-9c20-27dd2b6e6a75.png">

I wasn't aware that the masterbar behavior changed recently in Calypso, so that explains the recent difference between web and app behavior.

> I suspect the app is using an old version of Calypso, as evidenced by a number of updates I'm not seeing (the signup experience is very old, the site privacy flag in the sidebar uses an icon rather than text, and when you upgrade a private site to the Business plan there's no warning about this switch making it public).

Although this dead end is resolved, I wanted to address these concerns:

The desktop app updates Calypso with each release. A new release (4.5.0) was just [released in beta](https://github.com/Automattic/wp-desktop/releases/tag/v4.5.0-beta1) with the latest Calypso, while the last release (4.4.0) had a code freeze on Oct 2 so it just missed some newer changes like the site privacy flag in the sidebar. The Platform 9 3/4 team is currently looking at shortening the release cycle for this app to keep it more in sync with Calypso web (cc @loremattei).

However, some things in the desktop app are older than what's used on the web due to feature flags or a/b tests that aren't included in desktop builds. I believe that's why the signup flow is older — there are some signup a/b tests (not included in desktop) as well as these signup feature flags that are disabled on desktop:

https://github.com/Automattic/wp-calypso/blob/master/config/desktop.json#L87-L89

It looks like the warning about upgrading a private site to the Business plan was added in August, so it should be in the Calypso commits already included in the desktop app — if it doesn't appear and we expect it to (i.e. it isn't behind an intended feature flag or part of a test), we should investigate that further, perhaps as a separate issue.

**Comment by rachelmcr** [comment]
Given that this dead end is resolved (now that the masterbar appears on this screen in the app) and the unexpected post-checkout screen is being handled in https://github.com/Automattic/wp-calypso/issues/37009, I'll go ahead and close this issue as resolved. Please feel free to reopen if I've overlooked something that still needs to be dealt with.

**Comment by rachelmcr** [comment]
> when you upgrade a private site to the Business plan there's no warning about this switch making it public

I opened https://github.com/Automattic/wp-desktop/issues/687 to track this issue.
