### ISSUE TITLE
Ensure `dev-app-update.yml` exists before running `make dev`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-desktop#643]
Since the process spits out warnings:
```
desktop:updater:auto Update error { Error: ENOENT: no such file or directory, open 'dev-app-update.yml'
```

...when the file doesn't exist, it might be good to just create/copy that file with default values before the app spins up.

**Comment by nsakaimbo** [comment]
Closing - the auto-updater should now be disabled in development mode, so this shouldn't be an issue.
