### ISSUE TITLE
Self-hosted with jetpack opens browser for editing or new posts

### ISSUE THREAD

**Issue by helmutgranda** [Automattic/wp-desktop#647]
#### Steps to reproduce
1. Open Mac App
2. Login with credentials
3. Click on "Write" button on top right corner

#### What I expected
I should be able to write a new posts inside the app.

#### What happened instead
It opens a new browser window ready for me to create a new post in the browser

#### App Version / OS version
V 4.2.0 - MacOS Mojave

#### Context / Source
When I first installed the app it was working as expected, I was asked by the app if I wanted to create posts with the "block" feature which I accepted, after that I have been redirected to a new browser window. It is the only thing that I can think of that is different and I am not able to disable block editing.

I am able to create posts on wordpress.com inside the app and I am being asked if I want to try the block editor. I am afraid once I do so I wont be able to use the app and everything has to be done on the browser.

![image](https://user-images.githubusercontent.com/82293/61070782-165bfe80-a3d5-11e9-980e-d787fffc559d.png)

**Comment by designsimply** [comment]
Thank you! We are tracking this issue in https://github.com/Automattic/wp-desktop/issues/640 so I will close this one as a duplicate and also note that 640 has been labeled high priority but it may take several weeks to get some of our bigger WordPress.com Desktop app bugs fixed. Thanks for using the app and for taking the time to report issues!
