### ISSUE TITLE
MacOS updater is unreliable.

### ISSUE THREAD

**Issue by loremattei** [Automattic/wp-desktop#650]
The app auto-update feature is unreliable on MacOS. The user has to repeat the update process several times before the app is actually updated. 

#### Steps to reproduce
1. Open the app and when the prompt for a new version is displayed, confirm and proceed.

#### What I expected
The app should close and the new version should start. 

#### What happened instead
The app closes and nothing happens. When the user manually restarts the app, the old version is run and the prompt to update is shown again. 

This happens for several times. Eventually, the app gets updated. 

#### App Version / OS version
4.2.0/MacOS

**Comment by designsimply** [comment]
:wave: @loremattei this looks like a duplicate of https://github.com/Automattic/wp-desktop/issues/250 can you confirm?

**Comment by loremattei** [comment]
@designsimply yes, it is. I was pretty sure it was already filed, but I didn't realise it was so old and didn't look that far back. I'm closing this one.
