### ISSUE TITLE
Account recovery settings can't be fetched immediately after signup

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#655]
#### Steps to reproduce
1. Log out of the app.
2. Select "Create Account" and go through the signup flow.
3. After signup, select "Download mobile app" in the site setup checklist.

#### What I expected

I expect the "Get Apps" page (`/me/get-apps`) to load.

#### What happened instead

The "Get Apps" page appears and the following error appears on screen:

> An error occurred while fetching your account recovery settings.

This `account-recovery` endpoint returns a 403 `unauthorized_client` error with the message `Your client is not permitted to access this resource.`

This endpoint is used on the Get Apps page, for the SMS download link section. The same error appears under `/me/security/account-recovery`.

Restarting the app does not resolve the error, but logging out of the app and logging back in to the same account does resolve it.

#### App Version / OS version

Originally reported in WPDesktop 4.3.0-beta2 / macOS 10.14.5
Tested again in WPDesktop 4.7.0-beta1 / macOS 10.15.2

#### Screenshot / Video

![Screenshot 2020-01-20 16 01 25](https://user-images.githubusercontent.com/8658164/72741177-0486bf80-3b9f-11ea-9142-15bc89bb4f93.png)

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
I confirmed this is still an issue as of WPDesktop 4.7.0-beta1. The steps to reproduce and where the error appears has changed since the original report; I updated the issue description with the latest details.

**Comment by designsimply** [comment]
Noting that this came up in 5.1.0 beta testing as well. See #853. (Thanks @rachelmcr for catching the duplicate!)

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
