### ISSUE TITLE
View pages/posts arrow in post/page editor screen not working 

### ISSUE THREAD

**Issue by StefZarb** [Automattic/wp-desktop#656]
#### Steps to reproduce
1. Add a new post or page
2. Enter content
3. Save draft
4. Click on the 'View Posts' arrow

#### What I expected
To go back to the dashboard and view a list of posts/pages

#### What happened instead
The page doesn't change. 

#### App Version / OS version
MacOS Version 4.2.0

#### Screenshot / Video
https://monosnap.com/file/v8lfPVAevHVESp8WIMMcglwiI60wic

#### Context / Source

 #user-report

**Comment by rachelmcr** [comment]
Thanks for the report! This is a duplicate of https://github.com/Automattic/wp-desktop/issues/651 and is resolved in version 4.3.0 (currently in beta). There are a couple workarounds mentioned in that issue in the meantime:

* You can use the navigation in the `Window` dropdown menu, or using the shortcuts (e.g. `⌘ 1` to go to My Sites).
* You can try out the beta version by going to the app menu under WordPress.com > Preferences and selecting "Beta" for the Release Channel. Restarting the app will trigger an update to the beta version.

**Comment by StefZarb** [comment]
Thanks for letting me know and for the workaround, Rachel!
