### ISSUE TITLE
Remove obsolete CSS

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-desktop#67]
In https://github.com/Automattic/wp-calypso/pull/2964/ @drewblaisdell said:

This block obviates [most of these](https://github.com/Automattic/wp-desktop/blob/master/public_desktop/wordpress-desktop.css#L134) styles. They should be removed once this is merged.

**Comment by jasmussen** [comment]
Are you on top of this, @scruffian, or would you like me to take a stab at this? It's no problem I can fix this quickly, just wasn't sure if you meant to tackle this based on the context. Let me know!

**Comment by drewblaisdell** [comment]
This has been fixed by https://github.com/Automattic/wp-desktop/pull/79

**Comment by jasmussen** [comment]
👍
