### ISSUE TITLE
Fix file-loader builds

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-desktop#670]
https://github.com/Automattic/wp-calypso/pull/36139 fixed the server build for Calypso for `file-loader` handled imports from `node_modules`. The same fix will likely be necessary for the Desktop build.

**Comment by AaronCHKL** [comment]
MID-REBYERNMD

**Comment by nsakaimbo** [comment]
Update: the overhauled Desktop application now remote-loads WordPress.com, and this issue is no longer relevant. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
