### ISSUE TITLE
creating new draft leads to permanent expired nonce

### ISSUE THREAD

**Issue by DigitalDavo** [Automattic/wp-desktop#675]
#### Steps to reproduce
1. Try to create a new draft, leads to nonce page. no ability to get back. have to close.
2. can reproduce by quitting and starting again
3. work around - use jetpack connection via wordpress.com web site instead.
4.

#### What I expected
To see the create new post page

#### What happened instead
<img width="646" alt="expired-nonce" src="https://user-images.githubusercontent.com/3273790/66283980-58271300-e8f8-11e9-9563-d3c0198e5a9f.png">

#### App Version / OS version
wordpress.com 4.3.0 release
Windows 10

**Comment by designsimply** [comment]
I did a quick test using the WordPress.com desktop app version 4.4.2 on Windows 10 with a Jetpack site running WP 5.2.4 and Jetpack 7.8 as well as with a WP.com site and found that I was able to create and save drafts. I tested creating new drafts both the classic editor and the block editor—when I tested with the block editor it prompted me to log in again (https://github.com/Automattic/wp-desktop/issues/582) but saving the draft works for me after that. I never saw the "Expired nonce" message shown in your screenshot during my testing.

I must be missing something in my testing steps or my testing setup must be different compared to yours. Can you tell me a little bit more about what type of site you tested? Are you using Jetpack version 7.8 with WordPress version 5.2.4 on your site? If you log out and close the app then re-open the app and log back in then click the "Create New Post" button in the top toolbar again, does the "Expired nonce" message go away? If that doesn't help, can you try deleting the app and reinstalling the latest version (as of this writing the latest version is 4.4.2) which was just released?

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
