### ISSUE TITLE
Login does not allow pasting password from password manager

### ISSUE THREAD

**Issue by amitbapat** [Automattic/wp-desktop#679]
#### Steps to reproduce
1. Install Windows desktop app
2. Open app
3. Enter user name
4. Switch to  password manager
5. Copy password
6. Cannot paste password in the password field

#### What I expected
Please allow pasting password from keyboard (Ctrl-V).

#### What happened instead
Password field does not allow pasting password copied from password manager.

#### App Version / OS version
Windows, 4.3.0

**Comment by designsimply** [comment]
I tested today with WPDesktop 4.4.2 on Windows 10 and found that I was able to paste a password copied from elsewhere into the password field.

@amitbapat is it possible you thought the password was copied when it wasn't? Could you try pasting the password into a text file (without saving) to verify the copy command is working correctly and then try pasting it into the password field again? Can you also try upgrading to the latest version (4.4.2 was released recently) of the WPDesktop software from https://apps.wordpress.com/desktop/ to see if that makes a difference for you?

**Comment by amitbapat** [comment]
I tried to reproduce this again today and I could not. It's possible that my computer or keyboard had some weird issue and it went away after the reboot.
