### ISSUE TITLE
Windows: On first launch app window is taller than viewport

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-desktop#68]
On a fresh launch of the app on Windows, the app window is taller than the viewport, with the top edge of the app against the top of the screen, and the bottom edge of the app, and in some cases in-app information, appearing behind the taskbar.

![desktop](https://cloud.githubusercontent.com/assets/11873759/12852332/14c5bf30-cc37-11e5-94f4-5bb2a5828dd2.PNG)

To resize it is necessary to resize from the top, and then drag the app window up, as the bottom edge cannot be clicked while behind the taskbar to resize.

If the app is closed and reopened while still in the system tray it remembers the resized settings, but if the app is quit completely and restarted, the problem again occurs.

I've confirmed this behaviour in version 1.2.5 on Windows 7 and 8.1, and on different screen sizes. Changing the screen resolution on a specific screen does not change this behaviour.

**Comment by madLyfe** [comment]
ya the app doesnt remember sizing from when it was closed. it does remember its position though, on whatever of my monitors i placed it on before closing.

**Comment by rachelsquirrel** [comment]
Also reported in #3198817-t. The user reports the status line at the bottom of the app is partly hidden by the task bar.

**Comment by KokkieH** [comment]
This is still happening in v. 3.6.0

**Comment by nsakaimbo** [comment]
Unable to reproduce on Windows 10 with a more recent release (v5.0.0-beta2). Closing this issue but please feel free to re-open if this bug is encountered with newer releases of the application.
