### ISSUE TITLE
Themes: Can't dismiss modal after activating a new theme

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#680]
#### Steps to reproduce
1. Go to My Site(s).
2. Open the Themes section.
3. Select and activate a theme.
4. When the "Thanks" modal appears, click outside the modal to try to dismiss it.

#### What I expected

I expected the modal to be dismissed so I could go straight back to the Themes page. (This is the behavior on the web.)

#### What happened instead

The modal was not dismissed. I had to select one of the modal buttons and then navigate back to the Themes page from there.

#### App Version / OS version
WPDesktop 4.4.1 beta / macOS 10.15

#### Screenshot / Video
![Screenshot 2019-10-22 11 20 32](https://user-images.githubusercontent.com/8658164/67277120-0668b600-f4be-11e9-8ca0-da442dfb59d0.png)

#### Context / Source
#manual-testing

**Comment by designsimply** [comment]
I tested with 4.5.0-beta1 today using a few different sites and couldn't replicate—I was able to dismiss the Thanks notice after activating a theme by clicking anywhere outside the modal. ([38s](https://cloudup.com/cCXJ4vICUGB))

**Comment by rachelmcr** [comment]
I also confirmed that this is now working for me as of 4.5.0-beta1. Closing as resolved.
