### ISSUE TITLE
Ensure compatibility with Node 12

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-desktop#686]
Node 12 is the current LTS version and wp-calypso will be looking to migrate soon. The desktop may require some changes and upgrades to ensure it can handle the version change.

See https://github.com/Automattic/wp-calypso/pull/37031#issuecomment-545987889

In tests there, electron-spellchecker didn't seem to build properly.

**Comment by nsakaimbo** [comment]
This issue has been addressed - wp-desktop is now building with latest Calypso on Node 12.
