### ISSUE TITLE
Customer Home: Support illustration is stretched vertically

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#689]
#### Steps to reproduce
1. Log in to the app.
2. Go to My Sites > My Home (for a site with the customer home).

#### What I expected

I expected each card to look the same as it does on the web.

#### What happened instead

In the Support card, the illustration is stretched vertically. I noticed that if I remove this CSS style the image is sized with its original proportions:

```
img {
    height: auto;
}
```

#### App Version / OS version

WPDesktop 4.5.0-beta1 / macOS 10.15

#### Screenshot / Video

![Screenshot 2019-10-25 17 11 23](https://user-images.githubusercontent.com/8658164/67587060-f3b6e100-f74a-11e9-9522-c8e6acd6b6ed.png)

#### Context / Source
#beta-testing

cc @Automattic/explorers

**Comment by davemart-in** [comment]
Thanks for the heads up @rachelmcr! I'll get this fixed. 👍

**Comment by rachelmcr** [comment]
@loremattei heads up about this fix (for v4.5.0).
