### ISSUE TITLE
Sharing: Publicize connection created even if permission denied, and Cookies Required error when trying to connect Facebook

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-desktop#69]
Reported via [Twitter](https://twitter.com/user/status/695926633736306688)

When making a new Publicize connection an Electron pop-up window appears asking for login information. For Facebook specifically, if login info is entered, the following warning appears:

<img width="1076" alt="facebook_and_sharing_ _kokkiestrialtestsite_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/12867054/82e1467e-cceb-11e5-93c7-fbb11faaa08b.png">

Other services I tested connect normally when login credentials are entered.

With Facebook, clicking the Cancel button also has no effect, and closing the window automatically initiates a connection even if no login credentials were entered (I am, however, logged into Facebook in a browser on this computer):

![publicize fb](https://cloud.githubusercontent.com/assets/11873759/12867098/381c6f22-cced-11e5-89ec-19b9a9659252.gif)

On closing the pop-up a connection is also created even if permission was explicitly denied inside the pop-up. This last behaviour occurred with Facebook, Twitter, Google+ and Tumblr, but not LinkedIn:

![publicize tumblr](https://cloud.githubusercontent.com/assets/11873759/12867081/63405c28-ccec-11e5-8673-7d27b6b806ff.gif)

This behaviour occurs in both Windows and Mac versions of the app.

**Comment by KokkieH** [comment]
I'm still able to replicate this, except for the cookie warning. And the appearance of the login window has changed a bit - it no longer shows a cancel button, for example, but closing the window without logging in still results in a Facebook connection being created.

**Comment by rachelmcr** [comment]
@KokkieH I tested and I _think_ the remaining issues also occur in Calypso web, not specifically in the desktop app. Could you confirm when you get a chance? If so, we can move this report to Calypso for investigation.

**Comment by KokkieH** [comment]
It looks like you may be right. Even on the web, clicking Cancel on the initial oAuth window doesn't actually cancel the flow - either cancelling or completely closing the oAuth window simply continues the process, taking me to a 2FA prompt (as I have access to the Automattic Facebook Business app), and then asking me to select the page I want to post to.

However, it no longer appears to create a connection if I don't select a specific page in my account. Tried with Tumblr as well, with the same result.

I want to test this more thoroughly to make sure, though. Will do that when I'm home next week and update here.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
