### ISSUE TITLE
Bug: Harfbuzz version

### ISSUE THREAD

**Issue by npmaling** [Automattic/wp-desktop#692]
What I expected: to run WordPress Desktop version 4.4.2 on Fedora 31 new install

Steps to reproduce: it wouldn't start from file manager so ran it from command line and got the following error message:

(wpcom:5347): Pango-ERROR **: 16:52:16.420: Harfbuzz version too old (1.4.2)

Harfbuzz is installed somewhere on my machine ....

**Comment by rachelmcr** [comment]
Thanks for the report! As discussed in https://github.com/electron/electron/issues/20348 this is an issue with the app using an old version of Electron.

We've been working on updating Electron (see https://github.com/Automattic/wp-desktop/issues/588) which should resolve this issue once it's done.

**Comment by w73pa** [comment]
Same issue on OpenSuse Tumbleweed, rendering the desktop client entirely defunct with current versions of wpcom and tumbleweed.

**Comment by nsakaimbo** [comment]
Closing as the version of Electron in the app has been updated since this issue was reported. For future reference, please try v5.0.0 of the app or higher if you encounter this bug.
