### ISSUE TITLE
desktop app 

### ISSUE THREAD

**Issue by evileonline** [Automattic/wp-desktop#699]
After opening the wordpress software, the following appears
“You need to set `oauth_client_id` in your config file.”
Previously submitted such a solution was to solve the web software. The link is as follows
“https://github.com/Automattic/wp-calypso/pull/26148”
How to solve desktop software problems
Thank you！

**Comment by rachelmcr** [comment]
Thanks for the report! I see this was also reported in https://github.com/Automattic/wp-desktop/issues/700 — I'm going to close this issue and we'll continue tracking it there.
