### ISSUE TITLE
Reconnect, doesn't appear to be a way to.

### ISSUE THREAD

**Issue by kimaldis** [Automattic/wp-desktop#70]
I disconnect a site, www.kim-aldis.co.uk, and now I can't find a way to reconnect it. Is there a way?

**Comment by lancewillett** [comment]
Hi kimaldis — here are instructions to help you.

1. Go the Jetpack menu in your dashboard.
2. Click on "My Jetpack" at the top of the page.
3. Click on "Disconnect Site from WordPress.com" if your site is currently connected to WordPress.com.
4. Confirm the disconnection.
5. Click on the Connect button to connect your site to WordPress.com again.

If that doesn't fix it, you can contact us directly via [this contact form](http://jetpack.me/contact-support/) and we'll look into your Jetpack settings and fix things for you!
