### ISSUE TITLE
Login: Requesting a 2FA code via text message fails

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#701]
#### Steps to reproduce
1. Start with a WordPress.com account that has 2FA (not an a8c account).
2. On the app login screen, enter your username and password.
3. When it asks for your 2FA code, select the option to request a code via text message.

#### What I expected

I expected to get a text message with a 2FA code.

#### What happened instead

The app shows this error:

> Please enter your credentials.

The console shows a network request to `http://127.0.0.1:41050/sms` that fails with a 400 error.

#### App Version / OS version

WPDesktop 4.6.0-beta1 / macOS 10.15

#### Screenshot / Video

![screen-shot-2019-11-11-at-8 08 32-pm](https://user-images.githubusercontent.com/8658164/68672902-837dcd00-054a-11ea-8ec6-6b0820ca65d7.png)

#### Context / Source
Found in beta testing (h/t @AmandaRiu for the report)

**Comment by rachelmcr** [comment]
@sgomes Is it possible this is related to the changes you made in https://github.com/Automattic/wp-calypso/pull/34809?

**Comment by sgomes** [comment]
> @sgomes Is it possible this is related to the changes you made in [Automattic/wp-calypso#34809](https://github.com/Automattic/wp-calypso/pull/34809)?

Yes, it's certainly possible. I'll see if I can reproduce the issue.

**Comment by sgomes** [comment]
@rachelmcr I was able to reproduce the issue. It could be related to that PR, but I'm not entirely sure.

@mmtr Hey! 👋This is making a request to `http://127.0.0.1:41050/sms`, which fails with "Please enter your credentials.". 

Is it expected that this is making a request to `localhost`? If so, what type of request should it be? The `fetch` code I wrote does a `POST` request with the username and password in a `JSON` body, which I believe is the same thing that `superagent` was doing before Automattic/wp-calypso#34809.

**Comment by mmtr** [comment]
> Is it expected that this is making a request to `localhost`?

Yeah, the Calypso server bundled in the desktop app runs in `127.0.0.1`, so that request is expected.

> what type of request should it be? 

I'm not totally sure but but I'd say this should be an `application/json` request: https://github.com/Automattic/wp-calypso/blob/c6f5c2a6334ba0aeba8de104330896eb20e4f58a/server/api/oauth.js#L90-L110

>  I believe is the same thing that `superagent` was doing before

I'm not familiar with `superagent` but maybe it uses `application/json` as the default type for requests?

**Comment by sgomes** [comment]
Thanks, @mmtr, I'll check if adding a `content-type` header to the request helps! 👍

**Comment by sgomes** [comment]
@mmtr I'm having trouble building the desktop app; I get a runtime error on boot regarding some ES6 syntax (`...`).

Could you try the fix yourself instead? It should be sufficient to add the following to the object on line 43 of `client/auth/auth-code-button.jsx`:

```js
headers: { 'Content-Type': 'application/json' },
```

**Comment by nsakaimbo** [comment]
@sgomes You should be able to build the desktop app locally now as we've had a couple of PRs land to fix build issues (#706 and #708).

**Comment by sgomes** [comment]
@nsakaimbo I'm afraid I'm still getting that JS error message on boot, despite having nuked my local copy of the repo and rebuilt everything from scratch, with master `wp-desktop` and master `wp-calypso`. Any ideas?

**Comment by nsakaimbo** [comment]
@sgomes Have you tried building from `develop`, and not `master`? Also, worth bearing in mind to use the SHA for Calypso that's currently in develop (we had to revert using from the latest Calypso because something in Calypso is causing the JS error). So when you check out `develop`, make sure to `git submodule update --init`.

**Comment by sgomes** [comment]
Thanks @nsakaimbo! This appears to do the trick. 👍 

I was able to test my proposed fix and it appears to work. Opening a PR on the Calypso side of things.
