### ISSUE TITLE
MacBook Air Wordpress

### ISSUE THREAD

**Issue by Joeyc19** [Automattic/wp-desktop#710]
So my Wordpress app started working last week when I got the laptop and now its kicked me out of the app leaving me with a message saying that I need to set 'oauth_client_id' in your config_file.

Please can someone advise how to sort this please?

#### Steps to reproduce
1.
2.
3.
4.

**Comment by rachelmcr** [comment]
Thank you for the report! We had another report in https://github.com/Automattic/wp-desktop/issues/700 and are tracking the issue there, so I'm going to close this issue.

Could you check what version of the app you have installed? (You can find it in the WordPress.com menu > About WordPress.com.) Also, do you recall if this started happening right after an update to the app or not?

**Comment by rachelmcr** [comment]
We also just released version 4.6.0 — please let us know if the problem continues after that.
