### ISSUE TITLE
GPL? Seriously?

### ISSUE THREAD

**Issue by sheafferusa** [Automattic/wp-desktop#72]
Hi everyone!

Well I have to admit that I didn't expect a client side software from WordPress under the GPL license. This license is as such great for the server based code of WordPress, but for a desktop client it goes too far, to discourage its commercial usage such as using the client as part of an existing proprietary project. On the server side, wordpress can be used as a part of a proprietary software without gaving been forced to release the proprietary source code as Open Source. But, at the client side, a GPL means no linking with a proprietary software is allowed if a customer/developer  doesn't want to release all of his hard earned intellectual property rights etc as Open Source under GPL. This doesn't sound one with the wordpress 's desire to become the default software for everything over the web. 
Again, the shell used for the desktop client here is also under a permissive license, which turns out to be a big reason that so many developers and companies adopted it for their own client side applications on the desktop. The electron shell doesn't interfere with the intellectual property rights of most if not all the developers and users who have chosen to embrace it. 
That's what I expected from the WordPress Client for Desktop, but for some reason it didn't happen. That makes me sad and I bet there would be many who would have to abandon the client entirely, just for the single reason that it's not under a permissive license. 

Is there a chance that the license be re-considered and probably switched to a permissive one? I hope so. 

Thanks & Regards!

**Comment by mkaz** [comment]
We do not have plans of switching the license for the Desktop client.
It is licensed under the GPL like WordPress itself.
