### ISSUE TITLE
Update for Mac does not (never has) worked

### ISSUE THREAD

**Issue by tecumsa** [Automattic/wp-desktop#720]
I really hate the WP app for Mac. The Update and Restart has never worked, and trying to find the update on the website is harder than kissing a porcupine. Why do you make things so difficult? Why not provide a link directly to the update download, fix the update procedure to work like every other non-AppStore app in the world, or provide the app through the AppStore?

#### Steps to reproduce
1. Wait for a announce update
2. Open the app and click on Update and Restart
3. App closes, nothing happens
4. Repeat ad infinitum

#### What I expected

Uh, for the update to be downloaded, installed, and the app restarted?

#### What happened instead

App closed, nothing else happened.

#### App Version / OS version

4.6.0 / 10.13.6

**Comment by rachelmcr** [comment]
I'm sorry for the trouble you've had with the updater! We're currently tracking this in https://github.com/Automattic/wp-desktop/issues/250, so I'm going to close this issue.

If you're interested, you can see our findings for why this is happening in https://github.com/Automattic/wp-desktop/issues/250#issuecomment-466988421. Unfortunately fixing this relies on various other updates to the app that we're still working on, so we don't have an immediate fix for it.

In the meantime, the updater _should_ work on macOS if you wait a bit between seeing the prompt to update and selecting the update. The update downloads in the background during that time and it should prevent the failure that's happening now. Alternately, you can download each new update at https://apps.wordpress.com/desktop/ or from the Releases section here on GitHub: https://github.com/Automattic/wp-desktop/releases
