### ISSUE TITLE
Empty screen when the WP.com App token is revoked

### ISSUE THREAD

**Issue by xknown** [Automattic/wp-desktop#723]
If for some reason, the oauth2 token is revoked for the WordPress.com Desktop App, only a white page is shown along with a link to reload the current page. After clicking on this link, the same page is shown.

#### Steps to reproduce
1. Log in to the WP.com Desktop App
2. Log in with the same account on a normal browser, and navigate to `https://wordpress.com/me/security/connected-applications`. Click the disconnect button.
3. Quit the WP.com Desktop App
4. Re-open the WP.com Desktop App.

#### What I expected
The WP.com App should likely detect the logged out/unauthorized state. I guess this is also a problem in Calypso.

#### What happened instead
An empty page is shown along with a JS error in the browser console.

#### App Version / OS version
Version: 4.6.0 (MacOS 10.13)

#### Screenshot / Video
<img width="1440" alt="Screen Shot 2019-12-16 at 12 41 11" src="https://user-images.githubusercontent.com/1081870/70904798-9a5c8700-2002-11ea-809f-bec0b3183e95.png">

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
