### ISSUE TITLE
Customizer Won't Load on Mac

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-desktop#735]
#### Steps to reproduce
1. Log into WordPress.com app
2. Access a site and go to Design > Customize

#### What I expected
I expected Customizer to load

#### What happened instead
I get an error that the customizing tools did not load correctly:

![customizer](https://d.pr/i/4EZn5o+)
*Full link: https://d.pr/i/4EZn5o*

#### App Version / OS version
App version 4.6.0
Mac OS 10.15.2 (Catalina)

#### Context / Source
User reported in 2604139-zen and I was able to replicate it.

We'd also love to know how you found the bug: #user-report

**Comment by rachelmcr** [comment]
Thanks for the report! This issue is being tracked in https://github.com/Automattic/wp-desktop/issues/504.
