### ISSUE TITLE
Plans: Google analytics not available with a Premium plan

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-desktop#740]
Reported on #2626652-zen . The Google Analytics integration has been made available to Premium customers recently, this however is not the case when they try via app.

#### Steps to reproduce
1. Have a Premium plan
2. Go to WordPress.com > Your Site > Marketing > Traffic
3. See how the option is available via browser, but prompts to upgrade to Business via app: 

> "Google Analytics: Connect your site to Google Analytics in seconds with the Business plan
> Add your unique tracking ID to monitor your site's performance in Google Analytics."

![ga_issue](https://user-images.githubusercontent.com/3812076/72319909-cd6a6700-36e3-11ea-8b6c-a2101e0a2e87.png)

**Comment by rachelmcr** [comment]
Thanks for the report! I confirmed that Google Analytics is available for Premium plan sites in the 4.7.0-beta1 release (the Calypso change must have just missed the cut for 4.6.0, the current production version). This will be available to users once we release 4.7.0 to production.
