### ISSUE TITLE
Signup: White screen after switching from login with 2FA to signup flow

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#746]
If you start logging in to an account with 2FA, and then switch to the signup flow, you end up on a white screen. (This seems like an uncommon scenario.)

I confirmed that you _can_ switch to the signup flow in a web browser at this point, so this seems specific to desktop login->signup.

#### Steps to reproduce
1. Start logged out of the app.
2. Using an account with 2FA, enter your username and password.
3. When the app prompts you to enter a 2FA code, select "Create Account" instead to switch to the signup flow.

#### What I expected

I expected to begin the signup flow.

#### What happened instead

I ended up on a white screen with the following console errors:

```

:41050/oauth Failed to load resource: the server responded with a status of 400 (Bad Request)
245.js:2 TypeError: Cannot read property 'focus' of null
    at :41050/calypso/fallback/auth.js:1
    at Si (245.js:2)
    at Vi (245.js:2)
    at Xi (245.js:2)
    at ik (245.js:2)
    at exports.unstable_runWithPriority (245.js:2)
    at fg (245.js:2)
    at Yj (245.js:2)
    at Lj (245.js:2)
    at 245.js:2
Pi @ 245.js:2
:41050/calypso/fallback/auth.js:1 Uncaught (in promise) TypeError: Cannot read property 'focus' of null
    at :41050/calypso/fallback/auth.js:1
    at Si (245.js:2)
    at Vi (245.js:2)
    at Xi (245.js:2)
    at ik (245.js:2)
    at exports.unstable_runWithPriority (245.js:2)
    at fg (245.js:2)
    at Yj (245.js:2)
    at Lj (245.js:2)
    at 245.js:2
```

#### App Version / OS version

WPDesktop 4.7.0-beta1 / macOS 10.15.2

#### Screenshot / Video

![Screenshot 2020-01-17 17 12 06](https://user-images.githubusercontent.com/8658164/72632047-5a642900-394d-11ea-98cd-965e7c9eda12.png)

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
@nsakaimbo I confirmed that this isn't a new issue. Prior to v4.5.0 the blank screen was blue instead of white, but this issue exists at least as far back as v3.4.0 (that's the earliest I've tested this issue, but it may have existed from the beginning). It's a very unlikely flow for someone to try and given that no one has reported the issue before it seems very low priority to me.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
