### ISSUE TITLE
Signup: Email confirmation isn't fully detected/site can't be launched until app is relaunched

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#747]
I can't confirm my email address using the desktop app (the email confirmation link directs me to a web browser). If I leave the app open while I do that, though, the app doesn't fully detect that I have confirmed my email address until the app is relaunched.

#### Steps to reproduce
1. In the app, create a new account or log in to an account with an unconfirmed email address.
2. Notice that the "Site Setup List" (under My Site > My Home) shows an email validation step.
3. In a web browser, check your email and confirm your email address for WordPress.com.
4. In the app again, notice that the email validation step is completed (it says "You validated your email address").

#### What I expected

I expected the app to detect that my email address is now confirmed, and enable all actions that depend on email confirmation.

#### What happened instead

The "Launch your site" step is still disabled and shows a notice "Confirm your email address before launching your site."

After the app is relaunched, the option to launch your site works as expected.

#### App Version / OS version

WPDesktop 4.7.0-beta1 / macOS 10.15.2

#### Screenshot / Video

Before relaunching the app:
![Screenshot 2020-01-20 16 18 08](https://user-images.githubusercontent.com/8658164/72742348-706a2780-3ba1-11ea-9693-565efd7738ac.png)

After relaunching the app:
![Screenshot 2020-01-20 16 28 10](https://user-images.githubusercontent.com/8658164/72742575-ebcbd900-3ba1-11ea-88ca-583cbba9136a.png)

#### Context / Source
#manual-testing

**Comment by designsimply** [comment]
Tested and confirmed this is still happening in WPDesktop 5.1.0-beta1 on macOS 10.14.6.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
