### ISSUE TITLE
Error message on opening Wordpress app for Mac Desktop.

### ISSUE THREAD

**Issue by Dogloverfriend** [Automattic/wp-desktop#774]
Up until yesterday I had no problems using the Wordpress app for Mac desktop. Halfway through using it logged me out and when I tried to log back in it came up with error message: 
"You need to set `oauth_client_id` in your config file."

I tried reinstalling the most uptodate app but still got the error message. Please help.

Look forward to hearing from you.
Many thanks.

#### Steps to reproduce
1.
2.
3.
4.

#### What I expected
To open app and use it.

#### What happened instead
Got error message: "You need to set `oauth_client_id` in your config file."

#### App Version / OS version
WP.com: Version 4.7.0
Mac: OS High Sierra 10.13.6

#### Screenshot / Video

![Screen Shot 2020-02-18 at 11 25 59](https://user-images.githubusercontent.com/61189213/74733026-617ba100-5243-11ea-92a2-55b765544fac.png)

**Comment by nsakaimbo** [comment]
Hi, there - thanks for reporting this, @Dogloverfriend! Closing this as it seems identical to an existing issue reported in #700 (will add your comments there). 

Could you try quitting the application, deleting your Application Data contents and re-starting, per the instructions mentioned in [this comment](https://github.com/Automattic/wp-desktop/issues/700#issuecomment-557552341)? We're still trying to troubleshoot this issue, but please let us know if this helps in the mean time.

**Comment by Dogloverfriend** [comment]
Thank you for your reply.

I have followed your instructions below and there was no application data for Wordpress.

I look forward to hearing from you soon.

Kind regards

On 18 Feb 2020, at 15:19, Nicholas Sakaimbo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, there - thanks for reporting this, @Dogloverfriend<https://github.com/Dogloverfriend>! Closing this as it seems identical to an existing issue reported in #700<https://github.com/Automattic/wp-desktop/issues/700> (will add your comments there).

Could you try quitting the application, deleting your Application Data contents and re-starting, per the instructions mentioned in this comment<https://github.com/Automattic/wp-desktop/issues/700#issuecomment-557552341>? We're still trying to troubleshoot this issue, but please let us know if this helps in the mean time.
