### ISSUE TITLE
Windows: User Stuck on "Oh hai"/"We're Hiring" Splash

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-desktop#783]
A user on Windows said they were not able to get past the "oh hai/we're hiring" splash page.

#### Steps to reproduce

We have not been able to reproduce this issue, but the user states:

> I have closed the app repeatedly, but have had no success in removing the ad

#### App Version / OS version

Unclear what app version, and what OS version, the user is on.

#### Screenshot / Video

![win-oh-hai-splash](https://user-images.githubusercontent.com/8979548/75169411-81550e00-56f6-11ea-93c9-e8da76107f5b.png)

#### Context / Source

2726184-zen

**Comment by fresatomica** [comment]
Another user mentioned this on [the forums](https://en.forums.wordpress.com/topic/fancy-a-job-page/).

They saw the _Fancy a job?_ page after clicking on _My Site_. The address on the bar indicated http://127.0.0.1:41050/desktop/hey.html.

Their setup: 

> Windows 10 version 1909 (installed 12/7/2019), and the download I installed (2/26/2020) was wordpress.com-win32-setup-5.0.0.exe

Since March 1st they are not experiencing the issue anymore.

**Comment by nsakaimbo** [comment]
@fresatomica Thank you for the additional information! This will be useful in trying to reproduce the issue on our end.

**Comment by fresatomica** [comment]
The user came back as they started seeing this page again, it seems to be redirecting them to https://automattic.com/work-with-us/

**Comment by macmanx2** [comment]
A few more helpful bits:

> The issue does not occur when I open https://glrecords.org directly, then click My Site.

> It occurs only when I open the desktop app. The app comes up displaying the web page (preseumably the location at last close). When I click < to progress back to My Site, then the “Fancy a Job?” page appears. As noted on the development page linked 3 posts earlier, the Fancy page blocks access to My Site. (To get to My Site, I have to first directly open the web page.)

**Comment by supernovia** [comment]
We've got another case here: https://wordpress.com/forums/topic/wordpress-com-installation-problem/

The file certainly is ours, just a hiring prompt. It's just that folks are having trouble getting it to go away.

@johngodley can you take a look?

**Comment by johngodley** [comment]
@supernovia I haven't been involved here for 3 years now, so I don't think I'm best placed. Looking at recent changes maybe @nsakaimbo can take a look?

**Comment by sarahfg** [comment]
We got another report in the mobile queue #2866534-zen

**Comment by fresatomica** [comment]
Another report: https://wordpress.com/forums/topic/wp-desktop-and-the-oh-hai-curse/

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
