### ISSUE TITLE
Add New Post shows the blank loading screen in desktop app and instead opens Add New Post in browser

### ISSUE THREAD

**Issue by jcrowson** [Automattic/wp-desktop#827]
#### Steps to reproduce
1. Click on Site
2. Click posts
3. Click "Add New Post" button

#### What I expected
To see a blank new post screen inside of the desktop app, with the Gutenberg editor enabled.

#### What happened instead
The desktop app shows a blank loading screen and a new tab opens up in my browser showing the Add New Post page for my site.

#### App Version / OS version
v 5.0.1-beta2

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/557114/78255579-5c229f00-74ef-11ea-83d6-440699417edf.png)

#### Context / Source
I found this issue by simply using the desktop app for what it's intended for: writing posts. I've uninstalled the app several times, tried the stable and beta branch, and logged out and in again.

One thing I've noticed is that if I switch back to the classic editor, then it works.

**Comment by nsakaimbo** [comment]
Thanks for the report, @jcrowson! This sounds like an existing issue we're currently tracking in #759. We have observed this appears to be related to toggling between the Classic and Block editors, and your report is super helpful in confirming this.

I'll be closing this issue so we can continue tracking this in #759.
