### ISSUE TITLE
Notification badge and bounce don't work if the app is minimized or completely hidden behind other apps

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#835]
Steps to reproduce:

1. Log in to the WPDesktop app and go to WordPress.com > Preferences.
1. Make sure both Notifications options are checked (badge and bounce) and close preferences.
1. Minimize the app.
1. Trigger any notification for the user logged in to the WPDesktop app from elsewhere.
1. Wait for an app icon badge and bounce indicating a notification has been received.
1. Repeat the steps except put the app in the background (completely hidden behind other windows) in step 3.
1. Repeat the steps except leave the app active and focused (be on any screen except notifications) in step 3.

**Result:** if the app is minimized or behind other windows, the app icon doesn't get a badge and doesn't bounce to indicate a new notification has been received (screenshot).

**Note:** after the app is un-minimized or brought back to the foreground, it takes around 20 to 30 seconds for the badge to appear on the app icon in the macOS dock and the bounce never does get triggered in those cases.

<img width="202" alt="Screen Shot 2020-04-07 at Apr 7 6 19 43 PM" src="https://user-images.githubusercontent.com/1119271/78731677-992acf00-78fd-11ea-8075-796044393258.png">
<p style="clear:both;"><sup>Tested with WPDesktop 5.0.0.1-beta2 on macOS 10.14.6.</sup></p>

**Comment by nsakaimbo** [comment]
Notification badge behavior has been fixed as of 6.1.0-beta2 ([link](https://github.com/Automattic/wp-calypso/releases/tag/v6.1.0-beta2)) - closing.
