### ISSUE TITLE
Link to instructions to install Jetpack lead to a purchase prompt instead of instructions to install Jetpack

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#837]
Steps to reproduce:

1. Log out.
1. Click "Add self-hosted site".
1. Click "Please follow these instructions to install Jetpack."

**Result:** clicking on the link for instructions to install Jetpack leads to  https://wordpress.com/jetpack/connect/store ([screenshot](https://user-images.githubusercontent.com/1119271/78732506-08092780-7900-11ea-907e-9c9ebf147b72.png)) which could be quite confusing if you are actually looking for instructions to install Jetpack. 

Could we link to https://jetpack.com/support/getting-started-with-jetpack/ instead?

<img width="1280" alt="Screen Shot 2020-04-07 at Apr 7 5 56 58 PM" src="https://user-images.githubusercontent.com/1119271/78732430-d85a1f80-78ff-11ea-9573-4e8269a0c7de.png">
<p style="clear:both;"><sup>Tested with WPDesktop 5.0.0.1-beta2 on macOS 10.14.6.</sup></p>

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
