### ISSUE TITLE
Site Setup List: "Confirm your email address" step doesn't move to the completed section automatically

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#852]
Steps to reproduce:

1. Sign up for a new account using the WPDesktop app.
1. Follow the Site Setup List steps until you reach the "Confirm your email address" step.
1. Open the "Activate" email.
1. Click the "Confirm Now" button.
1. Log in to your account.
1. Close the browser window.
1. Go back to the WPDesktop app and notice the "Confirm your email address" is still incomplete.
1. Go to Stats.
1. Go back to My Home.
1. Observe that the "Confirm your email address" is now complete.

**Result:** the "Confirm your email address" step does not automatically move to the Completed section after opening the "Activate" email and tapping the "Confirm Now" button. ([59s](https://cloudup.com/cKyzr-IOb9Z))

The step should move to the completed section as soon as possible because it blocks you from completing other steps in the list otherwise.

![confirm-your-email-address-incomplete](https://user-images.githubusercontent.com/1119271/79826496-1ec86900-8359-11ea-9d71-d828e6147cf6.png)
<p style="clear:both;"><sup>Tested with WPDesktop 5.1.0-beta1 on macOS 10.14.6.</sup></p>

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
