### ISSUE TITLE
Customize: Customizer opens in web browser with no warning on Jetpack sites

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#865]
#### Steps to reproduce

1. Log in to the app.
2. Open the My Sites section.
3. Switch to a Jetpack site (self-hosted or Atomic).
4. In the sidebar, go to Design > Customize.

Optional: On an Atomic site, go to My Home > Quick Links > Edit menus or Customize theme.

#### What I expected

I expected the customizer to open in the app OR to have an icon indicating that the link would be opened externally (the square with an arrow coming out of it).

#### What happened instead

The customizer opened in the browser instead of the app, with no warning.

#### App Version / OS version

WPDesktop 5.1.0-beta1 / macOS 10.15.4

#### Screenshot / Video

![Screenshot 2020-04-24 13 53 11](https://user-images.githubusercontent.com/8658164/80214626-14e18700-8633-11ea-8c38-90c16a93aa9b.png)

#### Context / Source
#beta-testing

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
