### ISSUE TITLE
Editor: Switch to classic editor sometimes silently fails.

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#866]
#### Steps to reproduce
1. Start a new post.
2. Add a featured image to the post.
3. Go to the ellipsis menu and select "Switch to Classic Editor." Notice that nothing happens.
4. Click the "W" in the top left to close the editor.
5. Select "OK" to confirm on the "You have unsaved changes" dialog.
6. Start a new post again.
7. Add some post content (title and/or body of the post).
8. Go to the ellipsis menu and select "Switch to Classic Editor." Notice that nothing happens.
9. Click the "Save Draft" prompt at the top of the editor.
10. Go to the ellipsis menu and select "Switch to Classic Editor." Notice that now it switches to the classic editor.

#### What I expected

I expected that any time I select "Switch to Classic Editor" it would either switch or display a clear error message (such as the "You have unsaved changes" dialog).

Here's what I see when I take similar steps in the web editor:

![Screenshot 2020-04-24 15 32 01](https://user-images.githubusercontent.com/8658164/80224517-b374e480-8641-11ea-8ca1-f3cc75fd84cd.png)

#### What happened instead

It silently fails when there are unsaved changes on the post. I noticed that in some cases even clicking "Save Draft" wasn't sufficient to resolve this.

#### App Version / OS version

WPDesktop 5.1.0-beta1 / macOS 10.15.4

#### Screenshot / Video

![Screenshot 2020-04-24 15 32 40](https://user-images.githubusercontent.com/8658164/80224623-d99a8480-8641-11ea-8472-73a297ec8bb0.png)

#### Context / Source
#beta-testing

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
