### ISSUE TITLE
Customer Home: Quick Links don't always appear

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#877]
I'm not sure of exact steps to reproduce, because the Quick Links section appears on some of my tests but not others. I don't yet see a clear pattern.

#### Steps to reproduce
1. Log in to the app.
2. Open the My Sites section.
3. Confirm the "My Home" section opens and you have completed the "Site Setup List" for the site.

#### What I expected

I expect a Quick Links section to always load in the customer home. Example of a site where it loads:

![Screenshot 2020-05-12 13 03 04](https://user-images.githubusercontent.com/8658164/81687424-efd17e80-9450-11ea-912c-0effa02d7d00.png)

#### What happened instead

The Quick Links section doesn't always load. Example of a site where it doesn't load:

![Screenshot 2020-05-12 13 03 09](https://user-images.githubusercontent.com/8658164/81687493-f9f37d00-9450-11ea-9b73-d6364cc1052e.png)

Calypso web has a different Customer Home layout now, but even on this site on the web the Quick Links section loads:

![Screenshot 2020-05-12 13 04 15](https://user-images.githubusercontent.com/8658164/81687774-1f808680-9451-11ea-9094-41fe1d8bd1f9.png)

#### App Version / OS version

WPDesktop 5.1.1-beta1 / macOS 10.15.4

#### Context / Source
#beta-testing

**Comment by rachelmcr** [comment]
Just a note that I see inconsistent behavior on existing sites on an existing account, but I consistently see the issue after signing up for a new account/site and completing the site setup list on the new site.

**Comment by fstath** [comment]
A user in the WordPress.com forums reported this when they updated to the latest stable version (5.1.0).

Forum thread: https://wordpress.com/forums/topic/desktop-version-5-1-0-home-screen/

I was also able to replicate it on my end when I installed the same version.
App version: 5.1.0 (stable)
OS version: macOS 10.15.4

**Comment by rachelmcr** [comment]
Thanks for the report, @fstath! I did some additional testing around this and discovered that I can make the Quick Links section appear in the desktop app for a given site:

* Notice that the web screenshot above has a "Look more professional" card near the top of the My Home page. I noticed that the sites where the Quick Links section appears don't have that card.
* For a site where I was missing Quick Links in the desktop app, I went to the web and dismissed that card.
* Now, in the desktop app, I'm seeing the Quick Links section!

I'd suggest that as a possible workaround for anyone running into this issue.

cc @Automattic/serenity

**Comment by gwwar** [comment]
When's the next desktop update @rachelmcr? I suppose the API response was updated and desktop has an older snapshot of Calypso

**Comment by kwight** [comment]
Ah yes, this is as @gwwar said, a case of an older Calypso build attempting to display updated API results. This will "fix itself" when the next release uses a newer build (not to say it isn't a problem, just that no bug fix is required in Calypso nor. Desktop).

**Comment by kwight** [comment]
D43414-code will add a simplified static My Home view for the desktop app, to minimize any unexpected behaviour in the future. (This will also need a client update.)

**Comment by kwight** [comment]
https://github.com/Automattic/wp-calypso/pull/42187 is the client-side update.

**Comment by gwwar** [comment]
@kwight there's enough information in the UA string that we can fix this without a client update, then depend on the explicit flag for subsequent versions.

**Comment by mmtr** [comment]
Pushed an update to D43414-code that identifies the desktop app with a UA check, so we no longer an update in the client-side.

I also added a backwards-compatible view, so My Home if fixed when using WPDesktop 5.1.0 or below.

**Comment by rachelmcr** [comment]
Thanks for working on this so quickly! Just a note about the versions this affects: Version 5.1.1 (currently in beta, to be released on Monday) is the next release after 5.1.0, and this issue also affects that version. If the backwards-compatible fix could extend to 5.1.1 that should resolve it.

(I checked the schedule for the next desktop release but we don't have a [milestone](https://github.com/Automattic/wp-desktop/milestones) for it yet. At the earliest we would cut a new beta from current Calypso on Monday and release it two weeks after that as version 5.1.2 if there are no significant changes on the Electron side. cc @nsakaimbo)

**Comment by mmtr** [comment]
Thanks @racheleldracher! I updated D43414-code to extend the backwards-compatible view to 5.1.1.

<img width="1433" alt="Screen Shot 2020-05-14 at 11 28 42" src="https://user-images.githubusercontent.com/1233880/81926273-00fdc500-95e2-11ea-968e-2417647cf7c2.png">

Any future version will use the new view.

<img width="1433" alt="Screen Shot 2020-05-14 at 11 37 51" src="https://user-images.githubusercontent.com/1233880/81926315-0d821d80-95e2-11ea-8c0c-76ec73c3016f.png">

**Comment by kwight** [comment]
D43414-code is deployed, and no client changes were necessary; we should be all good here @rachelmcr 👍 Do let us know if anything else strange pops up!
