### ISSUE TITLE
Writing a new blog posts redirect the user to self-hosted WordPress site

### ISSUE THREAD

**Issue by khvnhtung** [Automattic/wp-desktop#879]
#### Steps to reproduce
1. Download WordPress v5.1.0 for macOS
2. Select an existing self-hosted WordPress site and add new post
3. The editor on WordPress app turn into an endless loading animation and redirects the user to the self-hosted WordPress site post editor.

#### What I expected
- I was supposed to write my blog post directly on the WordPress app.

#### What happened instead
- The app turns into a loading animation without a way to get out and redirects me to the blog post editor on my website.

#### App Version / OS version
5.1.0

#### Screenshot / Video
- Endless loading animation: https://imgur.com/a/CSpn1Jx
- My website blog post editor, sorry for the different language (add new post): https://imgur.com/a/CSpn1Jx

**Comment by rachelmcr** [comment]
Thanks for the report, @khvnhtung! This sounds like the issue we're tracking in https://github.com/Automattic/wp-desktop/issues/640, so I'm going to close this issue in favor of that one.

Although we haven't resolved the issue yet, we have identified that this problem currently occurs if you don't have Jetpack's [WordPress.com Secure Sign On](https://jetpack.com/support/sso/) (SSO) enabled on your site. You can enable SSO in the **WordPress.com log in** section under **Jetpack — Settings — Security** in your site's dashboard.
