### ISSUE TITLE
WP Desktop app on Mac OS X 10.8.5 doesn't work?

### ISSUE THREAD

**Issue by ClaudioConti** [Automattic/wp-desktop#92]
Why? On the download button is written "OS X 10.8+" but on my OS X 10.8.5 wont start.
Maybe I did something wrong?

**Comment by mkaz** [comment]
Unfortunately, it looks like we published outdated information for the version supported. The Electron platform that we build our app from only supports 64-bit binaries which is OS X 10.9 and up. 
From: http://electron.atom.io/docs/v0.36.7/tutorial/supported-platforms/
