### ISSUE TITLE
Editor: Add handling of new failure type

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-desktop#927]
Calypso has a new [editor failure type](https://github.com/Automattic/wp-calypso/pull/43248) added for when the iframed editor fails to load for an unknown reasons after 6 second timeout.

Once the above PR is merged the `notifyDesktopCannotOpenEditor` action will have a new `reason` - `REASON_BLOCK_EDITOR_UNKOWN_IFRAME_LOAD_FAILURE`. The app needs to decide how to handle this failure. The action will include the url to the wpadmin block editor for the given site.

#### Steps to reproduce
1. The easiest way to test is to temporarily hard code [const iframeUrl](https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L739)  to point to a url that causes an endless redirector loop.

**Comment by joweber123** [comment]
I had a report today from a user who is getting the error **An unhnadled error occurred. NaN**.  

I assume this has to do with this issue but I also wanted to note that the word *unhnadled* is spelled wrong.

I am coming here after reading through [this forum thread](https://wordpress.com/forums/topic/an-unhandled-error-occured-nan/) that had many users note the same issue. 

![Screen Shot on 2020-07-30 at 15:26:40](https://user-images.githubusercontent.com/24914028/88888341-1a292000-d279-11ea-9a4c-ca391792af60.png)

**Comment by nsakaimbo** [comment]
Thank you for the report, @joweber123! This issue (including the typo 😆) should be fixed in the forthcoming stable release (v6.0.1). In the mean time, the user can try switching to the beta channel to see if the latest beta improves their experience.
