### ISSUE TITLE
The Windows desktop app (WordPress.com.exe) does not execute following installation. (Win 10 64)

### ISSUE THREAD

**Issue by SaludoVencedores** [Automattic/wp-desktop#930]
#### Steps to reproduce
1. Download the install executable: https://wordpress.org/download/wordpress.com-win32-setup-5.2.0.exe
2. Run the executable and select "run Wordpress" as a finish step
3. Wordpress app runs; seems to have full functionality; close the app
4. Attempt to launch the app from the start menu entry -- crickets

#### What I expected
That the app would run when invoked

#### What happened instead
Crickets

#### App Version / OS version
5.2.0? 5.2.4?  Win 10 64 bit (with all current updates applied)

**Comment by rachelmcr** [comment]
@SaludoVencedores Thanks for the report! Could you try a fresh install of the latest version (6.0.0) and see if the issue persists? You can download the latest version at https://apps.wordpress.com/desktop/ or the [GitHub releases page](https://github.com/Automattic/wp-desktop/releases).

I tested installing version 6.0.0 (after uninstalling a previous version) on Windows 10 and it's working for me there, so I'm curious to hear how it goes for you.

**Comment by SaludoVencedores** [comment]
Yes, that version starts again. Thanks.

	-----------------------------------------From: "Rachel McR." 
To: "Automattic/wp-desktop"
Cc: "SaludoVencedores", "Mention"
Sent: Wednesday July 8 2020 7:46:20AM
Subject: Re: [Automattic/wp-desktop] The Windows desktop app
(WordPress.com.exe) does not execute following installation. (Win 10
64) (#930)

	@SaludoVencedores [1] Thanks for the report! Could you try a fresh
install of the latest version (6.0.0) and see if the issue persists?
You can download the latest version at 
[2]https://apps.wordpress.com/desktop/ [3] or the GitHub releases page
[4]. 

	I tested installing version 6.0.0 (after uninstalling a previous
version) on Windows 10 and it's working for me there, so I'm curious
to hear how it goes for you. 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [5], or unsubscribe
[6]. 

Links:
------
[1] https://github.com/SaludoVencedores
[2] https://apps.wordpress.com/desktop/
[3] https://apps.wordpress.com/desktop/
[4] https://github.com/Automattic/wp-desktop/releases
[5]
https://github.com/Automattic/wp-desktop/issues/930#issuecomment-655467970
[6]

**Comment by rachelmcr** [comment]
That's great news! Thanks for letting us know. :)

**Comment by SaludoVencedores** [comment]
Rachel,
Apparently I spoke too soon.  Today when I wanted launch the 6.0 version you linked me to and that I installed, it failed to start and gives no diagnostics.  Now, it looks like it is machine-specific to my desktop.  When I initially installed v6.0 I was on the road using my laptop.  When I got back, I installed v6.0 on my desktop and that is where it is failing to start.  I disabled all of my security software and tried launching it as Administrator, and still nothing.  I just now confirmed that it does start on the laptop.  Both laptop and desktop are non-networked Win 10 64 systems.

**Comment by nsakaimbo** [comment]
Hi, @SaludoVencedores: When you navigate to `Add or Remove Programs` and scroll the list to find `WordPress.com`, how many installations of the program do you confirm? There should only be one, but there was a bug from a while ago where a bug in the auto-updater on Windows resulted in a "ghost" installation left on the machine. Because of the duplicate installations, double-clicking the app wouldn't work. Not sure if this is the issue you're experiencing but worth double-checking.

The fact that it is machine-specific, i.e your desktop and not laptop, is also useful to know.

**Comment by SaludoVencedores** [comment]
Nicholas,

I see once instance (see attached) – WordPress 6.0.0.  If you know of the specific files that comprise the “ghost”, I can try to manually clean them.

It is true that the laptop has only ever had the one instance installed on it, while the desktop has had previous instances (5.4.2?) installed and subsequently removed.

Doug
