### ISSUE TITLE
Domains link is not working from the My Sites > My Home > Get Help card

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#931]
Steps to reproduce:

1. Go to My Sites > My Home.
1. Find the Get Help card.
1. Click on the "All about domains" link.

**Result:** a blank modal window pops up when the "All about domains" link in the My Sites > My Home > Get Help card is clicked from within the WPDesktop app. ([58s](https://cloudup.com/cKbbqeIdEPE))

**Note:** on the web, the "All about domains" link points to https://wordpress.com/support/domains/ and in the app it points to https://wordpress.com/support/all-about-domains/ and it appears the pop up window which displays the support link doesn't show search results if there are any in the same way the website does.

<img width="1280" alt="Screen Shot 2020-06-24 at Jun 24 3 01 54 PM" src="https://user-images.githubusercontent.com/1119271/85627852-6ce53b80-b62c-11ea-92fc-b181ce0d07e9.png">

<img width="1280" alt="Screen Shot 2020-06-25 at Jun 25 6 26 58 PM" src="https://user-images.githubusercontent.com/1119271/85808236-7ac0bc80-b711-11ea-8810-ef2f7ea1c7dd.png">

**Comment by nsakaimbo** [comment]
Fixed by Automattic/wp-calypso#43543.
