### ISSUE TITLE
npm shrinkwrap

### ISSUE THREAD

**Issue by mjangda** [Automattic/wp-desktop#94]
https://docs.npmjs.com/cli/shrinkwrap

Calypso uses shrinkwrap to avoid versioning problems (added in https://github.com/Automattic/wp-calypso/commit/9bc4c914c5b01058732014c82f20e7cdd5e7ca35). Desktop should to the same.

**Comment by nsakaimbo** [comment]
Closing - Calypso now uses package-lock.json, and wp-desktop does the same.
