### ISSUE TITLE
Comments no longer visible after auto-update to Wordpress 5.5

### ISSUE THREAD

**Issue by BruceSherwood** [Automattic/wp-desktop#952]
#### Steps to reproduce
1.
2.
3.
4.

#### What I expected
brucesherwood.net is a Wordpress.com site hosted at siteground.com. The recent automatic update to version 5.5 broke the comments on posts, as the comments were no longer visible. All that remained was the title stating how many comments there are. What siteground.com did for me was back up my site to use the previous version of Wordpress, which made the comments visible again. I had searched the web for the problem of hidden comments, but all I could find were instructions that apparently applied to earlier versions of Wordpress, as I could not find the menu options that were specified.

#### App Version / OS version
Windows 10, Chrome

**Comment by designsimply** [comment]
Thank you for the report! I will test this, and in the mean time may I please ask what version of the WordPress.com Desktop app you are running? If you are using Chrome as mentioned in your bug report, and not the WordPress.com Desktop app, can you confirm that for me?

**Comment by designsimply** [comment]
I tested viewing comments on a WordPress 5.5 Jetpack 8.8.1 site in the WordPress.com Desktop app version 6.0.2-beta1 as a first pass, and I was able to see comments in My Sites > Comments as well as in the Reader for the same site. I also checked the site in Chrome and I was able to see the comments displayed normally there as well. In my test, Jetpack was the only active plugin and Twenty Twenty was the active theme at the time of the test and I used macOS not Windows. This was a quick test to make sure comments are not broken catastrophically.

Further troubleshooting is needed to learn more and to find out exactly what happened in your case and where this issue should be reported. This repository is specifically for issues with the WordPress.com Desktop app. May I please ask that we move this to the WordPress support forum to learn more? The support volunteers should be able to guide you in some troubleshooting steps and help you learn where to post once you know more information about the problem.

In your forum post, it would be helpful to note:

* Type of site and versions (i.e. WP 5.5 Jetpack ?)
* Active theme
* Active plugins
* Were the comments gone from the WP Admin > Comments section too?
* If you were using a caching plugin, or if SitGround provides caching, did you try clearing the site cache on the server side?
* Did you clear browser cache in Windows Chrome to make sure the browser was looking at a fresh copy of the site?

Please read https://wordpress.org/support/topic/read-this-first-wordpress-5-5-master-list/#post-13238243 first and then post your original report plus the additional info requested in the form at https://wordpress.org/support/forum/how-to-and-troubleshooting/#new-topic-0

**Comment by designsimply** [comment]
Closing because we haven't had a reply back from the author after asking for more info 38 days ago and noting I'd be happy to re-open if another comment is posted here or we can also look into this again if it's reported in a new issue.

I am hoping that it was a caching issue in this case (which sounded possible to me!) and that it has been long since resolved.
