### ISSUE TITLE
Wordpress Desktop App keeps opening browser tabs whenever I use it. 

### ISSUE THREAD

**Issue by superpoweredfan** [Automattic/wp-desktop#958]
Every time I open the WordPress App to begin working, the app forces me to leave the plugin sidebar, which then fails to load the site. So then I have to go my site page where, after I attempt to start a new post, the app forces the browser open to a new tab. After I close the tab, it does it again. If I try to save the draft in the app, it forces open a new tab. If I add media to the post, it forces open a new browser tab. I don’t use my browser for WordPress posts, that is why I downloaded the app but the latest update is a mess. Please help as I now have a browser full of tabs for the same post.

#### Steps to reproduce
1.
2.
3.
4.

**Comment by jenhooks** [comment]
Hi @superpoweredfan ! I followed up with you on this via email, so I'm closing this issue.

**Comment by nsakaimbo** [comment]
For anyone else that might stumble upon this - Classic Editor support in both Calypso and the WordPress Desktop app has recently been deprecated. If a user has the Classic Editor plugin enabled, they will be redirected to use the editor in wp-admin.

On our to-do list is better in-app messaging around this to inform users of the reason for the redirect.
