### ISSUE TITLE
[Win7] Back mouse button doesn't work

### ISSUE THREAD

**Issue by Maggew** [Automattic/wp-desktop#96]
CTRL + 2 > Followed Sites > Click on an article 

When I try to use my back button on Windows WP Desktop App, I'm not returned to the Reader Stream.

**Comment by jasmussen** [comment]
I believe system buttons tap into universal shortcuts. So if we're able to make alt+left (or on a mac, CMD + left) to invoke the back command, I believe this issue will be fixed in turn. #219
