### ISSUE TITLE
Releases missing from GH releases page

### ISSUE THREAD

**Issue by popey** [Automattic/wp-desktop#966]
#### Steps to reproduce
1. Visit https://github.com/Automattic/wp-desktop/releases
2. Observe the release number

#### What I expected

Expect to see the latest release of Wordpress Desktop

#### What happened instead

Note that it's months old, and not consistent with what's downloadable from the home page.

#### App Version / OS version

Web browser.

#### Screenshot / Video

![Screenshot from 2020-12-04 11-30-46](https://user-images.githubusercontent.com/1841272/101158771-38869a00-3624-11eb-93af-223836d241c5.png)

**Comment by popey** [comment]
Forgive me for not reading the readme. :D

**Comment by designsimply** [comment]
I can totally see how it's easy to miss the readme note 🤔  maybe we can add a small notice at the top of the 6.0.2 release to help. I'll look into that next week.

**Comment by designsimply** [comment]
Updated! Thanks for asking about this :) https://github.com/Automattic/wp-desktop/releases/
