### ISSUE TITLE
[Win7] Keyboard hotkey ALT + (L) Arrow doesn't work

### ISSUE THREAD

**Issue by Maggew** [Automattic/wp-desktop#97]
CTRL + 2 > Followed Sites > Click on an article 

When I try to use my ALT + (L) Arrow hotkey on Windows WP Desktop App, I'm not returned to the Reader Stream.

**Comment by jasmussen** [comment]
If I understand you correctly, you're asking for the browser Alt + Left  "Back" shortcut key to function. There's a similar CMD + Left shortcut for OS X. 

It seems this is a popular request. So I'm reopening the old bug, and closing this as a duplicate. #219

**Comment by Maggew** [comment]
It's a very nice shortcut, one of my favorite Windows Operating shortcuts too.

Thanks!!

**Comment by jasmussen** [comment]
Just realized that ticket I was referencing was in an old repository. Sorry about that. I've opened a new ticket with your request. Thanks for your reports.
