### ISSUE TITLE
Suggest for Ureplied comments filter feature

### ISSUE THREAD

**Issue by lucidgen** [Automattic/wp-desktop#977]
Hello,
You have app on Desktop and Mobile, It make me control my website about to perfect. But I hope you can develop “Ureplied comments filter” feature in Manage comment area.
Thank you very much!

**Comment by nsakaimbo** [comment]
Thanks for using the app, and for the feature request. If you're still interested in this feature, please file the request in the http://www.github.com/Automattic/wp-calypso repository.
