### ISSUE TITLE
"Collapse menu" in WordPress.com desktop app

### ISSUE THREAD

**Issue by jonny-a8c** [Automattic/wp-desktop#980]
#### Steps to reproduce

1. In the WordPress.com desktop app, navigate to My Sites and select a site
2. In the left sidebar, click on "Collapse menu"

#### What I expected

I expected the left sidebar to collapse.

#### What happened instead

Both "Switch Site" and site title disappear, however the sidebar menu doesn't collapse (unlike desktop browser)

#### Screenshot / Video

<img width="1079" alt="Screenshot 2021-05-05 at 09 49 16" src="https://user-images.githubusercontent.com/39252765/117203964-e8fff200-adac-11eb-8ca2-2b032d640dff.png">

#### Context / Source

3962145-zen

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).
