### ISSUE TITLE
... tests with this apps on Fedora Linux distro ...

### ISSUE THREAD

**Issue by catafest** [Automattic/wp-desktop#985]
I tested and I found these issue: 
#### Steps to reproduce
1. download and unarchive
2. run with: ./wpcom on Fedora Linux distro ...
3. I don't see any security issue in this application, is like a light browser to Wordpress - build on Electron ...

#### What I expected to see on this type of application:
I expect to see:
1. good permission on files ...
[mythcat@desk wordpress.com-linux-x64-6.14.0]$ ls -la
total 176264
drwxrwxrwx    5 mythcat mythcat      4096 Apr 30 14:23 .
drwx------. 104 mythcat mythcat     12288 May 23 11:53 ..
-rwxrwxrwx    1 mythcat mythcat    124662 Apr 30 14:23 chrome_100_percent.pak
-rwxrwxrwx    1 mythcat mythcat    187289 Apr 30 14:23 chrome_200_percent.pak
-rwxrwxrwx    1 mythcat mythcat   4743960 Apr 30 14:23 chrome-sandbox
-rwxrwxrwx    1 mythcat mythcat  10527632 Apr 30 14:23 icudtl.dat
-rwxrwxrwx    1 mythcat mythcat    249240 Apr 30 14:23 libEGL.so
-rwxrwxrwx    1 mythcat mythcat   3064616 Apr 30 14:23 libffmpeg.so
-rwxrwxrwx    1 mythcat mythcat   6990656 Apr 30 14:23 libGLESv2.so
-rwxrwxrwx    1 mythcat mythcat   3908248 Apr 30 14:23 libvk_swiftshader.so
-rwxrwxrwx    1 mythcat mythcat   6710080 Apr 30 14:23 libvulkan.so
-rwxrwxrwx    1 mythcat mythcat      1060 Apr 30 14:23 LICENSE.electron.txt
-rwxrwxrwx    1 mythcat mythcat   4562357 Apr 30 14:23 LICENSES.chromium.html
drwxrwxrwx    2 mythcat mythcat      4096 Apr 30 14:23 locales
drwxrwxrwx    3 mythcat mythcat        17 Apr 30 14:23 resources
-rwxrwxrwx    1 mythcat mythcat   5035565 Apr 30 14:23 resources.pak
-rwxrwxrwx    1 mythcat mythcat     51449 Apr 30 14:23 snapshot_blob.bin
drwxrwxrwx    2 mythcat mythcat        43 Apr 30 14:23 swiftshader
-rwxrwxrwx    1 mythcat mythcat    172276 Apr 30 14:23 v8_context_snapshot.bin
-rwxrwxrwx    1 mythcat mythcat       107 Apr 30 14:23 vk_swiftshader_icd.json
-rwxrwxrwx    1 mythcat mythcat 134100640 Apr 30 14:23 wpcom

2. a good debug output , not like this: 

{"name":"calypso","hostname":"desk","pid":6948,"reqId":"ec9adc04-b5c7-49a4-aa52-17c68ea8c838","level":30,"method":"GET","status":200,"length":"12940","url":"/","duration":64.031,"httpVersion":"1.1","env":"desktop","userAgent":"Chrome 87","rawUserAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/6.14.0 Chrome/87.0.4280.67 Electron/11.0.4 Safari/537.36","remoteAddr":"127.0.0.1","msg":"request finished","time":"2021-05-23T08:56:52.127Z","v":0}
#### What happened instead
... is saw is a beta apps ... good luck !

#### Screenshot / Video
https://imgur.com/a/Vb6utTe  - simple use it

#### Context / Source

1. an encrypted authentication over the internet ... 
2. good permissions for files after unarchive - because is need to have it;
3. you have just: create the website and not add my website ...

**Comment by nsakaimbo** [comment]
Closing this issue as the application is officially only built and supported on Ubuntu.
