### ISSUE TITLE
Post editor showing blank on the Desktop app

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-desktop#988]
In Desktop App user cannot access editing pages and posts. They see just blank page instead, menu disappears and they have to click My Sites. In browsers it works well.

4124913-zd-woothemes - V 7.0.6, simple site, 

- Logs - 29c0b-pb/
- settings.json - 29c0c-pb/
- Paul asked further questions

4124931-zd-woothemes - V 7.0.6 on Big Sur version 11.4, simple site, 
- asked about Application Logs - no answer 
- Asked asked further questions too

**Comment by daria2303** [comment]
One more 4114772-zd-woothemes

**Comment by nsakaimbo** [comment]
Hi, @daria2303 - Please inform the user to download and install the latest version of the Desktop app (v7.0.6) from here if they haven't already.

If this issue still persists, it can be helpful to inspect their application logs (select "Get Application Logs" from the "Help" menu).

**Comment by daria2303** [comment]
Hi @nsakaimbo we are waiting for the first two Applications Logs, they attached to the last one already.
All use latest version of the app

**Comment by dcoleonline** [comment]
Here's another instance in 4126894-zd where they're using the desktop app v7.0.6 on macOS 10.15.7 Catalina.

They provided these logs late yesterday:
[wpdesktop-2021-07-09T19.58.31.123.zip](https://github.com/Automattic/wp-desktop/files/6795392/wpdesktop-2021-07-09T19.58.31.123.zip)

**Comment by nsakaimbo** [comment]
@daria2303 Thanks for sourcing the application logs - we're still looking into this. One additional troubleshooting step (not sure if they've tried this already):

Can the user try uninstalling the app - _including all caches_ - and then re-installing the application? Instructions for a complete uninstall are located here: 

PCYsg-6LX-p2

**Comment by nsakaimbo** [comment]
@daria2303  What happens when they click the "W" button in the top-left? Can they exit being stuck in this state?

**Comment by nsakaimbo** [comment]
@daria2303 @KokkieH In addition to the above, is it possible that the user can share a screenshot of what the app looks like when they run into this? The Gutenberg editor loads really slowly (even in a traditional browser) and I'm wondering if the app may be timing out in some way when trying to access the editor.

**Comment by pauljacobson** [comment]
Hi there @nsakaimbo, the user replied with logs here:

- Logs - 29c0b-pb/
- `settings.json` - 29c0c-pb/

It looks like we didn't ask the user the other questions, so I'll follow-up.

**Comment by daria2303** [comment]
@nsakaimbo we do not see the folders mentioned here PCYsg-6LX-p2 (checked by me and another HE: 4114772-zd-woothemes).
However in the first ticket 4124913-zd-woothemes user seemed to be able to see and delete them and it worked for them. Why don't we see these folders? (I deleted the app, but cannot see rest of the folders in Library directory)

**Comment by Robertght** [comment]
The user in 4126894-zen replied with the logs again after trying to uninstall&reinstall the app.

[wpdesktop-2021-07-17T12.02.10.836.zip](https://github.com/Automattic/wp-desktop/files/6840105/wpdesktop-2021-07-17T12.02.10.836.zip)

**Comment by CodeAllNightNDay** [comment]
I also have a user getting the white screen when editing or creating a post with the Desktop App on a MacBook Air.
Ticket: 4157746-zd-woothemes
This is what they see: https://d.pr/i/oW8gP7

**Comment by KirkwallDay** [comment]
Another case here: 4129502-ZD

They sent us an application log too, it's in the ticket if that will help. They did uninstall and re-install and still experience the issue.

**Comment by inaikem** [comment]
Hi @nsakaimbo 👋 Is there any more information we can obtain for you to help your efforts on this? Cheers!

**Comment by daria2303** [comment]
4126894-zd-woothemes told us that it is working now
