### ISSUE TITLE
"Unsupported Browser" on Linux

### ISSUE THREAD

**Issue by rodrigoprimo** [Automattic/wp-desktop#990]
I'm running version 7.1.0 of this app on my Ubuntu 21.04 machine. Today, when loading the app, I got an error message saying that my browser is not supported (see screenshot below). I can click on "Continue loading the page anyway" and everything seems to work, but I thought it was worth creating an issue in case this is something unexpected that you might want to check.

![Screenshot from 2021-08-10 10-23-10](https://user-images.githubusercontent.com/77215/128874783-697020b7-67d7-41ba-85d9-2cd0ae5e48eb.png)

**Comment by sandymcfadden** [comment]
Thank you @rodrigoprimo! This is fixed now with this revert https://github.com/Automattic/wp-calypso/pull/55317

**Comment by rodrigoprimo** [comment]
Thanks, Sandy.
