### ISSUE TITLE
[Feature request] Add ability to hide header menus

### ISSUE THREAD

**Issue by hwittenborn** [Automattic/wp-desktop#992]
Specifically I'm wanting to hide both of these:

![image](https://user-images.githubusercontent.com/74838472/130370037-a0839a88-4f1d-492e-87a3-3bd2d42306a6.png)

I'd like to be able to just use the app without anything else in the way.

**Comment by nsakaimbo** [comment]
@hwittenborn Have you tried using the `Toggle Full Screen` option from the `View` menu?

**Comment by hwittenborn** [comment]
@nsakaimbo I tried that option, but it just makes the app go (literally) fullscreen.

I'm wanting to hide the `File Edit View Window Help` row, as well as the `< > W` one.

**Comment by belcherj** [comment]
We will ad it to our list of feature requests. Closing for now.
