### ISSUE TITLE
WP App : Action Bar `Copy Shortlink` not working

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-desktop#993]
### Issue

The `Copy Shortlink` button in the action bar does not copy the short link of the site/page.

This is the button- 
<img width="283" alt="Markup 2021-09-17 at 18 18 25" src="https://user-images.githubusercontent.com/40609190/133784987-774bf3a2-0186-469a-9278-3bebc899922c.png">

Here is a recording of the issue for better understanding-
https://d.pr/v/PNbtRy

### What we expect

We expect that the short link of the site and the particular page should get copied to the clipboard normally as it does on the browser.

### Version

OS- Mac OS Mojave 10.14.3 
App- Version 7.2.0

Not yet tested on Windows App.

Reported here 4297537-zen

**Comment by nsakaimbo** [comment]
Thanks for the report! Confirmed this bug in the latest version of the app. Developer console shows the following error when this happens:

```
actionbar.js?v=20210917:122 Uncaught Error: prompt() is and will not be supported.
    at HTMLAnchorElement.<anonymous> (actionbar.js?v=20210917:122)
```

Worth noting that the behavior in a browser is to open a dialog prompt when this item is selected.

**Comment by sophiegyo** [comment]
User report from 4297537-zd indicates:
WP App is 7.2.0
Catalina 10.15.7

They're unable to update their Mac OS to a more recent version as the hardware is apparently too old.

**Comment by arunsathiya** [comment]
Hey @nsakaimbo, I am following up for the same ticket that Sophie linked above. 

>"Copy Shortlink" item in the top-right of a given post that does work as expected

Could you clarify where this option is? I am aware of a link on P2s, but is there a similar functionality on regular WordPress.com blogs too?

**Comment by nsakaimbo** [comment]
> Could you clarify where this option is? I am aware of a link on P2s, but is there a similar functionality on regular WordPress.com blogs too?

I was unaware that this link is exclusive to P2s and not "regular" posts - thanks for the info.

**Comment by nsakaimbo** [comment]
Update: looks like the code for the action bar doesn't live in Calypso, but in a separate repository: Automattic/actionbar. Specifically, the code responsible for this action is located [here](https://github.com/Automattic/actionbar/blob/a63f98d6509be7b37420de52d2459a090b3d6021/actionbar.js#L199-L202).

**Comment by arunsathiya** [comment]
@nsakaimbo Thanks for the patch! To confirm, is this update already available for customers or do they need to wait for a release? I am not seeing a milestone on that PR.

**Comment by nsakaimbo** [comment]
This patch will be in a forthcoming release (v7.3.0).
